akvo/rsr/static/rsr/v3/css/src/main.css, akvo/rsr/static/rsr/v3/css/src/main.scss, akvo/rsr/static/rsr/v3/js/src/react-project-main.js, akvo/rsr/static/rsr/v3/js/src/react-project-main.jsx, akvo/rsr/views/project.py, akvo/templates/organisation_main.html, akvo/templates/update_main.html
- The ratio of the images in the carousel has been updated
- This causes white spaces on the sides of most images, so the shadow on the side of the carousel box has been removed because this looks weird
- The images in the carousel, on the update main page and on the organisation main page are now clickable and show the original image in a new tab
=> [#901] Show original images and correct ratio

akvo/rest/views/organisation.py, akvo/rsr/static/rsr/v3/js/src/react-my-details.js, akvo/rsr/static/rsr/v3/js/src/react-my-details.jsx, akvo/templates/myrsr/my_details.html
On the 'My details' page it's now possible, in addition to selecting an organisation from the dropdown, to type in the long_name or name of an organisation in order to connect to an organisation.
=> [#1045] Improved typeahead for organisations

akvo/rsr/migrations/0086_created_stamps.py, akvo/scripts/organisations.csv, akvo/scripts/projects.csv
Data migration that populates almost all projects and organisations with a created_at timestamp
My running of this on a fresh RSR DB returns about half a dozen projects and one org missing a timestamp from both sources. Those could be hand patched, using the same date as the next lower numbered object. It's not strictly correct, but is probably good enough.
=> [#1116] Populate created at

akvo/templates/base.html
On project updates pages the ulrize filter was converting URIs to actual
html elements in the meta og:description elements.
Fixed by removing the urlize filter & also limit chars to 500. There is
no hard limit on that field but Google told that Facebook only shows max
300 so this gives us additional space if needed.
=> [#1257] Fixed meta og:description elements

akvo/rsr/static/rsr/v3/js/src/react-project-main.js, akvo/rsr/static/rsr/v3/js/src/react-project-main.jsx, akvo/rsr/views/project.py, akvo/templates/project_main.html
- #1262: Added ```<p>``` tags for newlines in the accordion
- #1264: Added goals overview to accordion
=> [#1262 #1264] Updated accordion on project main page

akvo/api/authentication.py, akvo/api/resources/project.py, akvo/api/resources/user.py
@kardan Could you check this? It should work now (http://rsr.akvotest.org/api/v1/project/1605/?format=xml&depth=2 now gives a different error when not logged in).
Since this is causing issues with a partner (VEI), whose website is down now (see #1259), we'd like to do a hotfix tomorrow.
=> 1289 tastypie auth

akvo/rsr/admin.py, akvo/rsr/migrations/0089_auto__del_field_transaction_receiver_organisation_ref__del_field_trans.py, akvo/rsr/models/project.py, akvo/rsr/models/transaction.py, akvo/rsr/static/rsr/admin/css/akvo_admin.css, akvo/templates/admin/rsr/organisation/change_form.html, akvo/templates/admin/rsr/project/change_form.html, scripts/deployment/pip/requirements/2_rsr.txt
Note that the 'user process' PR needs to be merged in first (because of migrations). Done in this PR:
- #1299 Make reporting organisation non-required in admin
- #1290 Add 'related projects' to project admin
- #1309 Updated django nested inlines library
- Bugfixes from that library
- Allows for tabbed inlines (some of the inlines have been set to tabbed instead of stacked)
- #1316 Remove categories, benchmarks and goals from project admin
- #1317 Update transactions
- Receiver and provider organisations now are related to the organisation model
- Transaction date can be null
- Transaction value can have 2 digits behind comma
- #1321 Remove partner types extra from partnerships in admin
=> [#1290 #1299 #1309 #1316 #1317 #1321] Project admin

akvo/settings/66_local.template
Since the Django Debug Toolbar is slow, we should not enable it by
default. Hence commenting out the section in the local settings template.
=> [1018] Disabled DDT by default

scripts/devhelpers/gulpfile.js, scripts/devhelpers/package.json
Besides adding plumber this also updates dependencies. Have to admit that I'm no nom expert so I first did npm update which I think updates my global gulp. Then I killed the scripts/devhelpers/node_modules dir and while in scripts/devhelpers issued npm install to get new modules.
If there is an error in a sass file or a jsx file file and row should be printed now.
=> 1333 gulp errors

akvo/rsr/static/rsr/v3/css/src/main.css, akvo/rsr/static/rsr/v3/css/src/main.scss, akvo/templates/organisation_main.html
The cleanest place to put the identifier seemed to be in "Details", above the address.
I also added some light spacing between the different blocks
before: 
after:
=> 1293 iati identifier

akvo/rsr/models/organisation.py
1. Go to organisation list page
2. Filter on location
3. Page should not break when showing at least one organisation
=> [#1454] Organisation sort SQL error fix

akvo/rsr/views/donate.py
The donation machinery was using a domain_url variable that the old
middleware applied to the request. Now just use the HTTP_ORIGIN instead.
=> [#1456] Fixed broken donations.

akvo/rsr/views/project.py, akvo/utils.py
1. Go to project list
2. Sort by something
3. Switch page, sorting should stay in place
=> [#1458] Sorting remains when switching pages

akvo/rsr/static/lib/scripts/react-typeahead-1.0.4.js, akvo/rsr/static/scripts-src/project-directory-typeahead.js, akvo/rsr/static/scripts-src/project-directory-typeahead.jsx, akvo/rsr/static/scripts-src/project-directory.js, akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/rsr/views/project.py, akvo/settings/40-pipeline.conf, akvo/templates/base.html, akvo/templates/myrsr/my_details.html, akvo/templates/myrsr/user_management.html, akvo/templates/project_directory.html, akvo/templates/project_main.html, akvo/templates/sign_in.html
#1052 
React-typeahead requires a React version of at least 0.12, so this PR bumps the version from 0.10. This might have wider consequences, but I haven't seen any so far.
=> [fixes #1052] Add react typeahead to organisation filter for project directory

akvo/templates/project_main.html
fixes #1549 by moving a closing </div> tag inside an if block. Also reverts fd92cfc which was against an out of date version of develop. Also standardises indentation
=> [#1549] Fix donation layout in release candidate

akvo/rsr/admin.py, akvo/rsr/migrations/0007_auto_20150512_1320.py, akvo/rsr/models/partner_site.py, akvo/rsr/views/organisation.py, akvo/rsr/views/project.py, akvo/rsr/views/project_update.py, akvo/templates/organisation_directory.html, akvo/templates/project_directory.html, akvo/templates/update_directory.html
=> [#1563] Add option for showing all objects on Akvo Pages maps

akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss
=> [#1596] keep nav menu on one line in ES and FR

akvo/templates/organisation_main.html
If there is an org url that is used as target, otherwise the link is removed.
=> [Fixes #1509] Updated logo link

akvo/templates/organisation_main.html
If project buckets are not empty they are now links.
=> [Fixes #1508] Project counts are now links

INSTALL.md
Top level INSTALL information contained 2 dead links. These have been replaced with current documentation links.
=> Updated INSTALL information

vagrant/README.md
For example. MySQL is no longer used in the RSR stack so references to
it were removed. vagrant command line example updated for latest version
syntax.
=> Minor changes to vagrant README

akvo/rsr/templatetags/maps.py
Akvo used to do a lot of logging when traversing locations for
lat / longs. This swamped the log file and also was not really
useful since lack of lat / long is ok for those collections.
=> [Fixes #1632] Not logging on no cordinates

akvo/rsr/admin.py, akvo/rsr/migrations/0012_partnersite_show_keyword_logos.py, akvo/rsr/models/partner_site.py, akvo/templates/partials/project_header.html
If a project is tagged with a keyword that has a logo and the
'show keyword logos' is enabled on a Akvo Page 2 keyword logos
can be seen on the project main page. This option takes the
keyword logos from normal non Pages RSR to Pages but as opt in.
=> [Fixes #1616] Adds keyword logos to Akvo Pages.

akvo/rsr/views/project.py
The indicator periods are listed in the order they are entered in the
admin.
Add order_by() call to sort by the IndicatorPeriod.period_start field.
=> [#1532] Sort indicators periods on period_start

akvo/templates/base.html
I hope this'll fix the issue.. Can't really test, but as far as I can tell Google doesn't use the ```og:description``` property. I think Facebook does use that though, so I've left it it. But also added the normal ```description``` tag that I believe Google uses.
=> [Fixes #1713] Use the meta name='Description' tag

akvo/rsr/static/scripts-src/myrsr-admin.js, akvo/rsr/static/scripts-src/myrsr-admin.jsx
Fixes #1785
Added a try, except clause to make sure that we don't try to store the API results to the local storage if there is not enough space in the local storage.
=> [#1785] Cached API results of local storage

akvo/rsr/static/scripts-src/myrsr-admin.js, akvo/rsr/static/scripts-src/myrsr-admin.jsx
Safari throws an error when using the new elHasClass helper function.
Test if classList.forEach is defined - if not, default back to using the regex to test for class presence.
#1765
=> [#1765] test for classList.forEach before using

akvo/rsr/static/scripts-src/my-iati.js, akvo/rsr/static/scripts-src/my-iati.jsx
#1790 
The target container for the React components only appears in the MyIATA page if certain template conditions are met. This PR checks for the existence of the target DOM element before attempting to invoke React.
=> [#1790] Check element exists before invoking React

akvo/rsr/models/organisation.py, akvo/rsr/views/my_rsr.py
Fixes #1843
Instead of using sets those methods can use querysets instead. I guess this would be in place of #1842 since it also fixes that bug.
=> [#1843] Refactor the Organisation.content_owned_organisations methods

akvo/rsr/models/project.py
Fixes #1465 
No data migration for leading or trailing spaces is created, since there were only 5 on Live, so this isn't very common.
=> [#1465] Strip project title and subtitle of trailing and leading spaces

akvo/templates/reportserver/BIRT/.project, akvo/templates/reportserver/BIRT/Project-results-single.rptdesign, akvo/templates/reportserver/README.md
Here is the BIRT part of #1831
=> #1831 project report with results

akvo/rsr/models/project.py, akvo/rsr/templatetags/rsr_utils.py, akvo/templates/project_directory.html, akvo/templates/project_main_tabs/summary.html, akvo/templates/rsr_utils/img.html
Fixes #1900: 
- Added the first 'can_create_projects' partner as the primary partner. I guess this will hold in almost all cases.
In addition, did two small changes as well..
- Removed the financial info part from the project main page (as there's a tab for that now).
- Set the geometry for the logo of partners without a logo correct on the finance page.
=> [#1900] Slight change in primary project partner

akvo/rsr/migrations/0040_auto_20151111_1300.py
Fixes #1932
Revert the migration code to not using the "real" Project model.
=> [#1932] Fix migration 0040

akvo/rest/views/indicator_period_data.py
=> [#2037] Change file_upload endpoint permissions

akvo/templates/inclusion_tags/maps.html
A lower case "w" trashes the js when clicking on pins. Fix by using upper case.
=> [#2100] Fix maps widget bug

akvo/rest/viewsets.py
@zzgvh We found a tiny bug in the API filtering PR. For ordering the API, the ```ordering``` parameter is used instead of ```order_by```.
=> [Fixes #2095] Change 'order_by' to 'ordering'

akvo/rest/viewsets.py
=> [#2163] Catch unknown fields in old API filtering

akvo/rsr/models/project_update.py, akvo/rsr/static/scripts-src/my-updates.js, akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/rsr/views/my_rsr.py, akvo/rsr/views/project.py, akvo/settings/40-pipeline.conf, akvo/templates/myrsr/my_projects.html, akvo/templates/myrsr/my_updates.html, akvo/templates/update_add.html, akvo/templates/update_main.html
Fixes #2149
Fixes #2191 (see #2198)
=> [Fixes #2149 and #2191] Project editing permissions

akvo/rsr/filters.py, akvo/templates/project_directory.html, akvo/templates/project_main_tabs/summary.html, akvo/utils.py
=> [#2189] Change project listing filters and hide status when not present

akvo/rsr/models/indicator.py, akvo/rsr/models/project.py, akvo/templates/myrsr/project_editor/section_5.html
=> [#2307] Update actual values entered in project editor

akvo/rest/serializers/result.py, akvo/rest/views/result.py, akvo/rsr/models/result.py
Fixes the main issue with the **result** endpoint. There's still going to be lots of queries for results in complex parent-child project hierarchies, but at least they'll be fast. I think what happens is that the first Result queryset is cached and then used in all other queries.
=> #2375 results performance

akvo/codelists/migrations/0004_auto_20160920_1045.py, akvo/rsr/migrations/0084_auto_20160920_1045.py, akvo/rsr/models/iati_import.py
The choices are obtained by listing subpackages of
`akvo.iati.imports.mappers`, and not sorting them can create unnecessary
migrations.
Also, add a couple of missing migration files from previous changes.
=> [Fixes #2371] Sort mappers_prefix choices

akvo/rsr/models/indicator.py
Prepend the text of an update to the corresponding indicator period's
`actual_comment` field.  Older comments may get stripped off, if the
length of all comment exceeds 2k chars.
Fix #2342
1. For a project, add a result with an indicator and an indicator period. 
2. Adding indicator period updates from My Results section, should update the actual_comment field for that indicator.
=> Update actual comment with update text

akvo/rsr/static/scripts-src/project-hierarchy.js, akvo/templates/project_hierarchy.html
To avoid overlaps, the arrows are placed at slightly different positions
based on the index of the connector for which we are using an arrow, and
the curviness of the connectors is also changed.
| Before        | After         |
| ------------- |---------------|
| ![mon oct 3 16 58 30 ist 2016](https://cloud.githubusercontent.com/assets/315678/19036071/269c2804-898b-11e6-85ba-6bad606227bc.jpg)      | ![mon oct 3 16 57 39 ist 2016](https://cloud.githubusercontent.com/assets/315678/19036057/1e267508-898b-11e6-9f90-d1a012da6498.jpg)  |
=> [#2366] Make arrows smaller and move them around

scripts/devhelpers/venv_exec.sh
The script makes it easier to run any commands in the Vagrant vm's
python venv.  The repository's root directory is the CWD, when running.
Fixes #2355
=> [#2355] Add script to run venv executables

akvo/rest/fields.py, akvo/rsr/tests/rest/test_project_update.py
When the POST has a multipart-encoded file, the file extension checks
don't happen, and unknown file types don't give a proper error.  This
commit adds a check on the file type even for these cases.
=> [#1577] Check project update photo file extension

akvo/rsr/admin.py, akvo/rsr/migrations/0085_auto_20160920_1448.py, akvo/rsr/models/project.py, akvo/rsr/tests/models/test_project.py, akvo/templates/project_main_tabs/finance.html
This is a follow-up pull-request to #2376. 
This PR adds a `donations` field on the `Project` model is used to keep track of any old donations that projects on the platform have already received.  In future, it can be used to keep track of donations received outside of RSR by manually updating it.
It also modifies an already merged migration (but not yet deployed), to populate the `donations` field correctly, for projects with donations.
=> Add a donations field to Projects

RELEASE_NOTES.md, akvo/rest/fields.py, akvo/rsr/tests/rest/test_project_update.py
This bug was introduced in 1aa60508350d4477c1f0964db7f3c124d9d1bc01
Any API POST where 'photo' field is None would fail, but I don't yet know what exact user action triggered this report: http://sentry.support.akvo-ops.org/rsr/live/group/1017/
Closes #2417
=> [#2417] project_update API POST fails when photo is None

akvo/rest/views/user.py, akvo/rest/viewsets.py, akvo/rsr/models/user.py, akvo/rsr/tests/rest/test_permissions.py
When `private_objects` were being filtered out of querysets of ViewSets subclassed from `PublicProjectViewSet`, every `private_object` in the queryset was iterated over and the permissions for the current user for it were verified.  As the number of private projects increases, this will get slower and slower.  
This commit tries to convert this Python loop into DB queries, to make the filtering of the `queryset` faster. The permission rules are parsed and converted to a `queryset` filter using `Q` objects and the filtering of objects for which a user doesn't have permissions happens within DB queries.  To ensure nothing has changed w.r.t permissions from before, tests have been added for `queryset`s of all `ViewSet`s subclassing from `PublicProjectViewSet`. 
Closes #2424
=> #2424 Make queryset filtering based on permissions faster

RELEASE_NOTES.md, akvo/rsr/migrations/0087_auto_20161110_0920.py, akvo/rsr/static/scripts-src/my-user-management.js, akvo/rsr/static/scripts-src/my-user-management.jsx
The user management page doesn't show any users when a single employment
shown on a page doesn't have a group assigned.  The post_save signal on
Employments actually tries to ensure that all Employments actually have
a Group and uses the 'Users' group as default.  But, the current DB
seems to have at least one Employment without a Group.
Fixes #2398 
Ideally, this should come with a data migration to fix any employments that don't have a group assigned. But, I'm not sure if we can should get that in, before a release.  I'll try working on that, now. This bug seemed like something that's an edge case that won't happen in the live DB, but it is currently happening. Hence, a "quick-fix".
=> [#2398] Fix users not showing when a user has no groups

RELEASE_NOTES.md, akvo/rest/views/user.py, akvo/rsr/signals.py, akvo/rsr/tests/rest/test_user.py
Employments are forced to have a non-null group, though the model does
allow null values, by trying to set a default group in the post_save.
But, this can fail if such an employment already exists, thus creating
an employment with a null group.  Multiple such employments with a null
group can get created, too.
This commit moves the setting of the group to the pre_save signal, thus
preventing an invalid employment from getting created.
Closes #2374, Closes #2122
=> #2374 Prevent duplicate employments

RELEASE_NOTES.md, akvo/rsr/management/commands/lock_unlock_periods.py, akvo/rsr/tests/commands/__init__.py, akvo/rsr/tests/commands/test_lock_unlock_periods.py
This commit adds a script to bulk lock and unlock indicator periods based on
project keywords.  All the periods on projects with the specified keyword can
be locked or unlocked at once.
Closes #2449
=> [#2449] Add script to lock and unlock periods by keyword

RELEASE_NOTES.md, akvo/rsr/tests/views/__init__.py, akvo/rsr/tests/views/test_my_rsr.py, akvo/rsr/views/my_rsr.py
To make it easier to work with the user management page, all the employments of
a particular user are shown together, and the users with the most newly created
employments are shown at the top.
Closes #2340
=> [#2340] Group employments by user, keep reverse chronological order

RELEASE_NOTES.md, akvo/rsr/management/commands/lock_unlock_periods.py, akvo/rsr/tests/commands/__init__.py, akvo/rsr/tests/commands/test_lock_unlock_periods.py
This commit adds a script to bulk lock and unlock indicator periods based on
project keywords.  All the periods on projects with the specified keyword can
be locked or unlocked at once.
Closes #2449
=> Release 3.18.3 Vilnius (hot-fix)

akvo/rest/views/user.py, akvo/rsr/tests/rest/test_user.py
With the DRF 3 update, the serializers behave slightly differently -- Default
values are not returned for data not passed explicitly to the serializer as
initial data.  This commit explicitly adds required values to the initial data.
=> [#2298] Fix requesting organization from UP app

RELEASE_NOTES.md, akvo/templates/update_add.html
This fixes the problem of some `ProjectUpdate`s not having a location, since
Chrome >= v50 has disabled GeoLocation API on insecure origins.
Closes #2479 
Click on the "Add an update" button in the top bar, in Chrome >= v50.  You should be shown an alert message asking you to use another browser.  Doing this in another browser should not show the message.
=> [#2479] Prompt using a different browser if geolocation disabled

akvo/rsr/static/scripts-src/cookie.js, akvo/rsr/static/scripts-src/cookie.jsx
React.createElement is incorrectly passed a text field as the `children`
argument.  This causes invalid HTML (`<input>user-input</input>`) to be
generated and causes the input element to lose focus while typing.
Thanks to @gabemart for the fix!
Closes #2473
=> [#2473] Test environment password dialog loses focus

akvo/rest/serializers/project_update.py, akvo/rsr/tests/up/test_up.py
Updates fail with a 400 when the photo caption/credit fields are not filled up, in the RSR UP app.  This commit restores backward compatibility in this aspect.
=> [#2298] Allow updates to be posted with no photo_{caption,credit}

RELEASE_NOTES.md, akvo/rsr/tests/views/test_account.py, akvo/rsr/views/account.py
To get the list of projects where a user has `change` permissions, use DB
queries instead of a loop wrapping DB queries to make the response much faster.
This fixes timeouts for users who are not rsr admins but have change
permissions for a lot of projects.
Closes #2494
=> [#2494] Switch to DB queries to get allow_edit_projects

akvo/rest/views/project_editor.py, akvo/rsr/tests/rest/test_project_editor.py
The ordering seems to have somehow messed up for one project, causing a bunch
of issues in production.  Not sure how exactly this happened, but ensuring that
all that the changes in this view happen in a single transaction should help
prevent such breakages in future.
Closes #2519
=> [#2519] Ensure sibling items have sequential 'order' before reorder

akvo/rest/viewsets.py, akvo/rsr/tests/rest/test_indicator.py
Not ensuring that `.distinct` is called on the queryset used by subclasses of
`PublicProjectViewSet` caused a bug where an indicator period was missing from
the results page of a project.  This commit fixes that bug.
This commit comes with a simple test, but the test isn't actually able to
reproduce the bug on production.  Not sure what exactly needs to be done to
reproduce that bug.
Closes #2507
Supersedes and Closes #2509
=> [#2507] Fix broken pagination on subclasses of PublicProjectViewSet

akvo/rsr/static/scripts-src/project-main/project-main-partners.js, akvo/rsr/static/scripts-src/project-main/project-main-partners.jsx
The url is now an absolute url and this breaks loading of partner logos.
Closes #2559
=> [#2559] Fix broken org logos in the partners tab

akvo/rest/views/indicator_period_data.py, akvo/rsr/static/scripts-src/my-iati.jsx, akvo/rsr/static/scripts-src/my-results.js, akvo/rsr/static/scripts-src/my-results.jsx
The attachments in indicator period updates can't be deleted because of changes in how DRF3 handles uploaded files.
Fix by adding DELETE method handling in indicator_upload_file() and corresponding method deleteFile in my-results.jsx
=> [#2561] Fix deletion of files in period updates

akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/rsr/tests/views/test_account.py, akvo/rsr/views/account.py, akvo/templates/registration/register.html
Add a hidden from field in the registration form. If this field contains data when a POST is made to the register view, discard the form and redirect to the RSR homepage.
The assumption is that if the honeypot field has data a bot has filled it in and we should discard the registration.
=> [#2454] Honeypot form field in registration

RELEASE_NOTES.md, akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/rsr/tests/views/test_account.py, akvo/rsr/views/account.py, akvo/templates/registration/register.html
The CSS for the honeypot field is getting applied to the search bar in the
project directory since they both have the same id.
=> [#2454] Change id of honeypot field to not match the search bar id

akvo/templates/registration/activation_email.txt, akvo/templates/registration/approved_added_email_message.txt, akvo/templates/registration/approved_request_email_message.txt, akvo/templates/registration/invited_user_message.html, akvo/templates/registration/invited_user_message.txt, akvo/templates/registration/user_organisation_request_message.txt, akvo/templates/results_framework/approve_update_message.html, akvo/templates/results_framework/approve_update_message.txt, akvo/templates/results_framework/approved_message.html, akvo/templates/results_framework/approved_message.txt, akvo/templates/results_framework/revise_update_message.html, akvo/templates/results_framework/revise_update_message.txt
Email context doesn't have a request and hence request.scheme doesn't work.
Since, we are making https the default, the URLs are hard-coded to use https.
=> [#29] Hardcode all urls in emails to use https protocol

akvo/rest/views/typeahead.py, akvo/rsr/static/scripts-src/project-directory-typeahead.js, akvo/rsr/tests/rest/test_typeahead.py
Show all organisations in the typeahead for organisations in the project editor on partner sites.  Any organisation could be added as a partner to a project, making it a partner for the site's organisation.  Showing only existing partners in this typeahead definitely doesn't make sense.
Closes #2624
=> [#2624] Show all orgs in project editor typeahead

akvo/rsr/models/user.py, akvo/rsr/static/scripts-src/project-editor.js, akvo/rsr/static/scripts-src/project-editor.jsx, akvo/templates/myrsr/my_projects.html, akvo/templates/myrsr/project_editor/project_editor.html, akvo/templates/myrsr/project_editor/project_editor_progress.html
=> [#2356] Enable publish & add project buttons only if user has perms

akvo/rsr/filters.py, akvo/rsr/models/project.py, akvo/rsr/tests/models/test_partner_site.py, akvo/rsr/tests/views/test_account.py, akvo/rsr/tests/views/test_project.py, akvo/rsr/views/project.py, akvo/templates/project_directory.html
`ProjectLocation`s associated with projects were being used to populate the list of options in the advanced filter for locations, while `RecipientCountry` locations are shown in the project directory, when showing information about each project.  This made the search buggy, and also hard to understand.  To make it easier for the user to understand how search is working, this code ignores the `ProjectLocation` countries completely, and simply uses the `RecipientCountry` values.
Closes #2623
=> Fix problems with Location advanced filter in project directory

akvo/iati/exports/elements/related_activity.py, akvo/rsr/models/project.py, akvo/rsr/models/related_project.py, akvo/rsr/tests/iati_checks/test_iati_checks.py, akvo/rsr/tests/iati_export/test_iati_export.py, akvo/rsr/tests/results_framework/test_results_framework.py
If a parent-child relation was also specified as a child-parent relation, the
IATI xml would have two related activities with both these relations.
Closes #2638
=> [#2638] Populate related activities only once in IATI xml

akvo/rest/views/typeahead.py, akvo/rsr/models/organisation.py, akvo/rsr/models/partner_site.py, akvo/rsr/models/project.py, akvo/rsr/models/user.py, akvo/rsr/views/organisation.py, akvo/rsr/views/project_update.py, akvo/rsr/views/utils.py, akvo/rsr/views/widgets.py, akvo/utils.py
- Private projects are meant to be viewed only by members of the organisations which are partners of the projects. Members of these organisations could be shown private projects in the project listings, etc., but to keep these pages simple, it was decided to exclude private projects from all the pages outside of MyRSR.
- The existence of private projects shouldn't be known to anyone outside of the organisations to which they "belong".  So, all public counts of projects must exclude private projects.
=> Do not list/count private projects anywhere outside of MyRSR

akvo/rsr/models/user.py, akvo/rsr/permissions.py, akvo/rsr/views/my_rsr.py
To prevent timeouts, especially when a user has multiple employments, the code in the `user_management` view and the permissions code has been optimized mostly using a bunch of selects/prefetches.
```markdown
Fixed user management page timeouts for users with too many employments - [#2651](https://github.com/akvo/akvo-rsr/issues/2651)
```
=> Optimize the permissions code and user_management view code

akvo/templates/myrsr/project_editor/related_objects/document_input.html
The `document_category_input.html` template is included using wrong category id
when being inserted, and causes the document category to not be saved when a new
document category is added.  This commit fixes the bug and closes #2658.
```markdown
Fixed problem with saving document category in some cases - [#2658](https://github.com/akvo/akvo-rsr/issues/2658)
```
=> [#2658] Document category input partial is included using wrong id

akvo/rsr/permissions.py
Groups can be deleted and recreated -- this happens in tests, though this may
not happen in the real code.  This breaks tests because cached group ids are not
the same as the current ids of groups in the db.
Instead, check for permissions using group names.  Groups are fetched from the
DB using names, everywhere.  We therefore move to comparing employment group
name with canonical names for checking permissions.
Fixes the broken tests on develop.
=> [#2651] Don't cache groups in the code

akvo/iati/exports/elements/result.py, akvo/rsr/tests/iati_export/test_iati_export.py
Looks like a copy-pasta error -- result description was being used instead of
the indicator description.
Closes #2686
```markdown
Bugfix
Indicator descriptions missing in IATI file [#2686](https://github.com/akvo/akvo-rsr/issues/2686)
=> [#2686] Fix missing indicator description in IATI exports

akvo/rsr/static/scripts-src/rsr.js, akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/templates/project_directory.html
This commit tries to keep the search bar at the top of the page, when the
advanced filters pane is open, even on reloads.
=> [#2552] Scroll to the search field when advanced filters are active

akvo/rest/views/typeahead.py, akvo/rsr/filters.py, akvo/rsr/static/scripts-src/project-directory-filters.js, akvo/rsr/static/scripts-src/project-directory-filters.jsx
This PR adds a couple of commits to make dynamic filters feel more responsive. 
1. Queries are speeded up by using `.values` and fetching only the data that is required, in a bunch of places. 
2. All options fetched from the server are cached. Though only the request for options when there are no filters selected is annoyingly slow, we cache all the responses because this makes clearing a filter feel very responsive. 
```markdown
Make dynamic filters more responsive by using client side caching of options [2552](https://github.com/akvo/akvo-rsr/issues/2552)
```
=> Make dynamic filters feel more responsive

akvo/rest/views/report.py, akvo/rsr/migrations/0099_report_organisations.py, akvo/rsr/models/report.py, akvo/rsr/static/scripts-src/my-reports.js, akvo/rsr/static/scripts-src/my-reports.jsx
This commit adds an organisation field to reports, to associate one or more
organisations with a report. The report option is displayed only to users of
those organisations or to admin users.
Closes #2697
=> [#2697] Show organisation specific reports only to those org users

akvo/rsr/static/scripts-src/project-directory-filters.js, akvo/rsr/static/scripts-src/project-directory-filters.jsx, akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/templates/project_directory.html
- Scroll so that the search bar is at the top of the page when filters are active
- Display the advanced filters sidebar ASAP, instead of waiting for response from server with options
- Trim white space in selected names
- Move down the total project count to use the empty whitespace at the bottom
- Increase side bar width slightly
This should make the experience of using the Dynamic filters much better, as suggested by @AkvoAnt.  Caching the options to make the whole experience more responsive also would help. That is coming in a separate PR.
=> Some minor UI and UX changes for Dynamic filters

akvo/rsr/context_processors.py, akvo/templates/base.html
Add back the code for generating the link to the custom CSS file that can be uploaded to an Akvo page
Also change the context variable name to `page_stylesheet` not to clash with Pipline's `stylesheet` template tag.
On rsr.test.akvo.org (I think this is the only test server where we can create a Page now that https is in force, but I don't recall the exact name to use) create a Page site and upload a cusom CSS file (can be "stolen" from an exising site). Check that the style is applied.
This fixes #2710
```markdown
Fix missing custom stylesheet for Akvo pages [#2710](https://github.com/akvo/akvo-rsr/issues/2710)
```
=> [#2710] Reinstate link to custom stylesheet for Akvo pages

akvo/rsr/static/scripts-src/cookie.js, akvo/rsr/static/scripts-src/cookie.jsx
Also, automatically focus the password input when the dialog is shown.
Closes #2719
```markdown
Make the password dialog on test environments more usable [#2719](https://github.com/akvo/akvo-rsr/issues/2719)
```
=> [#2719] Enable submitting the test env password modal using Return

akvo/rsr/static/scripts-src/my-results/components/App.jsx, akvo/rsr/static/scripts-src/my-results/components/Indicators.jsx, akvo/rsr/static/scripts-src/my-results/components/Periods.jsx, akvo/rsr/static/scripts-src/my-results/components/Results.jsx, akvo/rsr/static/scripts-src/my-results/components/updates/Updates.jsx, akvo/rsr/static/scripts-src/my-results/selectors.js, akvo/rsr/static/scripts-src/my-results/utils.js
Add Loading... messages on all accordion levels and add more checks to selectors making sure they work when the params they rely on are not populated yet.
This is a little hard to test. I used the throttling in Chrome to load the page at a crawl and then I got a short time window when not all models were loaded. As far as I could tell I could still interact with the page, opening the Results accordion and see how the aggregate values in the indicators appeared when the periods and updates were fetched.
Proper unit tests would improve the situation here 😉.
=> [#2730] Improve UI interaction before all models are loaded

akvo/rest/views/user.py, akvo/rsr/models/employment.py, akvo/rsr/tests/rest/test_user.py
Closes #2745
Verify that the end-point `http://rsr.localdev.akvo.org/rest/v1/user/30297/?format=json` doesn't 500. 
```
Problem with displaying report types for some kinds of users resolved - [#2745](https://github.com/akvo/akvo-rsr/issues/2745)
```
=> [#2745] Reports are not visible to some users

akvo/rsr/views/project.py, akvo/templates/project_directory.html
Page size is set using a `limit` query parameter. When filters are applied, a
form submission happens, and only the form data is submitted to the server. The
`limit` query parameter gets lost.  This commit adds a hidden field for the
limit parameter to the form, so that this data is retained even when form
submissions happen.
Closes #2684
- Go to the project directory
- Change the number of projects being view from 10 to 20/50/100. 
- Select one or more advanced filters and apply them
- Check that the results pages have the same number of projects per page, as chosen above
```
Don't reset the page size to the default value of 10, when filters are applied [#2684](https://github.com/akvo/akvo-rsr/issues/2684)
```
=> [#2684] Keep the set page size value even after filters applied

akvo/rsr/static/scripts-src/project-directory-filters.js, akvo/rsr/static/scripts-src/project-directory-filters.jsx, akvo/rsr/views/project.py, akvo/templates/organisation_main.html
The filter name was changed in a previous
commit (fa8094647b1270ec5aa28f15c09b10f7f1b24693) when the dynamic filter was
implemented.  But, a lot of links actually use the old filter, and hence are
broken.  This commit renames the query parameter to fix the problem.
Closes #2740
- The links to projects in different states (completed/post-completion, etc.) on the Organisation page should show the correct number of projects. 
For example: https://rsr.akvo.org/en/organisation/42
```
Fix broken links to projects in different states from the organisation page [#2740](fa8094647b1270ec5aa28f15c09b10f7f1b24693)
```
=> [#2740] Rename query parameter iati_status to status

akvo/rsr/static/scripts-src/cookie.js, akvo/rsr/static/scripts-src/cookie.jsx, akvo/rsr/static/scripts-src/project-directory-filters.js, akvo/rsr/static/scripts-src/project-directory-filters.jsx, akvo/rsr/static/scripts-src/rsr.js, akvo/templates/base.html
1. Click on the advanced search button to open the advanced filters pane. 
2. Reload the page to see that the advanced filters pane is open.
```
Open the advanced filters pane if it was previously opened, not otherwise [#2741](https://github.com/akvo/akvo-rsr/issues/2741)
```
=> Use a cookie to detect if advanced filters pane should be open or not

akvo/rsr/static/scripts-src/my-results/selectors.js
Instead of aggregating the updates on the client side, we directly use the
actual value on the period, so that
1. we remove duplication of this aggregation computation on the client side
2. handle the case when a period has no updates, but the actual value has been
set directly on the period.
Closes #2738
```markdown
Use the actual value for a period entered in project editor if there is one and no updates have been added to the period. [2738](https://github.com/akvo/akvo-rsr/issues/2738)
```
=> [#2738] Use actual value of a period directly

akvo/settings/66_local.template
Serving of all pages is delayed by about half a minute, since the node_modules
dir created in the static root is too big for the pipeline collector to handle.
=> [#2735] Disable pipeline collector in development mode

akvo/rsr/static/scripts-src/project-directory-filters.js, akvo/rsr/static/scripts-src/project-directory-filters.jsx, akvo/rsr/tests/deployed_code_tests.py, akvo/templates/base.html
This commit adds a polyfill version for it in the advanced filters code to get
it working in IE. Object.assign seems to be used in the new results framework
too, but the bundles seem to have polyfill implementations in them.
Also, add a polyfill version of Promise (used by fetch.js) for browsers that
don't implement it.
Closes #2785
Run the test script for testing if the advanced filters is shown in IE, by running the following command
```bash
$ BROWSERSTACK_URL=<URL> RSR_ENV="uat" python akvo/rsr/tests/deployed_code_tests.py
```
The value to use for `<URL>` can be obtained from the first example on this page: https://www.browserstack.com/automate/python
To test if the test works, this branch can be deployed on the `dev` server and RSR_ENV can be set to "dev" when running the command …
=> [#2785] Object.assign is not implemented in IE

akvo/rest/views/indicator.py, akvo/rsr/models/indicator.py
When an indicator has lots of child_indicators, computing the property
`children_aggregate_percentage` does too many queries. A result with a bunch
of such indicators times out during the call
`/rest/v1/indicator/?result__project=5659`
Closes #2782
```
Improve response time for results frameworks with many child indicators [#2782](https://github.com/akvo/akvo-rsr/issues/2782)
```
=> [#2782] Too many queries to figure if indicator should aggregate

akvo/rsr/management/commands/undo_results_import.py
The import undo is essentially just deleting all the results that have a parent
result attached to them, from the specified projects.
Closes #2798
```
Add management command to undo imported results for projects [#2798](https://github.com/akvo/akvo-rsr/issues/2798)
```
=> [#2798] Add a command to undo results imports for specified projects

akvo/rsr/static/scripts-src/my-results/components/Periods.jsx, akvo/rsr/static/scripts-src/my-results/components/updates/Updates.jsx, akvo/rsr/static/scripts-src/my-results/selectors.js
The constant name was changed in the changes for the qualitative measure, but
the merge with percentage aggregation branch probably messed this up.
1. Verify that the "Insert reporting value" button does not appear for %age indicator periods which already have an update.
=> [#2446] Fix incorrect constant name - PERCENTAGE_MEASURE

akvo/rsr/static/scripts-src/my-results.js, akvo/rsr/static/scripts-src/my-results.jsx
Checks for whether the data is relative have been removed, and all data is
treated as relative data, since the `relative_data` flag is no longer present.
=> [#2790] Remove references to relative_data field in old UI

akvo/iati/imports/mappers/dates.py, akvo/rsr/tests/iati_import/test_iati_import.py
The IATI import is not working correctly for the activity-date tag.
This seems to be because the way "falsey" element values is determined have changed in the lxml library.
Fix by explicitly checking if the element is None.
=> [#2843] Fix activity-date IATI import

akvo/rsr/models/__init__.py, akvo/rsr/models/indicator.py, akvo/rsr/tests/rest/test_permissions.py
Change permissions for OrganisationIndicatorLabel so they can be managed in the django admin by RSR admins.
Also set on_delete on IndicatorLabel.label to models.PROTECT to avoid foot shooting in the admin.
=> [#2854] Change permsissions for OrganisationIndicatorLabel

akvo/rsr/static/scripts-src/project-editor.js, akvo/rsr/static/scripts-src/project-editor.jsx, akvo/templates/myrsr/project_editor/related_objects/indicator_input.html
Closes #2875
Verify that the qualitative indicator does not show the indicator dimension fields. Changing the type should toggle the display of indicator measure and indicator dimension fields.
```markdown
[#2875] Hide Indicator Dimension fields for qualitative indicators [#2875](https://github.com/akvo/akvo-rsr/issues/)
```
=> [#2875] Hide Indicator Dimension fields for qualitative indicators

akvo/rsr/static/scripts-src/my-results/components/App.jsx, akvo/rsr/static/scripts-src/my-results/selectors.js
Closes #2878
Set the Indicator nodes to be opened so that the period headers are visible.
=> [#2878] Set default view of Results on project page

akvo/templates/myrsr/project_editor/related_objects/indicator_period_input.html
We could've set some hidden fields in the validation sets, but since we are
changing the template to prevent the page from looking weird, we are going to
need to change back the template if we are going to add those fields back. The
change cannot be made without a deploy, and we might as well change the template
in that case.
Closes #2666
```markdown
Remove the actual value and actual value comments from the project editor [#2666](https://github.com/akvo/akvo-rsr/issues/2666)
```
=> [#2666] Remove actual value and comment fields from project editor

akvo/rsr/static/scripts-src/my-results/components/Periods.jsx
The check to see if we should show the edit button has an incorrect referenct to the period.
=> [#2880] Fix bug when opening percentage indicators

akvo/rsr/models/organisation_indicator_label.py, akvo/rsr/templatetags/project_editor.py, akvo/rsr/tests/rest/test_project_editor.py
Instead of just relying that we have the right primary organisation for the
project, we choose to display labels defined by all partners instead. In future,
this may turn out to be a problem, when multiple orgs define long lists of
labels.
Closes #2890
```markdown
Show OrganisationIndicatorLabels belonging to all partners [2890](https://github.com/akvo/akvo-rsr/issues/2890)
```
=> [#2890] Show OrganisationIndicatorLabels defined by all partners

akvo/rest/views/project_editor.py, akvo/rsr/tests/rest/test_project_editor.py
=> [#2897] Handle error being passed to add_error instead of message

akvo/rsr/static/scripts-src/my-results/selectors.js
Closes #2913 
The aggregate actual value calculation fails for percentage indicators without periods.
Fix by adding a check to see if there are periods.
```markdown
The aggregate actual value calculation fails for percentage indicators without periods [#2913](https://github.com/akvo/akvo-rsr/issues/2913)
```
=> [#2913] Fix percentage indicators without periods

akvo/rest/serializers/indicator_period.py, akvo/rest/views/indicator_period_data.py, akvo/rsr/models/__init__.py, akvo/rsr/models/result/indicator_period_data.py, akvo/rsr/models/user.py, akvo/rsr/permissions.py, akvo/rsr/tests/rest/test_indicator_period_data.py
Closes #2861 
This PR hides draft updates from all users who haven't created them, unless the user is an admin/superuser.
=> Draft updates should be shown only to the user who created them

akvo/rsr/static/scripts-src/project-editor.js, akvo/rsr/static/scripts-src/project-editor.jsx, akvo/templates/myrsr/my_results.html
- The button should now be a simple pencil icon
- Clicking on the icon should take you to the project editor page, scrolled to the results section, expanded. 
```markdown
Change the 'Edit Project' button in the Results Framework [#2935](https://github.com/akvo/akvo-rsr/issues/2935)
```
=> Change the project editor link in the results framework

akvo/rsr/models/project.py, akvo/rsr/models/result/indicator.py, akvo/rsr/models/result/indicator_period.py, akvo/rsr/tests/results_framework/test_results_framework.py
This commit fixes bugs in the save methods of indicator and indicator period, which causes updates in the results framework of parent frameworks to break the child projects. 
There are still some models (#2950 for instance) in the results framework that need to be handled correctly when doing imports, but this can come as a separate pull request.  
| Model                            | Imported on fresh import? | New instances imported?     | Changes to instances propagated?                  |
|----------------------------------|---------------------------|-----------------------------|---------------------------------------------------   |
| `Result`                        | Yes                       | Not automatic; Import again | Yes                                               |
| …
=> Fixes to how changes are propagated into imported results framework

akvo/rsr/management/commands/fix_utz_periods.py
The bug in #2951 caused some corrupted data to be stored in a UTZ project. This
script essentially cleans up the mess, and recreates the data correctly. This
script, though, seems to run needlessly slowly. There might be scope for some
optimization in the child/parent detection code.
=> [#2951] Data fix script for UTZ

akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss
Closes #2962 
The style to hide the honeypot field on the registration page went missing very soon after the field was added. Quick look at the git commit history doesn't explain exactly what happened, looks like for some reason the added CSS was removed in a later commit that had an older parent than the one where the style was added.
```markdown
Honeypot field on register page visible [#2962](https://github.com/akvo/akvo-rsr/issues/2962)
=> [#2962] Hide honeypot field on registration page

akvo/rsr/tests/rsr_utils/test_utils.py, akvo/utils.py
Closes #2933
utils.codelist_choices() acquired a bug when translating the codelists was introduced.
The reason for this is that codelist_choices assumes the "code" column always is the first one. This is not certain when the codelists are translated.
Fix by always finding the position of the "code" and "name" columns of the codelist.
```markdown
File type bug in project editor [#2933](https://github.com/akvo/akvo-rsr/issues/2933)
```
=> [#2933] Fix codelist_choices

akvo/rsr/static/scripts-src/my-results/components/App.jsx, akvo/rsr/static/scripts-src/my-results/components/FilterBar.jsx, akvo/rsr/static/scripts-src/my-results/selectors.js
The overview being whith the results nodes opened, and the indicators are closed.
Closes #2949 
```markdown
The public Results view should open as Overview [#2949](https://github.com/akvo/akvo-rsr/issues/2949)
```
=> [#2949] Change opening view of Results to always be "overview"

akvo/rsr/management/commands/recalculate_periods.py
The script that fixes orphaned periods does not recalculate the fixed parent
periods, and hence the aggregated actual values are still incorrect.
=> [#2946] Add a script to recalculate periods

akvo/rsr/static/scripts-src/my-results/components/updates/Updates.jsx
For some reason the attachments in updates were only shown for qualitative indicators.
Closes #2968
=> [#2968] Show attachments for all indicators

akvo/iati/exports/elements/result.py, akvo/rsr/tests/iati_export/test_iati_export.py
Closes #2965
```markdown
Exclude data from qualitative indicators from IATI export files [#2965](https://github.com/akvo/akvo-rsr/issues/2965)
```
=> [#2965] Exclude qualitative indicators from that IATI export

akvo/rest/views/report.py, akvo/rsr/tests/rest/test_reports.py
Only the reports belonging to no organisation or those where a user has approved
employment are shown to users.
Closes #2990
=> [#2990] Add tests for reports displayed to users

akvo/rsr/models/project.py, akvo/rsr/models/result/indicator_period.py
Closes #3010
```markdown
Adding a new period to parent results framework is super slow [#3010](https://github.com/akvo/akvo-rsr/issues/3010)
```
=> [#3010] Bunch of select related calls when adding child periods

akvo/rsr/models/user.py
The REQUIRED_FIELDS attribute on the User model should include 'email' so that the createsuperuser management command works.
Closes #3016
=> [#3016] Set email as required field in User

akvo/iati/checks/fields/results.py, akvo/rsr/static/scripts-src/project-editor.js, akvo/rsr/static/scripts-src/project-editor.jsx
This is a hack to set the measure value of qualitative indicators automatically
in the project editor.  The field is hidden, but the validation doesn't ignore
the field and it's quite hard to change that without changing a lot in the
validation logic.
Closes #3019
=> [#3019] Set a measure value for qualitative indicators automatically

akvo/rsr/management/commands/rsr_sync_pgviews.py, akvo/rsr/models/__init__.py, akvo/rsr/models/result/__init__.py, akvo/rsr/models/result/indicator_period_aggregation.py, akvo/settings/10-base.conf, scripts/deployment/pip/requirements/2_rsr.txt
First cut of a Postgres view aggregating a value.
The view calculates the "actual value" of an indicator period, i.e. the sum of all value fields on the period's approved updates.
Also includes a management command script. This is a "fixed" version of the manangement command included in django-pgviews, since the original script only works with Django 1.9+.
=> [#3026] Postgres views of aggregated values

akvo/rest/views/organisation_indicator_label.py, akvo/rsr/tests/rest/test_permissions.py
OrganisationIndicatorLabelViewSet should inherit from BaseRSRViewSet since it has no association with a project.
=> [#3028] Fix base class of OrganisationIndicatorLabelViewSet

akvo/rsr/management/commands/remove_implementors.py
The script removes implementing partners from EUTF 'DEC' projects that are also present on a child, 'CTR', project.
=> [#3055] Management script removing EUTF implementing partners

akvo/rsr/views/my_rsr.py
=> [#3034] Raise Http404 instead of returning it when project not found

akvo/rsr/static/scripts-src/project-main/project-main.js, akvo/rsr/static/scripts-src/project-main/project-main.jsx, akvo/templates/project_main.html
Closes #1935
- Open any project page
- Go the summary tab
- Switch to any other tab, and wait for at least 5 seconds (for one carousel transition)
- Switch back to the summary tab, carousel should still be working, though it resets to first picture
=> [#1935] Unmount carousel when not in summary tab, and remount it

akvo/rsr/static/scripts-src/my-results/actions/model-actions.js
UpdateAttachments component looks at the `photo` and `file` attributes of an
update, but only `photo_url` and `file_url` attributes are set upon uploading
photos and attachments.
Closes #3006
=> [#3006] Update attachment and photo url after upload

.prettierrc, akvo/rsr/static/package.json, git_hooks/pre-commit
Closes #3088
I've added a `pre-commit` hook, if someone prefers to use that. 
But, I personally prefer Editor integration.
=> [#3088] Add initial configuration for prettier

akvo/rsr/migrations/0124_auto_20180309_0923.py, akvo/rsr/models/result/indicator_period_data.py
Extend the maximum file name length for the photo and file fields to 255 cars,
since the name includes the path making the effective max length of the actual
file name around 50 chars with the default max_length of 100.
Closes #3157
=> [#3157] Extend file name length in IndicatorPeriodData

akvo/rsr/models/partnership.py, akvo/rsr/signals.py
Adding partners seems to cause the following query to run, multiple times, when
`self.project` is accessed on a partnership
```sql
SELECT ••• FROM "rsr_project" ORDER BY "rsr_project"."id" DESC
```
This is a slow query and takes about 1.5seconds to run.  This commit prevents
such queries from running and improves performance, when adding multiple
partners to a project.
Closes #3121
=> [#3121] Make adding partners slightly faster

akvo/rsr/models/user.py
Broken filtering of employments in user.approved_employments caused users to
have permissions which they were not supposed to have. This commit fixes the bug
and restricts users in the Users group to only have the intended permissions.
=> Release v3.36.7 (hot-fix)

akvo/rsr/permissions.py, akvo/rsr/tests/test_permissions.py
The permission predicates for is_org_user and is_org_enumerator were returning
True for None objects without checking if the user has a corresponding
employment of that kind. This isn't a problem for the User group, because users
in the User group have the least permissions, so this bug didn't really manifest
anywhere. When the enumerator role is added, though, users in the Users group,
but not in the Enumerators group will get permissions to add indicator updates,
for example.
=> [#3205] Fix subtle bug with user & enumerator permissions for None

akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss
EUTF's project codes are in the subtitles and they are cut off with the current
max-width. Increasing this makes the entire project code visible.
Closes #3270
=> [#3270] Increase max-width for subtitle in my projects listing

akvo/rsr/management/commands/single_period_indicators.py
Change the behaviour slightly when more than one period is encountered.
If there's more than one period, check if only one if "modified". If so keep the modified period and delete the others.
A period is modified if one of the fields target_value, target_comment, actual_value or actual_comment has a value or the period has at least one update.
=> [#3278] Update singe_period_indicators management script

akvo/rest/views/project.py, akvo/rsr/static/scripts-src/directory-utils.js, akvo/rsr/static/scripts-src/directory-utils.jsx
Due to incorrect hard-coded default page size, there can be empty pages in the
pagination shown on directory pages.
Closes #3289
=> [#3289] directories: Fix incorrect pagination

akvo/rsr/static/scripts-src/project-editor.js, akvo/rsr/static/scripts-src/project-editor.jsx
The update location and upload logo calls are made asynchronously, and the
server has a race condition where it over-writes the logo data written, when
updating the location.
This commit makes update location call synchronous, and updates the logo, only
after the location call has finished. This fixes the bug, though it might
actually be better to fix the server to handle such writes, better.
Closes #2742
=> [#2742] Fix race condition when creating new org from project editor

akvo/rsr/static/scripts-src/rsr.js
Create and use a google.maps.MarkerImage object to get the placement of the marker to use the icon's center for positioning.
closes #3312
=> [#3312] Fix map marker placement

akvo/rsr/static/scripts-src/project-editor.js, akvo/rsr/static/scripts-src/project-editor.jsx
Don't show the text explaining which group of fields are together a mandatory OR
field group, when even one of those fields has already been filled in.
Closes #3314
=> [#3314] project editor: Only mark empty mandatory OR fields

akvo/templates/results_base.html
JSON holding information about a project in the results template fails to parse
if there is no primary organisation for a project.
Closes #3344
=> [#3344] results template: Use null value no primary_organisation

akvo/rsr/static/scripts-src/rsr.js
On smaller screens, the zoom level is sometimes set to 1, to be able to show all
the location markers on the map. We had some custom logic to prevent such zoomed
out maps, which doesn't seem to be working well.
This commit removes this logic and lets the maps API figure out what the best
zoom level for the current screen would be.
Closes #3327
=> [#3327] project directory map: Allow zoom levels less than 2

akvo/rsr/static/styles-src/akvo-wordpress.css, akvo/rsr/views/project.py, akvo/settings/40-pipeline.conf, akvo/templates/base.html
The akvo-wordpress.css stylesheet is used when a request includes the `iframe` query string parameter.
This is so that projects loaded on Akvo's Wordpress site can show the projects without the "chrome" of the header, footer and navigation.
=> [#3358] Add custom stylesheet

akvo/rest/views/project.py, akvo/rest/views/project_editor.py, akvo/rsr/models/project.py, akvo/rsr/static/scripts-src/my-projects.js, akvo/rsr/tests/rest/test_project.py, akvo/rsr/views/my_rsr.py, akvo/templates/myrsr/my_projects.html
Creation of a project makes multiple API requests, apart from the actual request
to create a project.
- Adding a reporting organisation to the project
- Making a LogEntry for the project creation
- Setting up custom fields for the project
These can be moved to the backend to make things faster on the client side.
=> [#3363] Move the project creation book-keeping API calls to backend

akvo/rsr/context_processors.py, akvo/settings/85-gmaps.conf, akvo/templates/inclusion_tags/maps.html, akvo/templates/organisation_directory.html, akvo/templates/organisation_main.html, akvo/templates/project_directory.html, akvo/templates/update_directory.html
Closes #3368
If the map is loaded on a domain that is not supported, the map automatically fails to load. We need to ensure that all the partner sites, all the akvo test servers, local development environment, etc., are able to use the map apart from the live rsr.akvo.org site.
=> [#3368] Use an API key with all maps requests

akvo/rsr/management/commands/remove_default_periods.py
The script sets default_periods to False for all indicators of a single period hierarchy of projects
=> [#3383] Script setting Indicator.default_periods to False

akvo/rest/serializers/user_projects.py, akvo/rsr/tests/rest/test_project_access.py
Trying to speed-up the UserProjectAccessSerializer.update method broke it. In
the case where a user had access to projects which the current admin cannot
administer, raised an InvalidPermissionChange error.
This commit fixes that bug.
=> [#3355] Fix changing access for user with projects in other org

akvo/rsr/templatetags/maps.py
The extra_context is added only to template rendering for views. When rendering
the templates for inclusion_tags, the extra variables defined using
`extra_context` don't get passed. This causes the map URLs in the projects map
widget to show a warning about missing Google Maps API key.
This commit fixed the problem, that was assumed to have been fixed with
453088143f0f55967af4ded762089aca72bb2abd.
=> [#3368] Fix missing gmaps_api_key in inclusion_tags templates

akvo/rest/serializers/indicator.py, akvo/rest/serializers/indicator_period.py
Remove the ReadOnlyFields parent_indicator and parent_period from the respective serializers.
This will allow updating those fields.
NOTE: validation for those fields and parent_result in the ResultRawSerializer should be added before this is put in production.
=> [#3413] Remove parent_indicator and parent_period fields

akvo/rsr/management/commands/delete_empty_projects.py
The script looks for projets in the LogEntry table that have only one entry of the type ADDITION.
See help and comments in delete_empty_projects.py for more details.
=> [#3439] Script to delete empty projects

akvo/rsr/static/scripts-src/my-results/components/Reports.jsx, akvo/rsr/static/scripts-src/my-results/utils.js
Some browsers have timezone information in the dates, and this causes problems
with the dates used to generate the reports. Instead, we format the date using
our own helper function
Closes #3444
=> [#3444] Don't use date.toISOString() to get report start/end dates

akvo/rsr/static/scripts-src/my-results/components/Reports.jsx
Reports are generated with wrong dates if the date has timezone information,
which happens in the latest version of Chrome (and may be other browsers).
Keeping the timezone information will generate the correct date string for the
report server to use.
Closes #3444
=> RSR release 3.40.5 Managua hot-fix 

Dockerfile, Dockerfile-dev, akvo/settings/90-finish.conf, scripts/docker/dev/start-django.sh, scripts/docker/prod/start-django.sh
Installing and starting manually cron, to run the Django cronjobs
Not using k8s cronjobs because the end result of the cronjobs need to be 
writen to the media folder, which is can be mounted as writable by just one
container.
Fixes #3455
=> Adding cron jobs to backend container

akvo/rest/viewsets.py, akvo/rsr/models/__init__.py, akvo/rsr/models/user.py
Enumerators had change permissions on indicator period data (updates), but did
not have view permissions on the indicator periods, indicators or results that
are needed to populate this framework.
This commit adds a view_ permission on these hierarchical objects for the
enumerator. Everyone who has a `change` permission is assumed to have `view`
permissions already.
This commit also changes the code used to filter out objects in a queryset for
logged in users who are not admins. Previously, the objects were filtered based
on whether the user has `change` permissions on an object. This has now been
changed to check for `view` permission if the request is a `GET` and otherwise
check for the `change` permission.
Closes #3457
=> [#3457] Let enumerators view private projects' results framework

ci/k8s/deployment.yml, scripts/docker/prod/start-django.sh
Being more lenient by changing the liveness threshold to 2 mins.
Also, added an additional worker so we can handle more concurrent requests
See #3476
=> Backend fails liveness probe in production

akvo/rsr/front-end/scripts-src/classic/jsx/my-iati.jsx, akvo/rsr/front-end/styles-src/main.scss
Opening a large IATI xml file can take a while. The links are currently opened
using a js call, which hangs up the current tab. We now use a simple html link
instead of a js call to open the IATI xml files.
Closes #3504
=> [#3504] myrsr/iati: Use a link instead of opening new tab in js.

akvo/rsr/front-end/lib/scripts/react-onclickoutside.js
Datepickers don't go away when clicking outside them, since `react-onclickoutside` didn't load properly with the new webpack setup.  This commit fixes that.
=> [#3340] Fix react-onclickoutside loading with the new webpack setup

akvo/rsr/management/commands/create_collaborator_organisation.py, akvo/rsr/models/project.py, akvo/rsr/permissions.py, akvo/rsr/tests/base.py, akvo/rsr/tests/test_permissions.py, akvo/rsr/views/my_rsr.py, akvo/settings/30-rsr.conf, akvo/utils.py
This PR adds the new concept of a collaborator organisation. It builds on top of the concept of shadow organisations, which are content owned organisations that are clones of other organisations in RSR. Collaborator organisations are shadow organisations whose content owner and the original organisation are the same organisation. They are shadows for the content owner organisation that are managed by the content owner themselves. 
This PR restricts access to projects, that are part of project hierarchies that have `enable_restrictions` set to True, to employees of the owner organisation of the project hierarchy and it's collaborator organisation. 
The PR acknowledges the fact that the concept of `ProjectHierarchy` and access to partners are being tightly coupled, here. We need the concept …
=> Restrict project access to users employed by hierarchy owner and it's collaborator org

akvo/rest/views/user_management.py, akvo/rsr/forms.py, akvo/rsr/tests/views/test_account.py, akvo/rsr/views/account.py
Django by default only allows activated users to request for a new password
using the forgot password link. But, new users often ignore activation links in
the register or invite activation email. The forgot password workflow doesn't
work, without that, and leaves the users confused.
This PR over-rides the default rules for password reset to allow new users 
(those who haven't logged in, even once) to reset their password using the
password reset workflow.
Closes #3540
=> Allow new users reset passwords using forgot password link

akvo/rsr/front-end/scripts-src/classic/jsx/project-editor.jsx, akvo/rsr/views/my_rsr.py, akvo/templates/myrsr/project_editor/project_editor_dropdown_options.html, akvo/templates/myrsr/project_editor/related_objects/location_administrative_input.html
Currently, only the A4 vocabulary is modified, but we can change this to modify
others, when another organisation requests for this.
Also, moved administrative vocabulary field before administrative code
=> [#3459] Allow org based ISO codes for location administratives

akvo/rsr/front-end/scripts-src/my-results/components/App.jsx, akvo/rsr/front-end/scripts-src/my-results/reducers/modelsReducer.js
Reports, Narrative reports and categories for a project needn't be fetched in
the public results view of a project. The API end-point for the results of a
project was changed and it broke the fetching of results for a user who is not
signed in. This caused the results page to not load. This commit removes the API
calls for these models in the public results view, and loads the page as soon as
the required results data has been fetched.
=> [#3591] Don't fetch unnecessary models for public results tab view

scripts/docker/dev/50-docker-local-dev.conf, scripts/docker/dev/nginx-default.conf
Nginx to set HOST headers and changing RSR domain from "localhost:8000" to "localhost"
Opening the port 8000 in docker does not work because CORS issues.
Fixes #3595
=> REST calls failing in local dev env

akvo/rest/views/related_project.py, akvo/rsr/front-end/scripts-src/classic/jsx/project-editor.jsx, akvo/rsr/models/related_project.py, akvo/rsr/tests/iati_checks/test_iati_checks.py, akvo/rsr/tests/iati_export/test_iati_export.py, akvo/rsr/tests/models/test_indicator.py, akvo/rsr/tests/rest/test_project_editor.py, akvo/rsr/tests/results_framework/test_results_framework.py
Also disallow adding multiple parents to a project. Current projects with multiple parents are not impacted by this change.
=> Disallow changing parents after results have been imported

akvo/rest/views/project_editor_utils.py, akvo/rsr/tests/rest/test_project_editor.py
When creating a bunch of new indicators/results, the ordering of the indicators
and results is random and not the same as in which they were entered. This
commit fixes the ordering by sorting the fields based on the IDs of the fields,
along with the level of the model in the Results framework hierarchy.
Closes #3586
=> [#3586] Use key part ids to sort fields along with level

akvo/rest/views/report.py, akvo/rsr/tests/base.py, akvo/rsr/tests/rest/test_project_reports.py
Ensure organisation report are not included when fetching for
project reports.
Fixes #3603
=> [#3603] Don't include organisation report in project reports

akvo/rsr/front-end/scripts-src/classic/jsx/project-editor.jsx
The code that is setting up the change handlers, and creating the dynamic
dropdowns, and switching between them is called each time a new partial is
added. This causes an existing selection in a dropdown to be removed.
This commit fixes that by ensuring that the dynamic dropdown is not setup
multiple times, if it has already been setup.
Closes #3612
- Choose a project where EUTF is the reporting organisation
- Ensure that EUTF organisation has codelist data (can be copied from live or test, if not already present in local DB).
- Try to add a couple of administrative locations ![peekN6IF2Z](https://user-images.githubusercontent.com/315678/58571301-fd362e80-8228-11e9-85d4-261d36529486.gif)
=> [#3612] Setup handlers on dynamic vocabulary dropdowns only once

akvo/rsr/tests/__init__.py, akvo/rsr/tests/iati_import/test_iati_import.py, akvo/rsr/tests/models/test_organisation.py, akvo/rsr/tests/rest/test_administrative_location.py, akvo/rsr/tests/rest/test_project.py, akvo/rsr/tests/rest/test_project_editor.py, akvo/rsr/tests/rsr_utils/test_utils.py, akvo/rsr/tests/test_templatetags.py, scripts/docker/ci/build.sh
I used `--parallel` and `--reverse` to run tests in different order than they get run usually. This popped up a few problems in tests and this PR fixes them. 
I've also switched to running the tests in parallel in CI. This saves about a couple of minutes.
=> Fix flaky tests and run tests in parallel in CI

scripts/docker/prod/start-django.sh
Change GUNICORN_DEBUG_ARGS position to end of command as that allows to
overwrite any previous config parameter
Fixes #3628
=> Allow to overwrite any Gunicorn params

akvo/templates/myrsr/project_editor/partials/iati_prefix.html
The IATI prefix and suffix fields were causing the project editor to think that
the project has unsaved data. This commit marks them as masquerade-fields.
Closes #3624
- Change the IATI prefix on an EUTF project
- Save the project and reload the project
- The project page should not show an alert about unsaved data
=> [#3624] Prevent showing incorrect unsaved project dialogs

akvo/templates/myrsr/project_editor/partials/iati_prefix.html
Currently, only EUTF is using this feature and they want the IATI suffix field
to be readonly. They want the field to be readonly, even before a parent has
been added to the project to mark it as a part of the hierarchy. This commit
sets the field to be read-only always. We can find a better way of making this
work for EUTF, if another partner wants to use this feature.
=> [#3620] Always make the IATI suffix field read only

akvo/rest/serializers/indicator.py, akvo/rsr/tests/rest/test_indicator.py
POSTs to `/rest/v1/indicator_framework/` would fail when the `periods` and
`dimension_names` fields are present, even if they are empty. This commit
makes the fields read_only, so that the write works even if the fields are
present, but empty.
=> [#3653] Make dimension_names and periods fields read_only

akvo/rest/serializers/indicator.py, akvo/rsr/tests/rest/test_indicator.py
=> [#3684] Allow dimension_names to be empty when PATCHing indicator

akvo/rsr/models/project.py, akvo/rsr/models/result/indicator.py, akvo/rsr/tests/results_framework/test_results_framework.py
Creating a new indicator disaggregation category and labels, and adding the
category to an indicator should create the corresponding category and labels
at the child level. The previous code only created the category, in case it
wasn't already created, and didn't really bother about the labels.
Closes #3720
=> [#3720] New disaggregation category on indicator should propagate

akvo/rsr/models/project.py, akvo/rsr/models/result/indicator_dimension.py, akvo/rsr/models/result/result.py, akvo/rsr/tests/results_framework/test_results_framework.py, akvo/templates/myrsr/project_editor/section_5.html
Also, remove the option to re-import in a child project that has already imported.
=> Create new disaggregation groups and results in child projects automatically

akvo/rsr/eutf_signals.py, akvo/rsr/tests/test_eutf_signals.py
For EUTF project, we automatically set the reporting partner to EUTF when a
project becomes a part of the EUTF hierarchy. In some cases, this causes the
user who created the project to lose access to the project they have
created. To fix this, this commit changes the existing reporting
organisation to an implementing partner, when setting EUTF as the reproting
organisation.
Closes #3759
=> [#3759] Switch existing reporting partner to implementing partner

akvo/rsr/permissions.py, akvo/rsr/tests/test_permissions.py
Users should be able to access projects of explicitly content owned
organisations, when they are employed by the content owner.
Closes #3765
=> [#3765] Fix permissions for explicitly content owned org projects

docker-compose.yaml
If you work on multiple projects it's a bit tedious to have this container to always start.
=> Don't start rsrdbhost by default

akvo/rest/views/organisation.py, akvo/rsr/tests/rest/test_project_editor.py
When latitude and longitude data is present in the POST data sent to
`/v1/organisation`, the co-ordinates are used to create a location for the
newly created organisation.
Closes #3787
=> [#3787] Support nested location creation in OrganisationViewSet

ci/k8s/deployment.yml, ci/training-envs/delete-env.sh, ci/training-envs/new-env.sh, ci/training-envs/templates/deployment.yaml, ci/training-envs/templates/seedDatabase.yaml, ci/training-envs/values.yaml, nginx/default.conf
Added ReportServer to the RSR pod.
We always copy the RS production DB, even when starting from an empty RSR DB, as we want to have reports in the training env.
It is possible that RS does not work in an empty RSR due to the DB tables not existing when the RSR readonly user is created. Not checking this until somebody actually bothers to use an empty RSR.
=> Support for ReportServer in training envs

akvo/rsr/admin.py, akvo/templates/admin/rsr/projecteditorvalidationset/change_form.html
The validation rules are now defined in the frontend and the partnership
team is used to editing the validations in the admin interface. This can
cause confusion, because the changed rules will not be applied in the new
PE. This commit removes the rules from the admin interface, and adds a note
about contacting the dev team to update validation sets.
Closes #3796
=> [#3796] Remove validation set rules from the admin UI

akvo/rsr/front-end/scripts-src/my-results/components/RSRUpdates.jsx, akvo/rsr/front-end/scripts-src/my-results/components/updates/UpdateForm.jsx, akvo/settings/20-default.conf, akvo/templates/results_base.html, ci/training-envs/gateway/gateway.yaml, nginx/default.conf, scripts/docker/dev/nginx-default.conf
This PR sets a limit of 10MB on the max request size for nginx. This will ensure that no files/images > 10MB can be uploaded. 
The checks for the project update attachment are updated to allow 10MB photos to be uploaded. 
We also add a front-end check for Indicator updates to prevent updates of files larger than the limit, since the front-end doesn't use the server response to show a meaningful error.
=> Allow uploading images of upto 10MB as attachments

Dockerfile, Dockerfile-dev, akvo/rsr/feeds.py, akvo/rsr/tests/base.py, akvo/rsr/tests/test_feeds.py, scripts/docker/dev/run-as-user.sh
This will update the OS from Ubuntu 12.04 to Debian Stretch, and also updates the Python from 2.7.3 to 2.7.16.
This should make it easier for the developers to install latest packages and to be able to use newer tools in their dev environment (and in production). 
- Merge this PR into develop and let developers use this for a couple of weeks
- Keep an eye on Stack driver errors on test
- Release this with the next release post that.
=> Upgrade container to use latest Python 2.7 image

akvo/rsr/models/project.py, akvo/rsr/tests/results_framework/test_results_framework.py
When the project's relation to its parent is defined on the project that is
being deleted, the `RelatedProject` object is prevented from being deleted,
because we prevent changing project relations after importing results into a
project. So, this commit overrides the `Project.delete` method to delete all
the results on the project, before trying to delete it.
Closes #3822
=> [#3822] Allow deleting projects that have imported results

akvo/rsr/models/sector.py, akvo/rsr/tests/rest/test_my_projects.py
The iati_sector_unicode string actually tries to return an ascii string and
causes problems when a sector code has unicode text. This was caught while
working with the /rest/v1/my_projects API end-point, and this commit fixes
the problem with that end-point.
=> [#3813] Fix iati_*_unicode methods to actually return unicode

akvo/rsr/management/commands/reverse_geocode_city_names.py
Closes #3774
- I've run this locally to verify that it works for a few hundred locations, but when I say works - we get back some city names for some lat/lng values. 
- How do we verify that what we are back-filling is actually correct data? 
- What happens if some of the data that we back-filled is actually incorrect? How does this effect the partners? Since we can't really identify incorrect data, as of now, rolling back these incorrect back-fills can only happen on a case-by-case by the partners.
=> [#3774] Add command to reverse geocode lat,lng to city names

akvo/rest/viewsets.py, akvo/rsr/tests/rest/test_crs_add.py, akvo/utils.py
The logging code for POST methods incorrectly assumed that all the models
have an `id` field. The `CrsAdd` model doesn't have an `id` field, and we
to fix this we should instead use the `pk` attribute.
Closes #3831
=> [#3831] Fix broken POST to /rest/v1/crs_add

akvo/rsr/management/commands/hubspot_user_list.py
We manage users in hubspot and sometimes want to mark users as inactive
based on their responses to the hubspot emails. Also, we want to
periodically update the list of users we are sending emails to from hubspot.
Closes #3888
=> [#3888] Add command to export user list and mark users as inactive

akvo/rsr/m49.py
Instead of a unicode whitespace character, which was broken during the
Python3 update, we switch to using a simple space.
=> [#2208] Use simple spaces characters for country filter

akvo/rest/views/project.py, akvo/rsr/tests/rest/test_project.py
=> [#3934] GeoJSON specifies co-ordinates to be [lng,lat] not [lat,lng]

akvo/cache.py, akvo/rest/views/project.py, akvo/rest/views/utils.py, akvo/rsr/models/model_querysets/project.py, akvo/rsr/models/organisation.py, akvo/rsr/permissions.py, akvo/rsr/tests/model_querysets/project.py, akvo/rsr/tests/models/test_organisation.py, akvo/rsr/tests/test_project_access.py
The primary goal of this PR is to speed up the `/my_projects/` end-point for non-admin users in organisations with a bunch of content-owned organisations, etc, or more specifically users from EUTF. 
While working on this, I found a couple of bugs around the content owned organisations that are fixed in this PR.  The bugs and their fixes are described below. 
When looking for content owned organisations, in soem cases, additional organisations were being returned as content owned organisations. This is because of incorrectly used chained filter methods on a queryset. 90e5b25a82ee5d143663656792f3084d447ff3a8 fixes this by making the filter query take multiple arguments, instead of chaining filter methods with the two different arguments. 
The `content_owned_by` method on organisations was …
=> Speed up the my_projects end-point for non-admin users

akvo/rsr/tests/up/test_up.py, akvo/rsr/views/account.py
This PR fixes a bug in the `/auth/token` response (the end-point used by the Up app, to get list of user accessible projects). The API response included all the projects where the user had an employment - approved or otherwise. The last commit in this PR changes that to include only approved employments. 
The two commits before that are clean-up commits to improve the tests, leading up to this change.
=> In /auth/token response include only projects of approved employment organisations

akvo/rsr/tests/models/test_partner_site.py, akvo/rsr/views/my_rsr.py, akvo/urls.py
The first couple of commits are just improvements to the tests.  The last commit adds a `/css` view that redirects to the custom CSS URL for a partner site.
=> Add /css URL that redirects to partner site custom css

akvo/rsr/tests/base.py, akvo/rsr/tests/up/test_up.py, akvo/rsr/views/account.py
Use the `User.my_projects` method to return the correct list of project IDs
accessible to a user after the sign in using the app, and obtain the auth
token.
This list is only refreshed when the user logs in, and the FAC could
potentially cause issues for users who have the list of projects cached in
their apps. But, I'm not sure there's a way to resolve it from the server
side, without making any app code changes. May be invalidating the tokens
for users might work, but it could break things for non-Up app users
unexpectedly. Not sure if the app itself handles expired tokens correctly.
=> Ensure only user accessible projects are listed in Up app

akvo/rest/views/utils.py, akvo/rsr/tests/rest/test_user_management.py
When adding a new employment for a user, we look for the user based on the
email ID entered in the invitation dialog. This look-up was buggy in cases
where the email ID in the DB had non-lower case letters, since an exact
match search was being performed using lower cased emails entered in the
invitation dialog. This commit makes the search case-insensitive.
Independently, I've also verified that the `register` workflow does this correctly.
Fixes  #4093
=> [#4093] Perform case-insensitive email search for existing users

akvo/rsr/tests/test_thumbnail_backend.py, akvo/settings/30-rsr.conf, akvo/thumbnail_backend.py
`sorl` generated a different thumbnail path based on the storage. For our
use case of moving the cached images to Google Storage and re-using them,
this doesn't work very well, since we regenerate thumbnails for images that
already have thumbnails. This commit fixes that by using the same paths
generated using the filesystem storage backend, for the google one as well.
Closes #4101
=> [#4101] Generate the same thumbnail path irrespective of storage

akvo/iati/exports/elements/result.py, akvo/rsr/tests/iati_export/test_iati_export.py
Baseline values and target values should not be present in the IATI export. 
Closes #4105
=> Fix IATI export for qualitative indicators 

akvo/rsr/management/commands/fix_project_hierarchy_missing_periods.py, akvo/rsr/models/project.py
We no longer allow the child periods to be added/deleted from the UI, and
some projects may have deleted child periods. This script can be used to fix
such data issues.
Closes #4108
=> [#4108] Add command to fix missing periods from a project hierarchy

Dockerfile, Dockerfile-dev, Dockerfile-prod-no-code, akvo/rsr/tests/rest/test_project_editor.py, akvo/rsr/tests/rest/test_project_overview.py, akvo/rsr/tests/rest/test_project_role.py, akvo/rsr/tests/rest/test_user_management.py, akvo/rsr/tests/test_thumbnail_backend.py, akvo/rsr/tests/views/test_account.py, akvo/rsr/tests/views/test_project.py, scripts/deployment/pip/requirements/2_rsr.txt, scripts/deployment/pip/requirements/3_testing.txt
This work is a part of trying to upgrade all the dependencies to their latest versions that can run with the current version of Django that we run. This should make our transition to a newer Django easier. We may still find some unused packages, but we can deal with them in a separate PR.
=> Remove unused requirements

ci/k8s/deployment.yml, ci/training-envs/templates/deployment.yaml, docker-compose.ci.prod.images.yaml, nginx/default.conf, nginx/start.sh
Once we start using Google Storage, Nginx will proxy any media requests from the old url to the new Google Storage ones.
This will allow us to release the Google Storage functionality before changing the existing ReportServer reports, plus it makes the move safer as the old media urls will still work.
Part of #4080
=> Nginx to forward media requests to Google Storege

akvo/cache.py, akvo/rest/cache.py, akvo/rest/views/project.py, akvo/rest/viewsets.py, akvo/rsr/management/commands/populate_project_directory_cache.py, akvo/settings/20-default.conf, scripts/docker/dev/start-django.sh, scripts/docker/prod/start-django.sh
**NOTE**: This PR needs to be merged and deployed in two stages. I can do the actual merges and deploys, if I can get a review on this. 
We need to run `python manage.py createcachetable` before we can start using the cache. (I don't know if I should add that to the deploy script itself.) The first few commits refactor some code, and configure this cache. The last couple of commits switch over the code to start using this, and add a management command to populate the cache.  
We use a DB cache so that restarts of the container itself, don't reset the cache. The cache data takes about a couple of minutes to populate now.
=> Use a DB cache for project directory entries. 

akvo/rsr/spa/app/modules/editor/main-menu.jsx, akvo/rsr/spa/app/modules/editor/section3/section3.jsx, akvo/rsr/spa/app/modules/projects/projects.jsx, akvo/rsr/spa/app/top-bar.jsx, akvo/rsr/spa/app/utils/feat-flags.js
Nuffic is still using the stop gap PAR feature, and they need to migrate
to the new FAC, which basically only requires training of the admins, at
this point, apart from running some migration scripts.
=> [#3810] Show FAC for all organisations except Nuffic

akvo/rsr/dir/app/modules/index/view.jsx
Ordering score is a rough proxy for the activity on a project, based on
number of updates and indicator updates on a project in the last 9
months.
=> [#4222] Order projects by ordering score

akvo/rest/serializers/project_update.py, akvo/rsr/spa/app/modules/updates/updates.jsx
DRF doesn't allow nested values inside a list. This commit allow sending
a single location when using `multipart/form-data` requests.
`application/json` requests can still continue to use the `locations`
field to send nested lists of locations.
=> [#4255] Allow sending location in multipart/form-data

akvo/rsr/tests/rest/test_indicator_period_data.py, akvo/settings/30-rsr.conf
=> [#4281] Set DRF serializer to not coerce decimal to string.

ci/deploy-semaphoreci.sh
To make it easier to deploy custom changes to training envs, we use a [TEMP commit](https://github.com/akvo/akvo-rsr/commit/2e6082807598d657a87bb2332fb22b2a3e330aec). This change makes it easier to push the required docker images, using a specific branch name. This change makes the process less error prone and more convenient.
=>  Push docker images to registry on rsr-env-* branches

ci/k8s/grafana/main.yml
- The Memory, CPU, Network usage was broken due to changes in the
label names
- We know use `container_memory_usage_bytes` because the
`container_memory_working_set_bytes` got deprecated in k8s 1.18
(We're using 1.16)
=> [#3552] Update Grafana dashboard

ci/training-envs/gateway/gateway.yaml, nginx/default.conf, scripts/docker/dev/nginx/default.conf
Indicator updates now allowing multiple files in a single request. This
means the request body size can easily cross 10MB, when there are
multiple files. This commit increases the limit on this size to 50MB.
=> [#4378] Increase max body size to 50MB

akvo/rest/views/project.py, akvo/rsr/tests/rest/test_project.py
This was broken in a refactoring commit here:
5d9f26a3095e3ae8465c80b0b671cc9459917994
Closes #4226
=> [#4426] Fix adding contributing project at level > 1

akvo/rsr/spa/app/utils/auto-save.jsx, akvo/rsr/spa/app/utils/misc.js
The undefined value commonly replace by null value, but it's will be problem if backend need empty string to recognize that value is really empty. Except for baselineYear that need null if user reset that value.
So, I create new function at `app/utils/misc.js` to swap object data which containing undefined values.
=> Closes #4554 Baseline values not deleting

akvo/rsr/spa/app/modules/project-view/project-view.jsx, akvo/rsr/spa/app/modules/projects/projects.jsx, akvo/rsr/spa/app/modules/projects/table-view.jsx, akvo/rsr/spa/app/modules/results/filter-checkbox.jsx, akvo/rsr/spa/app/modules/results/results.jsx, akvo/rsr/spa/app/utils/feat-flags.js, akvo/rsr/spa/app/utils/misc.js
=> Closes #4541 Nuffic Results view

akvo/rsr/management/commands/remove_project_parent.py, akvo/rsr/tests/usecases/test_remove_project_parent.py, akvo/rsr/usecases/remove_project_parent.py
This commit adds a command to delete related parents for a project, and sets
all the parents to None in the results framework hierarchy for that project.It
may be useful to make this functionality available from the UI for RSR admins.
=> [#4604] Add command to detach a project from a hierarchy

akvo/rsr/models/result/result.py, akvo/rsr/views/py_reports/eutf_org_results_table_excel_report.py, akvo/urls.py
The PR adds a couple of commits:
- Add a simple descendants method for Results. The method is a "clone" of the projects method, but simpler.
- Add a program report for EUTF that filters the existing Results & Indicators table to include only data related to the "Common Output Indicators" result. We allow for some flexibility in changing the result title or choosing the result to include in the report by making the result ID a parameter in the URL. 
See the commit messages for a more detailed description.
=> 4624 eutf common output indicators

scripts/docker/dev/start-django.sh
When running `docker-compose up` with empty postgres volume, either the
web or the reports container will be terminated due to failure to run
the migration.
=> [#4660] Do not run migration in reports container

.coveragerc, akvo/cache/__init__.py, akvo/cache/memcache.py, akvo/cache/prepo.py, akvo/cache/tests/test_prepo.py, akvo/rest/views/indicator_period_data.py, akvo/rest/views/partnership.py, akvo/rest/views/project.py, akvo/rest/views/project_update.py, akvo/rest/viewsets.py, akvo/settings/20-default.conf
The fix is two-fold:
- Store querysets closest to their final, filtered form --> rename `get_queryset` to `filter_queryset` and cache it
- Cache only the SQL query of a queryset instead of the DB result post query
More information is present in `QuerysetPrepo`.
The actual heavy part of `akvo.rest.viewsets._projects_filter_for_non_privileged_users` were the calls to `user.get_permission_filter`. They "only" modified the queryset and the actual DB query is somewhat fast. 
Fixes #4681
As a result, the UI frontend and API queries are faster.
=> [#4681] /rest/v1/project_update/ actually got slower with the cache

ci/build-semaphoreci.sh, ci/on-fail-semaphoreci.sh, docker-compose.ci.yaml, docker-compose.override.yaml, docker-compose.yaml, scripts/docker/dev/nginx/default.conf, scripts/docker/dev/nginx/includes/dir-webpack.conf
This PR gets rid of `network_mode: service:XXX` in the docker-compose YAMLs for the local env. Reasons are explained in the related issue.
In order to do so, the nginx config had to be modified to point to the specific hosts instead of `localhost`. I haven't grokked the CI setup, so the service network mode was simply moved to the CI docker-compose for it to stay as it is.
It is not clear where the service network mode was chosen due to how kubernetes works in production or because it looked that way without docker (everything runs on localhost) and that was just transferred. The PR shouldn't impact production configuration as only dev files were changed and the CI still works.
Closes #4669
=> [#4669] Replace docker service network mode

akvo/rest/urls.py, scripts/docker/ci/build.sh
Fixes deprecation warning. Check the CI.
Fixes #4671
=> Fix #4671: Deprecation(django): Replace base_name by basename in urls.py

akvo/rsr/models/focus_area.py, akvo/rsr/models/organisation.py, akvo/rsr/models/project.py, akvo/rsr/models/project_update.py, scripts/docker/ci/build.sh
https://docs.djangoproject.com/en/3.2/releases/1.11/#models-permalink-decorator
Deprecation warnings were also activated in the CI and this one doesn't show up anymore.
Fixes #4674
=> [#4674] chore(upgrade): Fix models.permalink

scripts/docker/ci/build.sh, scripts/docker/dev/50-docker-local-dev.conf
It was just missing `r'...'`
Fix #4673: Deprecation(django): invalid escape sequence \.
=> Fix #4673: Deprecation(django): invalid escape sequence \.

akvo/rest/filters.py, akvo/rest/tests/test_filters.py
=> [#4682]: Passing a malformed filter to REST endpoints silently fails and returns unfiltered results

README.dev.md, akvo/rsr/tests/models/test_custom_field.py, akvo/rsr/tests/models/test_project.py, akvo/rsr/tests/models/test_results_aggregation.py, scripts/docker/ci/build.sh
We can now use `--keepdb` for our tests which saves us the time of running migrations every time we run a test.
Migrations take about 1:20m to run right now, so that time is saved.
Fix #4668: Speed up django unit tests
```sh
$ time docker-compose run --rm web ./manage.py test --failfast --noinput akvo &>/dev/null
real    13m1.992s
user    0m1.297s
sys     0m0.869s
$ time docker-compose run --rm web ./manage.py test --failfast --noinput --keepdb akvo &>/dev/null
real    11m19.324s
user    0m1.380s
sys     0m0.777s
$ time docker-compose run --rm web ./manage.py test --failfast --noinput --keepdb akvo.codelists.tests.test_iati_codelist_generator.CodelistGeneratorTestCase.test_prevent_changing_generated_files_by_hand &>/dev/null
real    1m56.849s
user    0m1.310s
sys     0m0.763s
$ time …
```
=> [#4668]: Speed up django unit tests

scripts/docker/ci/build.sh
If future versions change the output, the `grep` won't work.
It already missed a necessary migration for some reason in another CI run (can't find it anymore).
Fix #4684
=> Fix #4684: CI: Use makemigrations --check

akvo/rsr/tests/base.py, akvo/rsr/tests/rest/test_indicator_period.py, scripts/docker/ci/build.sh
This first part just adds logs to try and find out why the test is failing. The problems ([link](https://akvo.semaphoreci.com/jobs/3c798ac4-080d-4b67-ae1c-3129bbd8bf34)) couldn't be recreated locally.
Related to #4702: CI tests are unstable... why?
=> [#4702]: CI tests are unstable... why?

docker-compose.override.yaml
I didn't want to mess around with JS code and point the hot reload in the client to another port.
It just isn't clear to me how to make that change a dev-only change.
The easiest route I therefore picked was to make it possible for the react client to access the ports
it was expecting to access
=> Fix: Make react hot reload work again locally

akvo/rest/views/project.py
The request takes way too long when the cache is broken.
On production, it never actually is able to fill the cache.
To give us time to work on a solution, this limits the number of projects in the directory from
#4725: /rest/v1/project_directory performance
=> [#4725] workaround: Ultra hacky limitation to speed up project_dir

akvo/rsr/management/commands/clear_all_sessions.py
On rsr.test.akvo.org the sessions weren't being cleared.
I'm not entirely sure why the SessionStore has to be cleared as well,
but it did the trick on that env.
=> Flush session store as well when clearing sessions

scripts/docker/dev/nginx/default.conf
Fix #4718: `nginx` container can startup locally without `reports` container
The same format is applied to all `location` blocks, now `nginx` can start even all upstreams don't exist.
=> [#4718]  nginx container won't startup locally without reports container

akvo/rest/views/project.py, akvo/rsr/tests/rest/test_my_projects.py
`Queryset.union` was throwing an exception with a query containing LIMIT.
#4743: /rest/rsr/v1/my_projects?country= fails with 500
=> [#4743] fix: my_projects endpoint filtering by country

akvo/rsr/spa/app/modules/updates/styles.scss, akvo/rsr/spa/app/modules/updates/updates-photo.js, akvo/rsr/spa/app/modules/updates/updates.jsx
Fix issue : VNG partners can't create Project Updates
It seems that a user is not able to delete an uploaded image to draft Project Update once they have upload an image. We need to change this:
=> [#4745] Project updates delete main photo

scripts/deployment/pip/requirements/2_rsr.txt, scripts/deployment/pip/requirements/3_dev.txt
Dependabot recommends urllib3>=1.26.5 (https://github.com/advisories/GHSA-q2q7-5pp4-w6pg)
`requests` had to be upgraded to allow the upgrade to be possible.
=> Upgrade urllib3>=1.26.5

akvo/rsr/spa/app/modules/projects/projects.jsx
Search projects by title doesn't work if we add extra space
1. Login to RSR
2. Search project by title
3. Add space after project title
4. RSR shows no search results after keywords have trailing spaces
https://user-images.githubusercontent.com/20871229/147434224-36306661-bb63-45d0-b050-59066a2e91fe.mov
=> [#4761] Fix: invalid space when searching project by title

.coveragerc, .gitignore, .semaphore/semaphore.yml, README.dev.md, README.md, ci/build-semaphoreci.sh, docker-compose.ci.yaml, scripts/deployment/pip/requirements/3_dev.txt, scripts/deployment/pip/requirements/dev.in, scripts/devhelpers/coverage.sh, scripts/docker/ci/build.sh
We need to know the real coverage in order to help identifying those parts of the code that still need testing.
The coverage is available on [coverage.io](https://coveralls.io/github/akvo/akvo-rsr?branch=feature/4738-get-real-coverage-in-ci) and a script was added to generate it locally.
Additionally, the script generates a report of the coverage of the diff between the current branch and `origin/master`. That'll be helpful to ensure that what you wrote is actually tested.
Close #4738
=> [#4738] chore: enable coverage on most paths

akvo/rsr/management/commands/perform_iati_checks.py, akvo/rsr/management/commands/tests/base.py, akvo/rsr/management/commands/tests/test_perform_iati_checks.py
The only options we had were checking all projects or those still to be checked.
Now we can also check all projects before, after or in between dates.
Closes #4781
=> [#4781]: Allow passing date range for perform_iati_checks

akvo/rsr/tests/results_framework/test_results_framework.py, akvo/rsr/views/py_reports/__init__.py
Closes #4771: Missing comma in `__all__` results in unexpected string concatenation
=> [#4771] A comma too many, a comma too few

akvo/rsr/fixtures/project_validations.yaml, akvo/rsr/tests/fixtures/test_project_validations.py, scripts/docker/dev/start-django.sh
The project validation fixtures have to exist so that the dev env
can use validation sets and their validations.
Without it, the frontend simply displays them, but can't use them.
- `docker-compose down -v && docker-compose up -d`
- When everything is up go to http://localhost
- Login as `local@akvo.org` / `password`
- Go to the test project project
- Open the project editor
- Click on `Settings` on the left
- Toggle a few validation sets
- Reload and open the `Settings` again
--------
Closes #4777: Not all validations sets are available in a clean environment
=> [#4777] make all validation sets available in a clean dev env

ci/build-semaphoreci.sh, ci/quote.py
Branch names can have all kinds of quotes and characters.
Since, I couldn't find a python function that does exactly what's needed (take a string and output the same string with escaped chars),  I took the next best thing and output a POSIX, escaped string.
Hopefully that should mostly be accepted by python.
If the CI for this passes, then the modifications should work as a single quote is in this branch's name.
Fix #4795
=> Fix [#4795]: Support branch names with a single quote in the CI

akvo/rsr/management/commands/a4a_optimy_import.py
Remove line that modifies the publishing status.
Could only do this locally by inserting the credentials into the configuration and running the script to make sure publishing statuses didn't change.
Closes #4808
=> [#4808]: Let a4a_optimy_import leave publishingstatus alone

akvo/rsr/management/commands/a4a_optimy_import.py
Find the default validation for projects imported by optimy and add it to the project.
Not sure. Gotta check :thinking: 
Closes #4809
=> [#4809] Set default validation set for a4a_optimy_import

akvo/rsr/signals.py, akvo/utils.py
The image field name on the model being saved is now passed as a parameter to the `save_image` function.
The signal is for multiple models and their image fields don't have the same
name as all other classes.
The old code just assumed "photo", but orgs have a "logo" field.
- As an admin open http://localhost/en/admin/rsr/organisation/add/
-  Fill in required fields
-  Add logo
- Save
Closes #4811
=> [#4811] Fix: Creating orgs with logos on google cloud

akvo/rsr/management/commands/cleanup_indicator_periods.py, akvo/rsr/tests/commands/test_cleanup_indicator_periods.py, akvo/rsr/tests/utils.py
Multiple bugs have caused our child indicator periods to be left orphaned after their parents were deleted.
This PR introduces a django command that finds and deletes them.
Orphans are identified as indicator periods:
- without a parent period
- with a parent indicator
Those that can be deleted are those **without** indicator data.
-----------------------
Closes #4833: Task: Clean up orphaned indicator periods
=> [#4833] Clean up orphaned indicator periods

akvo/rsr/spa/app/components/ResultType.jsx, akvo/rsr/spa/app/components/StatusIndicator.jsx, akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx, akvo/rsr/spa/app/modules/results-admin/TobeReported.jsx, akvo/rsr/spa/app/modules/results-overview/ResultOverview.jsx, akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx
=> [#4802] Adding the 'Result type' and the corresponding title

akvo/rsr/models/location.py
This is temporary and should be removed once #4849 is fixed or the cause has been found
example
```
WARNING 2022-02-15 14:35:10,710 location About to delete ProjectLocation(4) Latitude: No latitude specified, Longitude: No longitude specified, Country: No country specified of project(28) Test Project
Stack (most recent call last):
File "/opt/.pycharm_helpers/pycharm/django_test_manage.py", line 168, in <module>
utility.execute()
File "/opt/.pycharm_helpers/pycharm/django_test_manage.py", line 142, in execute
_create_command().run_from_argv(self.argv)
File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/test.py", line 23, in run_from_argv
super().run_from_argv(argv)
File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in …
```
=> [#4849] Log when Project location is being deleted from a project

akvo/rsr/spa/app/modules/results-overview/ResultOverview.jsx, akvo/rsr/spa/app/modules/results-overview/ResultOverview.scss, akvo/rsr/spa/app/modules/results-overview/components/Indicator.jsx, akvo/rsr/spa/app/utils/target-charts.jsx
by Ouma
https://xd.adobe.com/view/8b187c71-6cb6-4300-b4b3-ef46e4b9b667-de4b/screen/c8559c33-368a-4e42-a3e2-ec448ce60167/
=> [#4828] Fix Misplaced chart visual in the 'Description' section

scripts/data/make-and-restore-production-dump.sh, scripts/data/restore-from-dump.sh
This allows us to import dumps with privileged queries (e.g `CREATE EXTENSION`) by importing as the `postgres` user.
After the import, the RSR user is granted privileges and ownership of the tables and views. Without it, it's not possible to CRUD the tables/views.
Part 2 will be fixing training environments in order to import using the `postgres` user
This happens normally when starting up the DB service.
We ensure this way that migrations are run and RSR works normally.
We can manually import a dump like so
```sh
echo "CREATE EXTENSION IF NOT EXISTS ltree" | gzip - > scripts/data/dumps/test.gz
docker-compose exec \
rsrdbhost /data-scripts/restore-from-dump.sh \
/var/run/postgresql \
rsrdb \
rsruserdb \
/data-scripts/dumps/test.gz
```
----------
Related to #4856: Bug: Restoring DB dump …
=> [#4856] part1: fix: restore DB dump in dev env as postgres user

ci/training-envs/templates/seedDatabase.yaml
Updated the `seed-db.sh` script in the `ConfigMap` to use `postgres` to load the dumped DB. It was copy-pasted and adapted from #4864.
The only way to test this was live. RSR1 was deploying using this branch and is working.
One can verify that the right script was used by looking at the configmap of the script in kubernetes
```
docker run --rm -it -w /data -v `pwd`:/data kiwigrid/gcloud-kubectl-helm:2.12.3-234.0.0-88 bash
gcloud auth login
kubectl describe configmap rsr1-postgresql-seed-db --namespace=rsr-demo
```
--------------
Closes #4856: Bug: Restoring DB dump with ltree extension doesn't work
=> [#4856] part 2: fix: restore DB dump in training env as postgres user

akvo/rest/authentication.py, akvo/rest/models.py, akvo/rest/views/indicator_period.py, akvo/rest/views/indicator_period_data.py, akvo/rest/views/program_results_geo.py, akvo/rest/views/project.py, akvo/rest/views/project_editor.py, akvo/rest/views/project_enumerators.py, akvo/rest/views/project_overview.py, akvo/rest/views/project_update.py, akvo/rest/views/result.py, akvo/rest/views/user.py, akvo/rest/viewsets.py, akvo/rsr/models/__init__.py, akvo/rsr/tests/rest/test_authentication.py
- Open a project with enumerators (or create one yourself) --> http://localhost/my-rsr/projects/123/enumerators
- Copy a form access link 
- Open the link in a private browser windows/tab
It should open and it should be possible to modify results.
=> [#4872] fix opening project results using copied form access link

ci/training-envs/templates/seedDatabase.yaml, scripts/data/restore-from-dump.sh
There was no write-access to the sequences, so new objects couldn't be inserted
as the sequences couldn't be updated.
Apparently `GRANT ALL ON schema public` doesn't mean what we think it means...
=> [#4874] Fix: Database imported from production with superuser is read-only

ci/k8s/config-prod.yml, ci/k8s/config-test.yml
Sigh... why allow booleans in the first place if they can't be used at all?
Unfortunately, the proof is in the pudding and we have to wait for the CI to run...
=> [#4880] Use string instead of boolean in configmap

akvo/rsr/spa/app/components/AddUpdate.jsx, akvo/rsr/spa/app/components/ProgressBar.jsx, akvo/rsr/spa/app/modules/results-admin/components/ReportedForm.jsx, akvo/rsr/spa/app/modules/results-overview/components/UpdateItems.jsx, akvo/rsr/spa/app/modules/results/dsg-overview.jsx, akvo/rsr/spa/app/modules/results/enumerator.jsx, akvo/rsr/spa/app/modules/results/period.jsx, akvo/rsr/spa/app/modules/results/styles.scss
=> [#4827] Replace all line charts visuals and fix progressbar

akvo/rsr/spa/app/modules/editor/section7/location-items/search-item.jsx
=> [#4892] Fix bug:Unable to select a city when adding a new organization

akvo/rest/serializers/project.py, akvo/rsr/spa/app/modules/hierarchy/card.jsx, akvo/rsr/spa/app/modules/hierarchy/hierarchy.jsx, akvo/rsr/spa/app/modules/project-view/project-view.jsx, akvo/rsr/spa/app/modules/projects/conditional-link.jsx, akvo/rsr/spa/app/modules/projects/table-view.jsx, akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx, akvo/rsr/spa/app/modules/results/router.jsx, akvo/rsr/tests/rest/test_my_projects.py
=> [#4917] Set redirect old version for nuffic both organization and user

akvo/rsr/spa/app/modules/project-view/project-view.jsx
=> [#4917] Fix the old version redirection for akvo user

.github/PULL_REQUEST_TEMPLATE.md
Unfortunately, it's not supported by PR templates but by issue templates 🙄
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository
=> Remove YAML front matter from Pull request template

akvo/iati/exports/iati_export.py, akvo/iati/exports/iati_org_export.py, akvo/iati/exports/utils.py, akvo/rsr/tests/iati_export/__init__.py, akvo/rsr/tests/iati_export/test_iati_export.py, akvo/rsr/tests/iati_export/test_iati_org_export.py, akvo/settings/20-default.conf
The datetime stored in the DB was not aware of timezones and thus used the time on the server.
The last-updated-datetime attribute is an xsd:dateTime which can have a timezone component.
However, because the datetime instance is timezone naive and we use a manually formatted string,
we exported the wrong time.
We now indicate to django that it should store timezone aware dates in the DB.
Additionally, old "last_modified_at" dates will be converted to timezone aware dates when exporting.
And of course the `xsd:dateTime` is properly exported using `datetime.isoformat()`
Closes #4947
=> [#4947] IATI export datetime using correct format

akvo/rest/urls.py, akvo/rest/views/__init__.py, akvo/rest/views/sector.py, akvo/rest/views/tests/test_sector.py
This endpoint was split out from the `project_directory` endpoint.
It should reduce the amount of data loaded by the frontend to produce the map on the homepage.
The assumption was that the `/sectors` endpoint would provide 
Closes #4952
=> [#4952] Provide sector code list endpoint

akvo/settings/90-finish.conf
Remove iati_import cronjob
It doesn't handle the timezone properly and compares a timezone aware with a timezone naive date.
Dates in django are now timezone aware due to 1f98d87a195e1d4f9b512bf40467862b9af6357c
=> [#4975] Remove iati_import cronjob

akvo/rsr/dir/app/images/home-monitoring.svg, akvo/rsr/dir/app/styles/app.scss, akvo/rsr/dir/app/styles/home-page.scss
=> [#4764] Fix the first illustration not mirrored on safari

akvo/rsr/management/commands/remote_netherlands_foreign_ministry.py
The duplicate has many partnerships which are replaced by partnerships with the original org.
- Run script with `--dry-run`
- Navigate to a project's partnerships
- Check it has a partnership with the duplicate
- Run script **without** params
- Reload project partnership page
- Verify that partnership shows old org
Example result
http://localhost/my-rsr/projects/6927/partners
Closes #4978
=> [#4978] Remove Dutch foreign ministry org

akvo/rsr/spa/app/modules/hierarchy/hierarchy.jsx, akvo/rsr/spa/app/modules/project-view/project-view.jsx, akvo/rsr/spa/app/modules/projects/conditional-link.jsx, akvo/rsr/spa/app/modules/projects/table-view.jsx, akvo/rsr/spa/app/modules/results-admin/PendingApproval.jsx, akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx
=> [#4992] Fix old Results UI still there for Nuffic

akvo/rsr/spa/app/modules/announcements/27-05-2022.jsx, akvo/rsr/spa/app/modules/announcements/list.js
=> [#4242] Change released date from 17 to 27 May 2022

akvo/rsr/spa/app/modules/project-view/project-view.jsx, akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx
- Login as Enumerator
- Go to any project, eg : [http://localhost/my-rsr/projects/9604/results](http://localhost/my-rsr/projects/9604/results)
- Submit any update
- Login as MnE with other browser
- Review the last update of the enumerator and reject it.
- Open link from email
- Field input should be editable.
=> [#5000] Fix no active field on revised update for enumerator form link

akvo/rsr/models/project.py, akvo/rsr/tests/models/test_project.py
The `update_thumbnails` save signal was being called during project deletion.
That was triggered by related objects updating the project in their own delete signal.
It doesn't make sense to allow saving a project while it's being deleted,
so the method simply returns in that case
------------
Fixes #5004
=> #5004: Fix: Disallow saving a project during deletion

akvo/rsr/spa/app/modules/project-view/project-view.jsx, akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx, akvo/rsr/spa/app/utils/feat-flags.js
=> [#5010] Fix enumerators tab not available for admin role

akvo/rest/serializers/indicator.py, akvo/rest/serializers/indicator_period.py, akvo/rest/serializers/indicator_period_data.py, akvo/rest/serializers/result.py, akvo/rest/views/result.py
Prefetch as much data as possible.
`IndicatorPeriodFrameworkNoToLiteSerializer.get_updates` wasn't taking advantage of the prefetched data.
Now, it filters in python without making an extra query.
It's still suboptimal, but at least it's a bit faster.
----------------
Closes #5017
=> [#5017] Speed up Results framework endpoint

akvo/rest/serializers/rsr_serializer.py, akvo/rsr/models/focus_area.py, akvo/rsr/models/organisation.py, akvo/rsr/models/project.py, akvo/rsr/models/project_update.py, akvo/rsr/models/user.py
get_absolute_url uses `reverse()` which is filthy slow. Repeated calls to it slow down the application immensely.
We can cache that using `cached_property`, but optimally, we shouldn't be using such a method at all.
This is a quickfix to get use out of hot water. Hopefully, we can eradicate that method sometime...
-----------
Closes #5022
=> [#5022] Replace get_absolute_url with cacheable_url and cached_proprty in serializers and models

akvo/rsr/spa/app/modules/announcements/HelpLinks.jsx, akvo/rsr/spa/app/modules/announcements/announcement.jsx
=> [#4991] Reorder the links with the New features appearing at the bottom

akvo/rsr/models/__init__.py, akvo/rsr/project_role_auth.py, akvo/rsr/tests/rest/test_permissions.py, akvo/rsr/tests/rest/test_project_update.py, akvo/rsr/tests/test_permissions.py
Anybody able to view the update was able to edit it.
That was changed by limiting the operation to the owners and
introducing the "rsr.view_projectupdate" permission.
- Add 2 enumerators to a project
- Login with one enumerator in the browser window
- Login with second enumerator in private browser window
- Create updates with each enumerator
Expect to see the owned updates be editable and deletable, and the foreign updates to only be viewable.
Fixes #5038
=> [#5038] Fix enumerators can edit project updates they do not own

akvo/rsr/dir/app/modules/project-page/views/UpdatePage.jsx
> there is a slash in front which causes the url to be invalid
=> [#5020] Fix broken image at detail project update

akvo/rsr/views/project.py, akvo/rsr/views/project_update.py
- Go to http://localhost/en/project/2602/
- It should be redirected to http://localhost/dir/project/2602
- Go to http://localhost/en/project/2602/update/23786/
- It should be redirected to http://localhost/dir/project/2602/update?id=23786
---
Closes #5065
=> [#5065] Redirect old public pages to new version

ci/k8s/deployment.yml
RSR has just become quite CPU intensive and requires more memory than before.
As a workaround before optimizing performance and memory, the pod will:
- tolerate a mode with the taint akvo-app=rsr
- have an affinity for nodes with the label akvo-app=rsr
Can't really test this without running it. Only a dry run can check the syntax.
Related to #5062
=> devops: place rsr on its own node

akvo/rsr/spa/app/modules/editor/project-init-handler.js
=> [#5073] Fix editor long delays before loading

akvo/iati/imports/__init__.py, akvo/rsr/management/commands/cleanup_untitled_and_unpublished_projects.py, akvo/rsr/management/commands/delete_empty_projects.py, akvo/rsr/management/commands/expire_all_sessions.py, akvo/rsr/migrations/0047_auto_20160115_1039.py, akvo/rsr/migrations/0219_project_naive_created_at.py, akvo/rsr/migrations/0220_project_naive_created_at.py, akvo/rsr/models/iati_activity_import.py, akvo/rsr/models/iati_import.py, akvo/rsr/models/iati_import_job.py, akvo/rsr/models/project.py, akvo/rsr/signals.py, akvo/rsr/tests/base.py, akvo/rsr/views/py_reports/eutf_org_results_table_excel_report.py, akvo/rsr/views/py_reports/organisation_data_quality_overview_report.py, akvo/rsr/views/py_reports/organisation_projects_overview_report.py, akvo/rsr/views/py_reports/results_indicators_excel_report.py, akvo/utils/__init__.py, akvo/utils/datetime.py
Reduce the number of useless logs and warnings
Fixes #5061
=> [#5061] fix project.created at is naive datetime when saving a project

akvo/rsr/spa/app/modules/editor/project-init-handler.js
- Make sure you are logged in.
- Open this URL in your browser : https://rsr.akvotest.org/my-rsr/projects/6003/info
- It should contain General information data from the backend.
- Login with your account.
- Go to any project.
- Move to project editor.
- It should contain General information data from the backend.
- Login with your account.
- Let's try with the following projects : 
1. [OmiDelta Fonds Acteurs Non Etatiques pour la composante AEPHA](https://rsr.akvotest.org/my-rsr/projects/6024/results)
2. [ANAP](https://rsr.akvotest.org/my-rsr/projects/7021/results).
3. [Roblox …
=> Fix bug project editor sections are loaded only once

akvo/iati/exports/iati_export.py, akvo/iati/exports/iati_org_export.py, akvo/rsr/management/commands/perform_iati_checks.py, akvo/rsr/tests/usecases/test_run_iati_validation_jobs.py, akvo/rsr/usecases/iati_validation/__init__.py, akvo/rsr/usecases/iati_validation/iati_validation_job_runner.py, akvo/rsr/usecases/iati_validation/run_validation_jobs.py, akvo/rsr/usecases/iati_validation/schedule_validation.py
- Modify a few existing projects
- Ensure that their `run_iati_checks` is `True`
- Run `./manage.py perform_iati_checks` and ensure that there are no projects with `run_iati_check = True`
Closes [#5096
=> [#5096] iati export does not update checks after project is updated

ci/training-envs/Dockerfile, ci/training-envs/README.md, ci/training-envs/docker-compose.yml, scripts/data/make-and-restore-production-dump.sh
We weren't able to login using the gcloud SDK anymore  because it was too old.
Using docker-compose and Dockerfile, we now make it possible to target a specific version of gcloud.
=> Update tools for training env deployment

akvo/rsr/spa/app/modules/editor/project-init-handler.js, akvo/rsr/spa/app/modules/editor/section5/section5.jsx
Once a new child project is created, do the following steps : 
1. Move to section 5 (results n indicators) * make sure we have 3 options.
2. Move to any section (still in the project editor).
3. Go to the Hierarchy tab
4. Go to another project.
5. Go to the Hierarchy tab
6. Go back to the previous project (a new child project).
7. Move to section 5 
8. The result framework should have been imported automatically.
=> [#5114] Fix import results set option not available in the editor

ci/training-envs/templates/deployment.yaml, ci/training-envs/values.yaml
These nodes are reserved for RSR and should only host it. They are more powerful and are the same VM type as production.
=> Prefer deploying RSR training envs on specific nodes

akvo/rsr/dir/app/modules/index/view.jsx, akvo/rsr/dir/app/modules/project-page/ProjectPage.jsx, akvo/rsr/dir/app/root.jsx, akvo/rsr/dir/app/utils/misc.js, akvo/rsr/views/__init__.py, akvo/urls.py
=> [#5167] Handle password-protected partner sites

ci/deploy-semaphoreci.sh, ci/promote-test-to-prod.sh, doc/deploying.md
This used to be production as there was a big feature being developed on master. Now that it's merged, master can continue to be deployed as usual.
Closes #5202
=> [#5202]: Deploy master to production by default

akvo/rest/views/indicator_period_aggregation_job.py, akvo/rsr/management/commands/recalculate_project_aggregation.py, akvo/rsr/models/result/disaggregation.py, akvo/rsr/models/result/indicator_period_data.py, akvo/rsr/tests/rest/jobs/test_indicator_period_aggregation.py, akvo/rsr/tests/results_framework/test_cumulative_updates.py, akvo/rsr/tests/usecases/jobs/test_aggregation.py, akvo/rsr/usecases/jobs/aggregation.py
=> [#5212] Fix reports period.actual_value for cumulative indicators

ci/k8s/deployment.yml, scripts/docker/dev/start-django.sh, scripts/docker/prod/start-django.sh
=> Fix Feature/4680 readiness and liveliness probe for k8s

akvo/rest/serializers/project.py, akvo/rest/views/project.py, akvo/rsr/spa/app/modules/hierarchy/services.js, akvo/rsr/tests/rest/test_project_hierarchy.py
This was slow because we made a query for each project. Now we get the children and grand children.
A simple dict with each project and a list of their children is then built in python.
**Side effect**
Paging doesn't work anymore as the queryset includes grand children. Reimplementing it can be done another time if we really do have projects with enormous hierarchies.
We already know who the parent is since we're getting its children --> no need to make another query.
We weren't retrieving related objects, which we now do. Additionally, we iterated over the list of countries twice when one iteration was enough.
After testing …
=> [#5199] Optimize /project/children endpoint

akvo/rsr/spa/app/modules/hierarchy/hierarchy.jsx, akvo/rsr/spa/app/modules/hierarchy/services.js
- Login as MnE manager
- Switch `only show standalone projects below` as true
- Go to any standalone project
- Move to project hierarchy
=> [#5230] Fix bug standalone project hierarchy

akvo/rsr/spa/app/components/ProgressBar.jsx, akvo/rsr/spa/app/components/ProgressBar.scss, akvo/rsr/spa/app/modules/results-admin/components/ReportedForm.jsx, akvo/rsr/spa/app/modules/results-overview/components/UpdateItems.jsx, akvo/rsr/spa/app/modules/results/dsg-overview.jsx, akvo/rsr/spa/app/modules/results/dsg-overview.scss, akvo/rsr/spa/app/modules/results/period.jsx
- Login as MnE Manager.
- Go to the project that has the cumulative indicator True.
- Open Reporting period updates: Results > Indicator > Period.
- Revalidate the actual value on the right side of update items.
=> [#5239] Fix bug cumulative indicator sum up values

akvo/settings/41-django-q.conf
We do not need it as we schedule tasks with cron and they will eventually be executed. Especially tasks that are executed every minute to not need catching up.
- Start RSR
- Wait until everything is up
- Stop the worker for a few minutes
- Start the worker
- Ensure that aggregation job is only scheduled once instead of  the number of minutes the worker was down
Related to #5248
=> [#5248] Disable catch-up for django-q

akvo/cache/heartbeat.py, akvo/rsr/tests/usecases/django_q/test_decorators.py, akvo/rsr/usecases/django_q/decorators.py, akvo/rsr/usecases/jobs/aggregation.py, akvo/settings/41-django-q.conf, akvo/settings/90-finish.conf
- Modify `execute_aggregation_jobs` to sleep for > 1 min
- Start RSR locally and wait 2-3 minutes
- Observe `worker` logs and ensure `has a valid unique task heartbeat. Skipping run...` is in the logs
Related to #5249
=> [#5249] Add decorator to make django-q tasks unique

akvo/iati/checks/fields/countries_and_regions.py, akvo/iati/checks/fields/sectors.py, akvo/rsr/spa/app/modules/editor/section8/sectors/sectors.jsx, akvo/rsr/tests/iati_checks/test_iati_checks.py, akvo/rsr/tests/iati_checks/test_iati_checks_fields_countries_and_regions.py, akvo/rsr/tests/iati_checks/test_iati_checks_fields_sectors.py, akvo/utils/__init__.py
Validate that sector code is in vocabulary code
---
Closes #5281
=> [#5281] IATI validation adjusment

akvo/rsr/tests/usecases/test_schedule_iati_validation.py, akvo/rsr/usecases/iati_validation/schedule_validation.py
Only run external validation when project is published
---
Closes #5226
=> [#5226] Fix spammy IATI validation emails

akvo/rest/views/project.py, akvo/rsr/tests/rest/test_project.py, akvo/rsr/tests/utils.py, akvo/rsr/usecases/add_project_to_program.py
- Create a new L1 contributor on a program with a large results framework
- Create a new L3 contributor
=> [#5112] Optimize add_project_to_program API endpoint
