akvo/rsr/views/account.py
=> [#3452] Add missing password length to activate_invite view

akvo/rsr/management/commands/report_d2d.py
The report has been requested enough times now to have it as a management
command. The generated report is a comparison of RSR usage between two dates -
usually a quarter or a half year apart.
=> Add script to generate the D2D report

docker-compose-docker-sync.yaml, docker-sync.yml, scripts/docker/dev/50-docker-local-dev.conf
Installation:
1. Install docker-sync: `gem install docker-sync`
2. Start docker-sync from the RSR folder: `docker-sync start`. Wait for the message: "success Starting Docker-Sync in the background". First time around it takes 5 mins in my box. 
3. Start the local env: `docker-compose -f docker-compose.yaml -f docker-compose.override.yaml -f docker-compose-docker-sync.yaml up --build`
=> [#3474] PoC for docker-sync

akvo/rsr/management/commands/fix_locations.py, akvo/rsr/models/partnership.py
=> RSR Release Hot-fix 3.40.7 Managua

akvo/rsr/templatetags/rsr_filters.py, akvo/rsr/tests/pages/test_widgets.py, akvo/templates/widgets/project_list.html
=> Fix date format string in project list widget template

akvo/rsr/forms.py, akvo/rsr/tests/views/test_account.py
=> [#3498] Fix user signup broken due to django-registration upgrade

akvo/rsr/admin.py, akvo/rsr/models/partnership.py
=> Fix broken admin pages

akvo/rsr/front-end/scripts-src/classic/jsx/project-editor.jsx, akvo/rsr/front-end/styles-src/main.css, akvo/rsr/front-end/styles-src/main.scss
=> Show list incomplete fields in each section

.dockerignore, Dockerfile, akvo/rsr/front-end/webpack.config.base.js, akvo/rsr/front-end/webpack.config.prod.js, akvo/settings/30-rsr.conf, ci/build.sh, ci/deploy.sh, docker-compose.ci.prod.images.yaml, docker-compose.ci.yaml, docker-compose.override.yaml, docker-compose.yaml, nginx/Dockerfile, nginx/start.sh, scripts/docker/ci/51-docker-ci-dev.conf, scripts/docker/ci/end-to-end.sh, scripts/docker/dev/50-docker-local-dev.conf, scripts/docker/prod/start-django.sh
=> [#3488] Webpack static assets for production

akvo/rsr/tests/test_templatetags.py, akvo/settings/30-rsr.conf
=> [#3506] Change broken settings for map markers

akvo/rsr/front-end/scripts-src/classic/jsx/project-editor.jsx
=> [#3479] Turn off displaying project editor incomplete fields

akvo/rsr/front-end/scripts-src/my-results/components/Reports.jsx
=> Renable checkbox for resutls and indicators report

akvo/rest/views/organisation.py, akvo/rsr/tests/rest/test_project_editor.py
=> Fix broken new organisation creation from the project editor

akvo/rest/views/project_editor.py, akvo/rsr/models/project.py
=> [#3422] Add indicator id to import_indicator end-point response

akvo/rsr/front-end/scripts-src/classic/jsx/directory-utils.jsx, akvo/rsr/front-end/styles-src/main.scss
=> 3250 layout issues

akvo/codelists/store/codelists_EUTF.py, akvo/rsr/management/commands/eutf_hierarchy_check.py, akvo/rsr/management/commands/eutf_shadow_organisations.py, akvo/rsr/models/project.py, akvo/rsr/views/my_rsr.py, akvo/settings/30-rsr.conf
=> Display EUTF sector codes as a dropdown

akvo/rsr/management/commands/eutf_change_employments.py, akvo/rsr/management/commands/eutf_delete_custom_fields.py, akvo/rsr/management/commands/eutf_shadow_organisations.py, akvo/settings/30-rsr.conf
=> Script to delete EUTF custom fields

akvo/templates/myrsr/project_editor/section_7.html
=> [#3525] Move Project Locations section below Recipient Countries

akvo/rsr/management/commands/fix_imported_qualitative_indicators.py, akvo/rsr/models/project.py, akvo/rsr/tests/models/test_indicator.py
=> Fix incorrectly imported qualitative indicators

akvo/rsr/models/employment.py, akvo/rsr/tests/test_project_access.py
When creating a new employment for users, restricted users should be given
access to all the projects of the new employment's organisation, except the
projects which may have already been restricted for the user.
=> [#3543] Give access to new employment organisation's projects

akvo/rsr/models/project.py, akvo/rsr/tests/results_framework/test_results_framework.py
=> [#3039] Ensure importing indicators preserves export_to_iati flag.

akvo/rest/urls.py, akvo/rest/views/__init__.py, akvo/rest/views/report.py, akvo/rsr/front-end/scripts-src/my-results/utils.js, akvo/rsr/tests/base.py, akvo/rsr/tests/rest/test_project_reports.py
=> [#3572] project report access restriction

akvo/templates/myrsr/project_editor/section_5.html
=> [#3575] Improve the UI for copying results to a project

akvo/rsr/models/project.py, akvo/rsr/models/result/indicator.py, akvo/rsr/models/result/indicator_period.py, akvo/rsr/tests/iati_export/test_iati_export.py, akvo/rsr/tests/test_project_access.py
=> [#3584] remove dead code

akvo/rsr/front-end/scripts-src/my-results/components/updates/UpdateForm.jsx
=> [#3298] Fix percentage signs (%) not displayed for disaggregations

akvo/rsr/management/commands/merge_organisations.py, akvo/rsr/tests/commands/test_merge_organisations.py
We prompt the user before merging, if the "direct" fields on the objects vary,
and the user can choose to modify them manually or ignore the differences.
There is one weird ManyToMany Relation that this script ignores. It's not clear
where this weird relation comes from!
Closes #3580
=> [#3580] Add command to merge organisations

docker-compose.yaml
Fixes #3597
See https://docs.docker.com/docker-for-mac/osxfs-caching/
=> Add "delegated" flag to mounted volume

akvo/rsr/models/__init__.py, akvo/rsr/models/user.py, akvo/rsr/permissions.py, akvo/rsr/tests/rest/test_project_update.py
=> [#3600] Allow users to delete their own project updates

akvo/templates/myrsr/project_editor/related_objects/indicator_input.html, akvo/templates/myrsr/project_editor/section_5.html
=> Fix problems with publishing a project from the project editor

akvo/rsr/front-end/scripts-src/classic/jsx/project-editor.jsx, akvo/templates/myrsr/project_editor/partials/iati_prefix.html
=> [#3607] Disable IATI suffix input for EUTF and copy subtitle value

scripts/docker/prod/start-django.sh
=> Remove fake-migration-flag

akvo/rsr/admin.py, akvo/settings/10-base.conf, scripts/deployment/pip/requirements/2_rsr.txt
=> [#3622] Allow editing OrganisationCodelist from the django admin.

akvo/rsr/models/project.py, akvo/rsr/tests/results_framework/test_results_framework.py
=> [#3618] Avoid copying and importing target values

akvo/rsr/admin.py, akvo/rsr/models/project.py, akvo/rsr/tests/results_framework/test_results_framework.py, akvo/settings/10-base.conf, akvo/templates/myrsr/project_editor/partials/iati_prefix.html, scripts/deployment/pip/requirements/2_rsr.txt
=> Hot-fix 3.43.4 Blue Manakin (cherry-picked EUTF only changes)

akvo/rest/views/project_editor.py, akvo/rsr/models/result/indicator_dimension.py, akvo/rsr/tests/results_framework/test_results_framework.py, akvo/templates/myrsr/project_editor/partials/related_object_header.html, akvo/templates/myrsr/project_editor/related_objects/dimension_name_input.html, akvo/templates/myrsr/project_editor/related_objects/dimension_value_input.html, akvo/templates/myrsr/project_editor/related_objects/indicator_dimension_name_input.html, akvo/templates/myrsr/project_editor/related_objects/indicator_input.html
=> Prevent changes in dimensions at the child projects level

akvo/rsr/tests/rest/test_project.py, akvo/settings/30-rsr.conf
=> [#3636] Add support for DD-MM-YYYY date format to the API

akvo/rest/views/project_editor.py, akvo/rsr/models/__init__.py, akvo/rsr/models/user.py, akvo/rsr/templatetags/project_editor.py, akvo/rsr/tests/base.py, akvo/rsr/tests/models/test_user.py, akvo/templates/myrsr/project_editor/section_5.html
=> Improve User.can_import_results permissions checks

akvo/rest/views/user.py, akvo/rsr/tests/rest/migration_data.py, akvo/rsr/tests/rest/test_user.py, akvo/rsr/tests/up/test_up.py
=> [#3649] Restrict access to user API endpoint.

akvo/rest/serializers/indicator.py, akvo/rest/serializers/indicator_period.py, akvo/rsr/tests/base.py, akvo/rsr/tests/rest/test_indicator.py
=> Fix 500s when using the results_framework end point

akvo/rsr/admin.py
=> [#3656] Search on project id in django admin.

akvo/rest/serializers/indicator_dimension_name.py, akvo/rest/views/indicator_dimension_name.py
=> [#3675] Add nested values to dimension_name REST endpoint.

akvo/rest/serializers/result.py, akvo/rsr/tests/rest/test_result.py
=> [#3675] Fixed results_framework endpoint POST method error.

akvo/rest/serializers/crs_add.py, akvo/rest/serializers/fss.py, akvo/rest/views/crs_add.py, akvo/rest/views/fss.py
=> Section 11 API improvements

akvo/rest/serializers/indicator_dimension_name.py, akvo/rsr/tests/rest/test_indicator_dimension.py
=> [#3675] Support creating a dimension name with nested dimension values.

akvo/rsr/management/commands/remove_project_contacts.py
=> [#3686] Add script to delete ProjectContacts given project ids

scripts/deployment/pip/requirements/2_rsr.txt
=> Update some Python dependencies

akvo/rsr/models/__init__.py, akvo/rsr/models/result/indicator_dimension.py, akvo/rsr/tests/rest/test_permissions.py, akvo/rsr/tests/test_permissions.py
=> Add permission settings for IndicatorDimensionName and IndicatorDimensionValue models

akvo/rsr/front-end/scripts-src/my-results/components/updates/UpdateForm.jsx
=> Fix broken update form for qualitative updates

akvo/rest/views/project_editor_utils.py
=> Fix broken new indicator creation with dimension names

akvo/rest/serializers/__init__.py, akvo/rest/serializers/project.py, akvo/rest/serializers/project_location.py, akvo/rest/urls.py, akvo/rest/views/__init__.py, akvo/rest/views/project.py, akvo/rsr/views/my_rsr.py
=> [#3709] Add a new end-point listing editable projects

akvo/rsr/models/project.py, akvo/rsr/tests/results_framework/test_results_framework.py
=> Allow importing results framework even if disaggregation categories are already created

akvo/rsr/models/result/indicator.py, akvo/rsr/tests/models/test_results_aggregation.py, akvo/rsr/tests/results_framework/test_results_framework.py
=> [#3713] Adding/Removing dimension names updates child indicators

akvo/rsr/views/project.py, akvo/rsr/views/project_update.py, akvo/rsr/views/utils.py
On password protected partner sites, post logging in, project and update
pages should be accessible.
=> [#3704] Private projects and updates accessible on partner sites

akvo/rsr/front-end/styles-src/main.scss, akvo/rsr/spa/app/modules/editor/section1/comp/project-photo.jsx, akvo/templates/lockdown/form.html
=> Hot-fix 3.45.1 Helmeted Hornbill 

akvo/rsr/front-end/styles-src/main.scss, akvo/rsr/models/project.py, akvo/rsr/models/result/indicator.py, akvo/rsr/tests/results_framework/test_results_framework.py, akvo/templates/lockdown/form.html
=> Hot-fix 3.45.2 Helmeted Hornbill

akvo/settings/20-default.conf
=> [#3735] Set USE_TZ to True

akvo/rsr/front-end/scripts-src/my-results/components/Reports.jsx, akvo/rsr/management/commands/period_actual_comment_cleanup.py, akvo/rsr/models/result/indicator_period.py, akvo/rsr/tests/models/test_indicator_period.py
=> [#3738] period actual comment clean-up

akvo/rest/serializers/__init__.py, akvo/rest/serializers/indicator.py, akvo/rest/serializers/indicator_period.py, akvo/rest/serializers/result.py, akvo/rest/urls.py, akvo/rest/views/__init__.py, akvo/rest/views/indicator.py, akvo/rest/views/indicator_period.py, akvo/rest/views/result.py, scripts/docker/dev/nginx-default.conf
=> Add a results_framework_lite end-point

akvo/rest/views/indicator_dimension_name.py, akvo/rest/views/indicator_dimension_value.py
Log actions performed on disaggregation categories and labels to track down bug that changes the disaggregation category unexpectedly.
Closes #3750
=> [#3750] Log disaggregation categories and labels.

akvo/rest/views/typeahead.py
=> [#3752] Show only partner site related updates in typeahead

akvo/rsr/admin.py
=> [#3755] Search project update using id and title in admin interface

akvo/rsr/admin.py
=> Display only employer related objects in the admin

akvo/templates/myrsr/project_editor/section_4.html
The sections are ordered in the order in which they are displayed in the
project page.
=> [#3767] Re-order section 4 in the old project editor

akvo/rest/viewsets.py, akvo/rsr/models/project.py, akvo/rsr/tests/rest/test_project_editor.py
=> Run IATI checks on project editor save

akvo/rsr/spa/app/modules/editor/section9/docs/validations.js
=> [#3785] Document Format is mandatory in DGIS IATI validation too

akvo/rest/serializers/project.py, akvo/rest/views/indicator_dimension_name.py, akvo/rest/views/indicator_dimension_value.py, akvo/rest/viewsets.py, akvo/rsr/tests/rest/test_project_editor.py, akvo/utils.py
=> Update the project last_modified_at time on all API calls

akvo/rest/serializers/related_project.py, akvo/rsr/tests/rest/test_related_project.py
=> [#3747] Allow adding relation to a project not in RSR using the API

akvo/rsr/spa/app/modules/editor/section1/comp/info.jsx, akvo/rsr/spa/app/modules/editor/section1/comp/project-picker.jsx, akvo/rsr/spa/app/modules/editor/section1/validations.js, akvo/rsr/spa/app/modules/editor/section5/periods/periods.jsx, akvo/rsr/spa/app/modules/editor/section6/budget-items/budget-items.jsx, akvo/rsr/spa/app/modules/editor/section7/location-items/search-item.jsx, akvo/rsr/spa/app/utils/auto-save.jsx, akvo/rsr/spa/app/utils/final-field.jsx
https://github.com/akvo/akvo-rsr/issues/3800
=> 3800 date ranges

akvo/rsr/spa/app/modules/editor/section5/section5.jsx, akvo/rsr/spa/app/modules/editor/section5/styles.scss, akvo/rsr/spa/app/utils/accordion.jsx, akvo/rsr/spa/app/utils/hooks.js
=> [#3814] s5 jump to results & indicators

akvo/rest/views/typeahead.py, akvo/rsr/tests/rest/test_typeahead.py
=> Fix AttributeError for anonymous users in user_organisations typeahead

akvo/rest/serializers/project.py, akvo/rsr/front-end/scripts-src/my-results/components/App.jsx, akvo/rsr/models/user.py, akvo/rsr/views/my_rsr.py, akvo/templates/myrsr/my_project.html
Closes #3837
Verify using an enumerator user, and check that the Editor tab is not shown in the my_project page.
=> [#3837] Don't show Editor tab in my_project for non-editor users

akvo/rsr/spa/webpack.config.js, scripts/docker/dev/50-docker-local-dev.conf
And support custom domain in development.
Fixes #3842
=> [#3842] Fix webpack dev server Invalid Host Header error.

akvo/rsr/spa/app/modules/projects/cards-view.jsx, akvo/rsr/spa/app/modules/projects/filter-country.jsx, akvo/rsr/spa/app/modules/projects/filter-sector.jsx, akvo/rsr/spa/app/modules/projects/styles.scss, akvo/rsr/spa/app/modules/projects/table-view.jsx
=> My projects updates

akvo/rsr/spa/app/root.jsx, akvo/rsr/spa/package-lock.json, akvo/rsr/spa/package.json
=> Sentry for error logging

akvo/rest/serializers/project.py
~~The serialized descendants tree for the root project is cached for a day, to
speed up the `/hierarchy/{project-id}` end-point. The cache is invalidated
when any of the projects in the hierarchy changes.~~
Optimized the code to fetch the serialized descendants of a tree. In my last attempt at doing this, I suspect that my instrumentation code as messing things up, and I jumped to the caching solution too quickly.
=> Improve the queries for fetching descendants of project hierarchy

akvo/rsr/spa/app/modules/editor/endpoints.js, akvo/rsr/spa/app/modules/editor/project-init-handler.js, akvo/rsr/spa/app/modules/editor/section11/section11.jsx, akvo/rsr/spa/app/modules/editor/section2/contacts.jsx, akvo/rsr/spa/app/modules/editor/section3/partners.jsx, akvo/rsr/spa/app/modules/editor/section5/indicators.jsx, akvo/rsr/spa/app/modules/editor/section5/section5.jsx, akvo/rsr/spa/app/modules/editor/section6/finance.jsx, akvo/rsr/spa/app/modules/editor/section7/location-items/location-items.jsx, akvo/rsr/spa/app/modules/editor/section7/location-items/validations.js, akvo/rsr/spa/app/modules/editor/section7/locations.jsx, akvo/rsr/spa/app/modules/editor/section7/recipient-countries/recipient-countries.jsx, akvo/rsr/spa/app/modules/editor/section7/recipient-regions/recipient-regions.jsx, akvo/rsr/spa/app/modules/editor/section8/focus.jsx, akvo/rsr/spa/app/modules/editor/section8/policy-markers/policy-markers.jsx, akvo/rsr/spa/app/modules/editor/section8/sectors/sectors.jsx, akvo/rsr/spa/app/modules/editor/section9/links-n-docs.jsx, akvo/rsr/spa/app/utils/min-required.jsx, akvo/rsr/spa/app/utils/misc.js
=> Hotfix issues from sentry

akvo/rsr/front-end/static/rsr/images/rsrLogo.svg, akvo/rsr/spa/app/styles/main.scss, akvo/rsr/spa/app/top-bar.jsx, akvo/rsr/views/my_rsr.py, akvo/urls.py
=> Custom partner logo

akvo/rest/serializers/project.py, akvo/rest/views/project.py, akvo/rsr/spa/app/modules/editor/section5/results/validations.js, akvo/rsr/spa/app/modules/projects/cards-view.jsx, akvo/rsr/spa/app/modules/projects/table-view.jsx
=> Hotfix 26 11

akvo/rsr/spa/app/modules/editor/section5/indicators.jsx, akvo/rsr/spa/app/modules/editor/section5/periods/periods.jsx, akvo/rsr/spa/app/modules/editor/section5/section5.jsx, akvo/rsr/spa/app/modules/editor/styles.scss, akvo/rsr/spa/app/utils/item-array.jsx, akvo/rsr/spa/app/utils/required-hint.jsx
=> [#3880] "X more to fill" in ItemArray and Accordion

akvo/rsr/spa/app/modules/editor/section5/styles.scss, akvo/rsr/spa/app/modules/editor/styles.scss, akvo/rsr/spa/app/utils/item-array.jsx, akvo/rsr/spa/app/utils/required-hint.jsx
=> [#3880] validation hint to show as red border instead of text

akvo/rest/views/organisation.py, akvo/rest/views/project.py, akvo/rest/views/project_update.py, akvo/rest/views/utils.py
Projects are assigned a score which equals the number of project updates and
indicator updates created in the last 9 months. The projects with a higher
score are displayed before the ones with a lower score.
=> Use an activity heuristic for ordering in project directory

ci/deploy.sh, ci/k8s/deployment.yml, ci/training-envs/templates/deployment.yaml
I'm not sure if this is the right way of doing things, but I created a WIP PR, so we can have a chat about this.
=> [#3876] Update k8s deployment file to create reports container

akvo/rsr/models/project.py, akvo/rsr/tests/results_framework/test_results_framework.py
=> [#3899] Indicator reordering and description update should be reflected

Dockerfile, Dockerfile-dev, akvo/rsr/staticmap.py, akvo/rsr/tests/test_staticmap.py, akvo/rsr/views/py_reports.py, akvo/settings/85-mapquest.conf, akvo/templates/reports/grids.css, akvo/templates/reports/organisation-projects-results-indicators-map-overview.html, akvo/templates/reports/project-results-indicators-map-overview.html, akvo/templates/reports/results-indicators-map-overview.css, akvo/urls.py, scripts/deployment/pip/requirements/2_rsr.txt
=> [#3876] Custom reports for EUTF Syria.

akvo/rest/views/utils.py, akvo/rsr/templatetags/maps.py, akvo/rsr/views/utils.py, scripts/deployment/pip/requirements/5_dev.txt, scripts/load-test/Readme.md, scripts/load-test/compare-all-pages.sh, scripts/load-test/compare-one-page.sh
These are the fixes I found by running the load test scripts against the test server.  I've fixed a couple of immediate quick issues found from the tracebacks. 
There are some more new exceptions reported, but they look harmless in the sense of the user not being affected.
=> Fixes for the Python3 upgrade

ci/training-envs/rsr-config/django.conf, ci/training-envs/templates/deployment.yaml
=> [#3906] Remove SMTP email ID from the repo and use env var in config

akvo/templates/project_main_tabs/updates.html, akvo/templates/update_main.html
=> [#3909] Remove force_escape and urlize filters before apply_markup

akvo/rest/urls.py, akvo/rest/views/__init__.py, akvo/rest/views/project_overview.py
=> [#3896] Rename program overview to project overview.

akvo/rest/viewsets.py, akvo/rsr/spa/app/modules/editor/section5/styles.scss, akvo/rsr/spa/app/utils/api.js, akvo/rsr/spa/app/utils/required-hint.jsx, akvo/rsr/tests/rest/test_project_editor.py
=> Mark project editor API calls so IATI checks can be run

akvo/rsr/spa/app/modules/editor/section1/comp/project-photo.jsx, akvo/rsr/spa/package-lock.json, akvo/rsr/spa/package.json
=> Use project REST end-point to upload project images

akvo/rsr/staticmap.py, akvo/settings/85-mapbox.conf
=> [#3876] Use mapbox static map.

ci/training-envs/templates/deployment.yaml
=> [#3876] Use mapbox key from config in training envs

akvo/rsr/dir/app/main.js, akvo/rsr/dir/package-lock.json, akvo/rsr/dir/package.json
=> [#3915] smooth scroll polyfill for safari

nginx/default.conf, nginx/nginx.conf
=> Specific rate limiting for Googlebot

akvo/rest/urls.py, akvo/rest/views/__init__.py, akvo/rest/views/project.py, akvo/rsr/models/location.py, akvo/rsr/tests/rest/test_project.py, scripts/deployment/pip/requirements/2_rsr.txt
=> Add end-point to get GeoJSON with project locations

akvo/rsr/dir/app/modules/index/projects.jsx, akvo/rsr/dir/app/modules/index/view.jsx, akvo/rsr/dir/app/styles/main.scss, akvo/rsr/dir/package-lock.json, akvo/rsr/dir/package.json
=> Latest EUTF Syria updates

akvo/rsr/front-end/scripts-src/classic/jsx/my-user-management.jsx
=> [#3912] Add better error messages to the invite user modal

akvo/rsr/management/commands/user_cleanup.py
=> Improve the user cleanup management script

akvo/rsr/spa/app/modules/editor/section1/section1.jsx
=> s1 fix broken style path

Dockerfile-dev, akvo/rest/serializers/project.py, akvo/rest/views/project.py, akvo/rsr/tests/rest/test_project.py, akvo/settings/30-rsr.conf, scripts/docker/dev/50-docker-local-dev.conf
=> Fix for EUTF Africa

akvo/rsr/views/py_reports.py, akvo/templates/reports/organisation-projects-results-indicators-map-overview.html, akvo/templates/reports/project-results-indicators-map-overview.html, akvo/templates/reports/results-indicators-map-overview.css
* Add project subtitle
* Redesign Summary, Partners, & Location sections on project report.
=> [#3876] EUTF Syria custom reports adjustments.

akvo/rsr/models/result/indicator_period.py, akvo/rsr/tests/models/test_results_aggregation.py
=> [#3980] Fix conversion from NoneType to Decimal error.

akvo/rest/views/project_overview.py
=> [#3985] Add result type.

akvo/iati/exports/elements/result.py, akvo/rsr/tests/iati_export/test_iati_export.py
This PR adds the disaggregation data to the IATI exports using the IndicatorPeriodDisaggregation values. 
See the commit message in https://github.com/akvo/akvo-rsr/commit/b07bd80b2779b38b5093029e25ad74f18f7adfa0 for more information
=> Add disaggregations to the IATI export

akvo/iati/exports/elements/result.py, akvo/rsr/tests/iati_export/test_iati_export.py
=> Add disaggregations to IATI export 

akvo/rsr/tests/base.py, akvo/rsr/tests/results_framework/test_disaggregation_aggregation.py, akvo/rsr/tests/results_framework/test_disaggregation_contribution.py, akvo/rsr/tests/results_framework/util.py
=> Refactoring disaggregation contribution tests.

ci/k8s/deployment.yml, ci/training-envs/gateway/gateway.yaml, ci/training-envs/templates/deployment.yaml
=> Tweaking CPU and health checks

akvo/rsr/views/py_reports/__init__.py, akvo/rsr/views/py_reports/project_results_indicators_excel_report.py, akvo/rsr/views/py_reports/results_indicators_with_map_pdf_reports.py, akvo/rsr/views/py_reports/utils.py, akvo/urls.py, scripts/deployment/pip/requirements/2_rsr.txt
Implements the "Project results indicators simple table" report.
=> [#4014] python excel report

akvo/rest/serializers/__init__.py, akvo/rest/serializers/project_hierarchy.py, akvo/rest/urls.py, akvo/rest/views/__init__.py, akvo/rest/views/project_hierarchy.py, akvo/rsr/models/__init__.py, akvo/rsr/models/project_hierarchy.py, akvo/rsr/tests/rest/test_permissions.py, akvo/rsr/tests/rest/test_project_hierarchy.py
=> Add an API end-point to create new project hierarchies

akvo/rsr/views/py_reports/__init__.py, akvo/rsr/views/py_reports/organisation_data_quality_overview_report.py, akvo/urls.py
=> [#4024] Organisation data quality overview excel report.

akvo/rsr/views/py_reports/__init__.py, akvo/rsr/views/py_reports/results_indicators_with_map_pdf_reports.py, akvo/templates/reports/organisation-projects-results-indicators-map-overview.html, akvo/templates/reports/project-results-indicators-map-overview.html, akvo/templates/reports/results-indicators-map-overview.css, akvo/urls.py
=> [#4031] Results and indicators PDF report.

akvo/rest/views/project_overview.py
=> [#3896] Add update's narrative attribute.

nginx/default.conf
=> Favicon should be served by Nginx

akvo/rsr/spa/app/modules/editor/main-menu.jsx, akvo/rsr/spa/app/modules/editor/section3/section3.jsx, akvo/rsr/spa/app/modules/projects/projects.jsx, akvo/rsr/spa/app/top-bar.jsx
=> [#4096] Enable FAC for SNV users, along with Akvo users

akvo/rest/views/project_overview.py, akvo/rsr/spa/app/modules/program/indicator.jsx, akvo/rsr/tests/rest/test_project_overview.py
=> [#3896] Aggregates percentage values

akvo/rest/serializers/project.py, akvo/rsr/models/project.py
=> [#4083] Project part of a program

akvo/rest/views/project_overview.py, akvo/rsr/tests/rest/test_project_overview.py
=> [#3896] Program targets are aggregated when not set.

akvo/rest/views/project_overview.py
=> [#3896] Add project subtitle attribute.

akvo/rest/views/project_overview.py, akvo/rsr/spa/app/modules/program/indicator.jsx, akvo/rsr/spa/app/modules/program/styles.scss
=> Add subtitles to Program overview

akvo/rsr/tests/rest/test_indicator_dimension.py
=> [#4121] Disaggregation category not unique test.

akvo/rsr/views/py_reports/organisation_data_quality_overview_report.py, akvo/templates/reports/organisation-data-quality-overview.html
=> [#4025] Organisation data quality overview pdf report

akvo/rest/urls.py, akvo/rest/views/__init__.py, akvo/rest/views/project_overview.py
=> [#4114] Indicator overview endpoint.

akvo/rsr/eutf_signals.py, akvo/rsr/models/project.py, akvo/rsr/tests/models/test_project.py
=> Allow Project.set_reporting_org to change the reporting_org

akvo/iati/exports/elements/document_link.py, akvo/iati/exports/org_elements/document_link.py, akvo/rsr/templatetags/rsr_filters.py, akvo/rsr/templatetags/rsr_tags.py, akvo/rsr/tests/test_templatetags.py, akvo/templates/base.html
=> Fix how we create absolute URLs for media

akvo/rsr/views/py_reports/__init__.py, akvo/rsr/views/py_reports/eutf_org_results_table_excel_report.py, akvo/rsr/views/py_reports/utils.py, akvo/urls.py
=> [#4026] EUTF organisation results and indicators excel report.

akvo/rest/views/project_overview.py
=> [#4141] Add baseline year & value to /project/:id/indicator/:id/

akvo/rsr/views/py_reports/__init__.py, akvo/rsr/views/py_reports/results_indicators_excel_report.py, akvo/urls.py
=> [#4027] Results and indicators export excel report.

akvo/rsr/eutf_signals.py, akvo/rsr/models/employment.py, akvo/rsr/models/organisation.py, akvo/rsr/models/partnership.py, akvo/rsr/models/policy_marker.py, akvo/rsr/models/project.py, akvo/rsr/models/related_project.py, akvo/rsr/models/result/disaggregation.py, akvo/rsr/models/result/indicator.py, akvo/rsr/models/result/indicator_period_data.py, akvo/rsr/models/result/indicator_period_disaggregation.py, akvo/rsr/signals.py, scripts/data/load-dev-fixture.sh, scripts/data/update-dev-fixture.sh, scripts/docker/dev/50-docker-local-dev.conf
=> Add scripts to fetch and load dumps from test environment

ci/training-envs/rsr-config/django.conf
=> Change the email host for training envs

akvo/rsr/views/py_reports/__init__.py, akvo/rsr/views/py_reports/organisation_projects_overview_report.py, akvo/urls.py
=> [#4028] Organisation projects overview excel report.

akvo/rest/serializers/project_document.py
Be optimal about what document categories are created and deleted, when
PATCHing a project document.
=> [#4156] Update PATCH request code to not be sloppy

akvo/rsr/views/py_reports/organisation_projects_overview_report.py, akvo/rsr/views/py_reports/utils.py, akvo/templates/reports/organisation-projects-overview.html
=> [#4029] Projects overview pdf report.

akvo/rsr/views/py_reports/__init__.py, akvo/rsr/views/py_reports/eutf_project_results_table_excel_report.py, akvo/urls.py
=> [#4032] EUTF project results and indicators table excel report.

akvo/rsr/views/py_reports/__init__.py, akvo/rsr/views/py_reports/project_updates_excel_report.py, akvo/urls.py
=> [#4030] Project updates table excel report.

akvo/rest/views/project_overview.py, akvo/rsr/models/project.py, akvo/rsr/spa/app/modules/program/indicator.jsx, akvo/rsr/spa/app/modules/program/program.jsx, akvo/rsr/spa/app/modules/program/result.jsx, akvo/rsr/spa/app/modules/program/styles.scss, akvo/rsr/spa/app/modules/projects/filter-country.jsx, akvo/rsr/views/py_reports/__init__.py, akvo/rsr/views/py_reports/project_updates_excel_report.py, akvo/settings/20-default.conf, akvo/urls.py, akvo/utils.py, ci/k8s/deployment.yml, ci/training-envs/templates/deployment.yaml, docker-compose.ci.prod.images.yaml, nginx/default.conf, nginx/start.sh
=> Publish latest to master

akvo/rest/serializers/user_projects.py, akvo/rsr/middleware.py, akvo/settings/10-base.conf, akvo/settings/45-statsd.conf, akvo/urls.py, scripts/deployment/pip/requirements/2_rsr.txt, scripts/deployment/pip/requirements/3_dev.txt, scripts/deployment/pip/requirements/production.in, scripts/docker/dev/50-docker-local-dev.conf
I've upgraded a bunch of requirements, mostly trying to focus on Django apps that we use. It seems like `django-registration` and `django-rest-framework` will need some work to be able to upgrade. Everything else seems to work, though we'd need to do some more testing from the UI, locally and on test.
=> Upgrade a bunch of requirements

akvo/rsr/spa/app/modules/program/indicator.jsx, akvo/settings/30-rsr.conf
=> Disable project index for EUTF + Program overview vpos bugfix

akvo/iati/exports/iati_export.py, akvo/iati/exports/iati_org_export.py
=> [#4179] Use default_storage to create IATI xml files

akvo/settings/30-rsr.conf
=> Fix storage being used to generate IATI xml files

akvo/rsr/spa/app/modules/program/indicator.jsx, akvo/rsr/spa/app/modules/program/program.jsx, akvo/rsr/spa/app/modules/program/result.jsx, akvo/rsr/spa/app/modules/program/sticky-class.jsx, akvo/rsr/spa/app/modules/program/styles.scss
=> Program overview fixes + cascading sticky headers

akvo/rsr/spa/app/modules/program/styles.scss
=> [#4181] polish (fast scroll fix)

akvo/rsr/spa/app/modules/program/indicator.jsx, akvo/rsr/spa/app/modules/program/styles.scss
=> [#4181] disable temporarily (cascading sticky headers)

.gitignore, ci/build-semaphoreci.sh, ci/deploy-semaphoreci.sh, ci/promote-test-to-prod.sh
Use same workflow as other projects:
1. Just build the containers on master branch changes
2. Deploy master changes to TEST env
3. Promote from TEST to PROD cluster, without rebuilding the containers
Fixes #4176
=> Move to Trunk Based Development

akvo/rest/serializers/organisation.py, akvo/rest/serializers/user.py, akvo/rsr/models/user.py, akvo/rsr/spa/app/modules/projects/filter-country.jsx, akvo/rsr/spa/app/modules/users/users.jsx
=> Show content owned organisations in new user management page

akvo/rest/urls.py, akvo/rest/views/__init__.py, akvo/rest/views/indicator_period.py, akvo/rest/views/project_overview.py, akvo/rsr/tests/rest/test_set_periods_locked.py, akvo/rsr/tests/utils.py
=> [#4205] new period endpoints

akvo/rest/serializers/__init__.py, akvo/rest/serializers/indicator.py, akvo/rest/serializers/indicator_period.py, akvo/rest/serializers/indicator_period_data.py, akvo/rest/serializers/result.py, akvo/rest/urls.py, akvo/rest/views/__init__.py, akvo/rest/views/result.py
The new endpoint path:
`/rest/v1/project/<project_id>/results_framework/`
=> [#3998] Yet another results framework fetch endpoint.

akvo/rest/views/project_role.py
=> [#4198] Log permission changes using the FAC APIs

akvo/rsr/views/py_reports/results_indicators_with_map_pdf_reports.py
=> [#4236] Project results report show all location of the project.

akvo/rsr/dir/app/modules/index/view.jsx
=> [#4249] show locationless projects at zoom top level

akvo/rsr/spa/app/modules/reports/reports.jsx
=> [#4214] Show page title for Reports page

akvo/rsr/spa/app/modules/editor/main-menu.jsx, akvo/rsr/spa/app/modules/editor/section3/section3.jsx, akvo/rsr/spa/app/modules/projects/projects.jsx, akvo/rsr/spa/app/modules/projects/table-view.jsx, akvo/rsr/spa/app/top-bar.jsx, akvo/rsr/spa/app/utils/feat-flags.js
=> [#4042] Enable the FAC UI for Nuffic

akvo/rsr/project_overview.py, akvo/rsr/staticmap.py, akvo/rsr/views/py_reports/program_overview_excel_report.py
- Fix staticmap error when coordinates are empty.
- Adjust excel report file naming.
=> Program reports support dates filter.

akvo/rsr/views/py_reports/program_overview_excel_report.py, akvo/rsr/views/py_reports/program_overview_pdf_report.py, akvo/templates/reports/program-overview.html
- Handle empty periods when filtering by dates
- Format values
=> Program report adjustment.

akvo/rest/serializers/disaggregation.py
=> [#4315] Modify disaggregation model serializer for consistency.

akvo/rsr/decorators.py, akvo/rsr/spa/app/modules/reports/reports.jsx, akvo/rsr/spa/app/modules/results/results.jsx, akvo/rsr/spa/app/utils/loading-overlay.jsx, akvo/rsr/spa/app/utils/loading-overlay.scss, akvo/rsr/views/py_reports/eutf_narrative_word_report.py, akvo/rsr/views/py_reports/eutf_org_results_table_excel_report.py, akvo/rsr/views/py_reports/eutf_project_results_table_excel_report.py, akvo/rsr/views/py_reports/kickstart_word_report.py, akvo/rsr/views/py_reports/organisation_data_quality_overview_report.py, akvo/rsr/views/py_reports/organisation_projects_overview_report.py, akvo/rsr/views/py_reports/program_overview_excel_report.py, akvo/rsr/views/py_reports/program_overview_pdf_report.py, akvo/rsr/views/py_reports/project_results_indicators_excel_report.py, akvo/rsr/views/py_reports/project_updates_excel_report.py, akvo/rsr/views/py_reports/results_indicators_excel_report.py, akvo/rsr/views/py_reports/results_indicators_with_map_pdf_reports.py, akvo/templates/reports/program-overview.html
=> [#4310] Implement report downloading indicator.

akvo/iati/exports/elements/result.py, akvo/rsr/tests/iati_export/test_iati_export.py
=> Exclude results with all indicators excluded from IATI export

akvo/rsr/spa/app/modules/iati/new-export-modal.jsx, akvo/rsr/spa/app/modules/iati/styles.scss
=> Prevent unpublished projects and projects with errors from being included in IATI exports

akvo/rsr/dir/app/modules/index/view.jsx, akvo/rsr/dir/app/root.jsx, akvo/rsr/dir/build/index.html, akvo/rsr/front-end/scripts-src/classic/jsx/directory-utils.jsx, akvo/rsr/spa/app/root.jsx, akvo/rsr/spa/app/top-bar.jsx, akvo/rsr/views/project.py, akvo/urls.py, ci/build-semaphoreci.sh, ci/local-build-semaphoreci.sh, docker-compose.override.yaml, nginx/default.conf, scripts/docker/ci/end-to-end.sh, scripts/docker/dev/nginx/default.conf, scripts/docker/dev/nginx/includes/dir-webpack.conf
=> Use / to display the project directory

docker-compose.override.yaml, scripts/docker/dev/50-docker-local-dev.conf
=> Instructions to run a profiler locally

akvo/rest/viewsets.py, akvo/rsr/models/project.py
=> Filter queryset for non-admins only once

akvo/rsr/project_overview.py, akvo/templates/reports/program-overview.css, akvo/templates/reports/program-overview.html
=> [#4343] Show disaggregations on program overview pdf report.

akvo/iati/checks/fields/results.py, akvo/rest/viewsets.py, akvo/rsr/models/project.py
This PR has two commits, the first one makes perf improvements for projects with a large number of checks performed on them, essentially large projects with a lot of transaction/location/results/etc. 
The second commit reduces the number of DB queries made for projects with a large results framework. 
See commit messages for more details.
=> Make the project.update_iati_checks method faster for large projects

akvo/rsr/spa/app/modules/iati/new-export-modal.jsx
=> [#4359] Allow EUTF Africa to export projects with errors to IATI

akvo/rsr/spa/app/index.html, akvo/rsr/spa/app/root.jsx, ci/k8s/deployment.yml, docker-compose.ci.prod.images.yaml, nginx/start.sh, scripts/docker/ci/end-to-end.sh
=> Initialize Sentry SDK with correct release name and environment in SPA

akvo/rsr/spa/app/modules/projects/projects.jsx
=> [#4383] Don't create sub-programs by default for RSR Admins

akvo/rsr/views/py_reports/project_results_indicators_excel_report.py, akvo/rsr/views/py_reports/utils.py
=> [#4403] rearrange disaggregations position in project excel report.

akvo/rsr/views/py_reports/project_results_indicators_excel_report.py
=> Fix project excel report bug.

akvo/rsr/spa/app/modules/editor/custom-fields.jsx, akvo/rsr/spa/app/modules/editor/section1/section1.jsx
=> [#4411] mwc readonly fields

nginx/default.conf
Relates https://github.com/akvo/hortinvest/issues/5
Using https://nginx.org/en/docs/http/ngx_http_map_module.html
=> Add cors to include akvo.org subdomains

akvo/rest/serializers/disaggregation.py, akvo/rest/serializers/indicator_period_data.py, akvo/rsr/tests/rest/test_indicator_period_data.py
=> [#4409] disaggregations validation

akvo/rest/serializers/indicator.py
=> [#4449] Handle empty value on indicator targets

akvo/rest/views/project.py, akvo/rsr/spa/app/modules/editor/actions.js, akvo/rsr/spa/app/modules/project-view/project-view.jsx, akvo/rsr/spa/app/modules/results/filters.js, akvo/rsr/spa/app/modules/results/filters.test.js, akvo/rsr/spa/app/modules/results/results.jsx
=> [#4438] results filter inconsistency

akvo/rest/serializers/indicator_period_data.py, akvo/rsr/management/commands/fix_project_qualitative_narrative_text_update.py, akvo/rsr/spa/app/modules/results/edit-update.jsx, akvo/rsr/spa/app/modules/results/enumerator.jsx, akvo/rsr/spa/app/modules/results/period.jsx
=> [#4462] qualitative update inconsistency

akvo/rsr/front-end/scripts-src/my-results/components/periods/Periods.jsx, akvo/rsr/front-end/scripts-src/my-results/components/updates/UpdateHeader.jsx, akvo/rsr/front-end/scripts-src/my-results/components/updates/Updates.jsx
=> [#4469] Show qualitative updates on public page

akvo/rsr/spa/app/modules/results/enumerator.jsx, akvo/rsr/spa/app/modules/results/pending-approval.jsx, akvo/rsr/spa/app/modules/results/period.jsx
=> [#4486] ask for reason to decline update & show the reason in enum form

akvo/rsr/views/py_reports/docx_utils.py
=> [#4484] fix markdown to docx bug

akvo/rest/views/project_editor.py, akvo/rsr/models/project.py, akvo/rsr/models/result/result.py, akvo/rsr/spa/app/modules/editor/section5/indicators.jsx, akvo/rsr/spa/app/modules/editor/section5/section5.jsx, akvo/rsr/tests/rest/test_project_editor.py
=> [#4492] results reordering

akvo/rsr/spa/app/modules/editor/section11/flags/flags-stack.jsx, akvo/rsr/spa/app/modules/editor/section5/disaggregations/dimension-box.jsx, akvo/rsr/spa/app/modules/editor/section5/indicators.jsx, akvo/rsr/spa/app/modules/editor/section7/recipient-countries/recipient-countries.jsx, akvo/rsr/spa/app/modules/editor/section8/humanitarian-scopes/humanitarian-scope.jsx, akvo/rsr/spa/app/modules/program/indicator.jsx, akvo/rsr/spa/app/modules/projects/cards-view.jsx, akvo/rsr/spa/app/modules/results/enumerator.jsx, akvo/rsr/spa/app/modules/results/period.jsx, akvo/rsr/spa/app/modules/results/results.jsx, akvo/rsr/spa/app/modules/results/styles.scss, akvo/rsr/spa/app/top-bar.jsx
Other files changes by lintter
* Add conditional pinned to showing indicator description.
* Lintter remove unused variable.
* Linter suggest to add key in each list item.
* Linter suggest use undefined instead of conditional className.
* Add markdown parse for each description that has markdown formatter.
=> [#4497] Resolved showing indicator description

akvo/rest/views/project_overview.py, akvo/rsr/project_overview.py, akvo/rsr/tests/rest/test_project_overview.py, akvo/rsr/views/py_reports/program_overview_excel_report.py, akvo/rsr/views/py_reports/utils.py, akvo/settings/30-rsr.conf
=> [#4502] aggregate indicator targets

akvo/rsr/spa/app/modules/enumerators/enumerators.jsx, akvo/rsr/spa/app/modules/results/enumerator.jsx
Description doesn't match with the first title.
* create initial states for indicators.
* change condition of preview url params.
* setSelected indicator after filtering periods isPeriodNeedsReporting.
=> [#4507] Bug fixing initial indicator description

akvo/rest/serializers/indicator_period.py, akvo/rest/serializers/indicator_period_data.py, akvo/rsr/spa/app/modules/results/enumerator.jsx, akvo/rsr/spa/app/modules/results/pending-approval.jsx, akvo/rsr/spa/app/utils/rte.jsx
=> [#4511] pending approval's internal notes

akvo/rest/serializers/indicator_period_data.py, akvo/rsr/tests/rest/test_indicator_period_data.py
=> [#4518] nested comments at indicator_period_data_framework endpoint

akvo/rsr/tests/views/test_account.py, akvo/rsr/views/account.py, akvo/urls.py
=> [#4437] ajax login and reset password endpoint

akvo/rsr/spa/app/modules/editor/actions.js, akvo/rsr/spa/app/modules/editor/endpoints.js, akvo/rsr/spa/app/modules/editor/section5/periods/targets.jsx, akvo/rsr/spa/app/utils/auto-save.jsx
Something odd is happening when trying to report an indicator value (Loading indicator at the save button).
Trying to set the target for a disaggregation label in section 5 of the Editor. There is an helpful _"Something went wrong message"_
=> Resolved issue EUTF Syria reported

akvo/rsr/tests/views/test_account.py, akvo/rsr/views/account.py, akvo/urls.py
=> [#4437] ajax register endpoint

akvo/rsr/spa/app/modules/results/period.jsx
I try to solve this issue by 
- Show Alert after Submit indicator has error response and 
- Stop Loading indicator (Spinner) at the button when user is cancel, response API is error.
=> Fixes #4550 submit issue with decimals

akvo/rest/urls.py, akvo/rest/views/__init__.py, akvo/rest/views/indicator_period.py, akvo/rsr/spa/app/modules/editor/section5/indicators.jsx, akvo/rsr/spa/app/modules/editor/section5/periods/defaults-context.jsx, akvo/rsr/spa/app/modules/editor/section5/periods/defaults-context.test.js, akvo/rsr/spa/app/modules/editor/section5/periods/defaults-modal.jsx, akvo/rsr/spa/app/modules/editor/section5/periods/periods.jsx, akvo/rsr/spa/app/modules/editor/section5/section5.jsx, akvo/rsr/spa/app/utils/auto-save.jsx, akvo/rsr/tests/rest/test_bulk_indicator_periods.py
=> [#4542] Apply recently added or removed default periods to existing indicators

akvo/rsr/spa/app/modules/results/edit-update.jsx, akvo/rsr/spa/app/modules/results/edit-update.scss, akvo/rsr/spa/app/modules/results/enumerator.jsx, akvo/rsr/spa/app/modules/results/enumerator.scss, akvo/rsr/spa/app/modules/results/period.jsx
=> [#4547] Handle percentage update submission

akvo/rsr/dir/package-lock.json, akvo/rsr/spa/app/modules/project-view/project-view.jsx, akvo/rsr/spa/app/modules/projects/filter-country.jsx, akvo/rsr/spa/app/modules/reports/reports.jsx, akvo/rsr/spa/app/modules/results/filter-bar.jsx, akvo/rsr/spa/app/modules/results/pending-approval.jsx, akvo/rsr/spa/app/modules/results/period.jsx, akvo/rsr/spa/app/modules/results/results.jsx, akvo/rsr/spa/app/modules/results/router.jsx, akvo/rsr/spa/app/modules/results/styles.scss, akvo/rsr/spa/app/modules/results/update.jsx, akvo/rsr/spa/app/utils/final-field.jsx, akvo/rsr/spa/app/utils/misc.js, akvo/rsr/spa/package-lock.json
Remove checkbox tobe reported, pending and approved
* Create function getUniue array at misc .
* Modify styling filter-bar.
* Set default results overview and resulst admin.
* Display a messsage for pending approval is empty.
=> Closes #4541 Results View Restructuring

akvo/rsr/spa/app/modules/results/enumerator.jsx, akvo/rsr/spa/app/modules/results/enumerator.scss, akvo/rsr/spa/app/modules/results/pending-approval.jsx, akvo/rsr/spa/app/modules/results/pending-approval.scss, akvo/rsr/spa/app/modules/results/styles.scss, akvo/rsr/spa/app/modules/results/update.jsx
1. Replace checklist icon with small circle
2. Modify enumerator scss to create small circle.
3. Small circle color update based on its status.
4. Remove loading indicator at the left side submit button.
5. Create the approve all buttons sticky and change lock button type is filled danger.
=> Closes #4536 Redesign Enumerator View

akvo/rsr/spa/app/modules/editor/section5/periods/defaults-modal.jsx, akvo/rsr/spa/app/modules/editor/section5/periods/periods.jsx
Overlapping functionality with the "Apply recently added ..." action.
=> [#4542] Remove Add to indicator button

akvo/rsr/management/commands/a4a_change_hierarchy.py, akvo/rsr/models/project.py, akvo/rsr/tests/results_framework/test_results_framework.py
Also, adds a management command to change hierarchy for an a4a project
=> [#4481] Add function to change parent to a sibling of current parent

akvo/rsr/spa/app/modules/editor/actions.js, akvo/rsr/spa/app/modules/editor/section5/periods/periods.jsx, akvo/rsr/spa/app/utils/auto-save.jsx
1. Find project ID : 9878.
2. Go to tab Editor.
3. Click on 5. Results and Indictors.
4. Then select *Other Result 2: Biannual SMQ update - Community Sanitation *.
5. Open first indicator Quantitative Indicator 1 - ...
6. Go down until you get Periods section,
7. Click at Copy defaults button. * Defaults periods will applied
8. and then reload that page.
9. Previously applied defaults periods will be lost.
=> Closes #4542 Copy defaults can't  save data

akvo/rsr/spa/app/modules/project-view/project-view.jsx, akvo/rsr/spa/app/modules/results/enumerator.scss, akvo/rsr/spa/app/modules/results/filter-checkbox.jsx, akvo/rsr/spa/app/modules/results/results.jsx
=> Closes #4541 Disabled Results admin view

akvo/rsr/management/commands/remove_disaggregation_targets_dupes.py
=> [#4567] Management command to remove duplicate disaggregation targets

akvo/rsr/spa/app/modules/projects/table-view.jsx
=> Closes #4541 Bug fixing redirect old version caused 403

akvo/rsr/spa/app/modules/hierarchy/hierarchy.jsx
=> [#4576] Fixes multiple root programs in project hierarchy

akvo/rsr/models/result/indicator_period_data.py, akvo/rsr/spa/app/modules/results/enumerator.jsx, akvo/rsr/spa/app/modules/results/enumerator.scss, akvo/rsr/tests/rest/test_result.py
=> Closes #4451 Nuffic collaborate draft updates

akvo/rest/serializers/project.py, akvo/rest/views/project.py, akvo/rsr/spa/app/modules/editor/editor.jsx, akvo/rsr/spa/app/modules/hierarchy/card.jsx, akvo/rsr/spa/app/modules/hierarchy/hierarchy.jsx, akvo/rsr/spa/app/modules/program/program.jsx, akvo/rsr/spa/app/modules/project-view/project-view.jsx, akvo/rsr/spa/app/modules/projects/conditional-link.jsx, akvo/rsr/spa/app/modules/projects/table-view.jsx, akvo/rsr/spa/app/modules/results/enumerator.jsx
I tried solve this issue with :
1. Keep button is disabled and change the text of publish button with "Loading..." when page is not ready.
2. Bug fixing Tab Active (blue line) in the wrong place.
=> Closes #4574 Bug fixing publish button clicked

akvo/rest/serializers/indicator.py, akvo/rest/views/project.py, akvo/rest/views/project_overview.py, akvo/rest/views/result.py, akvo/rsr/spa/app/modules/program/indicator.jsx, akvo/rsr/spa/app/modules/program/program.jsx, akvo/rsr/spa/app/modules/program/result.jsx, akvo/rsr/spa/app/modules/program/styles.scss, akvo/rsr/spa/app/modules/project-view/project-view.jsx, akvo/rsr/spa/app/modules/results/period.jsx, akvo/rsr/spa/app/modules/results/results.jsx, akvo/rsr/spa/app/modules/results/router.jsx, akvo/rsr/spa/app/utils/misc.js, akvo/rsr/spa/app/utils/misc.test.js, akvo/rsr/spa/app/utils/target-charts.jsx
=> [#4580] Indicator target visualization

akvo/rest/fields.py, akvo/rest/serializers/project_update.py, akvo/rsr/spa/app/modules/updates/updates-photo.js, akvo/rsr/spa/app/modules/updates/updates-validator.js, akvo/rsr/spa/app/modules/updates/updates.jsx, akvo/rsr/templatetags/rsr_utils.py
=> [#4583] project updates issues

akvo/rsr/spa/app/modules/results/period.jsx, akvo/rsr/spa/app/modules/results/results.jsx, akvo/rsr/spa/app/utils/final-field.jsx
- commit reference 766f72abfa08cda02a30c8cb4db63d8682705937
=> Closes #4582 Result Overview edit and delete functionality reintroduced

akvo/rsr/spa/app/modules/editor/section4/section4.jsx
Combining order of descriptions by rule with by default
=> Closes #4586 Goals Overview Section

akvo/rsr/spa/app/modules/editor/reducer.test.js, akvo/rsr/spa/app/modules/editor/section5/periods/defaults-context.test.js, akvo/rsr/spa/app/modules/projects/conditional-link.test.jsx, akvo/rsr/spa/app/utils/misc.js, akvo/rsr/spa/app/utils/misc.test.js
=> Closes #4578 Update Front End Unit Testing

akvo/rsr/dir/app/modules/index/map.jsx, akvo/rsr/dir/app/styles/main.scss
=> [#4594] Implement project directory map cluster popup

scripts/docker/ci/build.sh, scripts/docker/dev/start-django.sh
=> [#4590] Run frontend tests on CI

akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx, akvo/rsr/spa/app/modules/results-overview/ResultOverview.jsx, akvo/rsr/spa/app/modules/results-overview/components/FilterBar.jsx
1. http://localhost/my-rsr/projects/2602/results (HortImpact)
2. http://localhost/my-rsr/projects/9798/results (ASWA Mali)
=> Closes #4599 Filter periods tweaks

akvo/rsr/spa/app/modules/project-view/project-view.jsx, akvo/rsr/spa/app/modules/results/period.jsx, akvo/rsr/spa/app/modules/results/router.jsx, akvo/rsr/spa/app/modules/results/styles.scss
Mark draft status by className draft-update
=> Closes [#4588] draft indicator update 

akvo/rsr/spa/app/modules/project-view/project-view.jsx, akvo/rsr/spa/app/modules/results/enumerator.jsx
- Bug fixing Result Admin tab for Enumerator
- Bug fixing invalid selected indicator
=> Closes #4603 Enumerator should not see Result Admin

akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx, akvo/rsr/spa/app/modules/results/results.jsx
- http://localhost/my-rsr/projects/9878/results
[#4608] Create search functionality at pending approval view
=> Closes #4608 Pending approvals tab

akvo/rsr/spa/app/components/AddUpdate.jsx, akvo/rsr/spa/app/components/StatusPeriod.jsx, akvo/rsr/spa/app/modules/results-overview/components/UpdatePeriod.jsx, akvo/rsr/spa/app/modules/results/enumerator.scss, akvo/rsr/spa/app/modules/results/pending-approval.jsx, akvo/rsr/spa/app/modules/results/period.jsx
[#4601] Add status component at Results Overview
=> Closes #4601 'Approved' indicator update status

akvo/rsr/spa/app/modules/results/enumerator.scss, akvo/rsr/spa/app/utils/final-field.jsx, akvo/rsr/spa/app/utils/misc.js, akvo/rsr/spa/app/utils/misc.test.js
=> Closes #4613 text spilling over

akvo/rest/serializers/indicator_period_data.py, akvo/rest/views/indicator_period_data.py, akvo/rsr/tests/rest/test_indicator_period_data.py, akvo/rsr/tests/utils.py
=> [#4617] Indicator period data audit trail

akvo/rsr/spa/app/modules/results-admin/components/TobeReported.jsx, akvo/rsr/spa/app/modules/results/enumerator.jsx, akvo/rsr/spa/app/modules/results/enumerator.scss, akvo/rsr/spa/app/modules/results/filters.js, akvo/rsr/spa/app/modules/results/filters.test.js, akvo/rsr/spa/app/modules/results/router.jsx
[#4616] Create sticky indicator at results admin
=> Closes #4616 Results admin sticky indicator

akvo/rest/views/indicator_period_data.py, akvo/rsr/tests/rest/test_indicator_period_data.py
=> [#4638] Fix indicator update bug when rejected or approved

akvo/rest/views/project_enumerators.py, akvo/settings/30-rsr.conf, akvo/templates/enumerators/a4a_assignment_message.txt, akvo/templates/registration/a4a_project_invited_user_message.html, akvo/templates/registration/a4a_project_invited_user_message.txt, akvo/utils.py
=> [#4640] Make custom email text for A4A

akvo/rest/serializers/project.py, akvo/rest/views/project_role.py, akvo/rsr/models/user.py, akvo/rsr/spa/app/main.js, akvo/rsr/spa/app/modules/editor/section3/access/access.jsx, akvo/rsr/spa/app/modules/editor/section3/section3.jsx, akvo/rsr/tests/rest/test_project_role.py, akvo/settings/30-rsr.conf
=> [#4635] A4A project role M&E manager add Enumerators

akvo/rest/views/project_overview.py
The `/rest/v1/project/<project_id>/results/` endpoint has additional props
- contributors
- partners
- periods
=> [#4642] Add additional props to support program filter

akvo/rsr/spa/app/components/AddUpdate.jsx, akvo/rsr/spa/app/components/DeclinedStatus.jsx, akvo/rsr/spa/app/modules/results/enumerator.jsx, akvo/rsr/spa/app/utils/hooks.js
=> [#4628] Replace DeclinedStatus component

akvo/rsr/spa/app/components/AuditTrail.jsx, akvo/rsr/spa/app/modules/results/styles.scss, akvo/rsr/spa/app/modules/results/update.jsx
=> #4617 Implement Audit Trail at Front End Side

docker-compose.override.yaml
Remove empty rsr-memcached service definition
Fixes #4647
=> [#4647] Modify docker-compose.override.yaml

akvo/rsr/forms.py, akvo/rsr/registration.py, akvo/rsr/tests/views/test_account.py, akvo/rsr/views/account.py, akvo/settings/10-base.conf, akvo/urls.py, scripts/deployment/pip/requirements/2_rsr.txt, scripts/deployment/pip/requirements/3_dev.txt, scripts/deployment/pip/requirements/production.in
=> [#4679] HMAC activation workflow

akvo/rest/serializers/indicator_period.py, akvo/rest/serializers/project.py, akvo/rest/views/report.py, akvo/rest/views/result.py, akvo/rest/views/user.py, akvo/rest/viewsets.py, akvo/rsr/models/result/indicator_period_data.py, akvo/rsr/models/user.py, akvo/rsr/permissions.py, akvo/rsr/project_role_auth.py, akvo/rsr/views/project.py, scripts/docker/ci/build.sh
Fix #4691: Using user.is_authenticated() and user.is_anonymous() as a method is deprecated
=> #4691: Using user.is_authenticated() and user.is_anonymous() as a method is deprecated

akvo/rsr/spa/app/components/IndicatorItem.jsx, akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx, akvo/rsr/spa/app/modules/results-admin/components/TobeReported.jsx, akvo/rsr/spa/app/modules/results/enumerator.jsx, akvo/rsr/spa/app/modules/results/enumerator.scss
- Add scrollPosition at results admin.
=> [#4700] Fix indicators at enumerator & admin view

scripts/docker/dev/nginx/default.conf
=> Fix reports container bad gateway response in dev environment

akvo/rsr/spa/app/components/AuditTrail.jsx, akvo/rsr/spa/app/components/ScoringField.jsx, akvo/rsr/spa/app/modules/editor/styles.scss, akvo/rsr/spa/app/modules/results/enumerator.jsx, akvo/rsr/spa/app/modules/results/update.jsx, akvo/rsr/spa/app/utils/final-field.jsx, akvo/rsr/spa/app/utils/input-label.jsx
=> [#4626] Remove checkbox & show scores at results overview

akvo/rsr/spa/app/components/IndicatorItem.jsx, akvo/rsr/spa/app/components/ScoringField.jsx, akvo/rsr/spa/app/modules/enumerators/enumerators.jsx, akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx, akvo/rsr/spa/app/modules/results-admin/components/TobeReported.jsx, akvo/rsr/spa/app/modules/results/enumerator.jsx, akvo/rsr/spa/app/modules/results/enumerator.scss, akvo/rsr/spa/app/modules/results/filters.js, akvo/rsr/spa/app/modules/results/filters.test.js, akvo/rsr/spa/app/modules/results/pending-approval.jsx
=> [#4712] Fix newly assigned and pre-approved indicator

akvo/rsr/spa/app/components/AddUpdate.jsx, akvo/rsr/spa/app/components/ScoringField.jsx, akvo/rsr/spa/app/modules/editor/section5/indicators.jsx, akvo/rsr/spa/app/modules/results-overview/components/UpdatePeriod.jsx, akvo/rsr/spa/app/modules/results/enumerator.jsx, akvo/rsr/spa/app/modules/results/period.jsx
Trying to fix issues following :
1. [14. Submission date stamp from 'Draft' status updates
Sep 20](https://akvo.zulipchat.com/#narrow/stream/292992-Akvo-RSR.20-.20Results.20Admin.20Review/topic/14.2E.20Submission.20date.20stamp.20from.20'Draft'.20status.20updates/near/263197468)
2. [15. Unclear/incorrect 'Submit' interaction](https://akvo.zulipchat.com/#narrow/stream/292992-Akvo-RSR.20-.20Results.20Admin.20Review/topic/15.2E.20Unclear.2Fincorrect.20'Submit'.20interaction).
3. [16. Draft status issues (scoring)](https://akvo.zulipchat.com/#narrow/stream/292992-Akvo-RSR.20-.20Results.20Admin.20Review/topic/16.2E.20Draft.20status.20issues.20.28scoring.29/near/258354159)
=> [#4631] Replace createdAt w/ lastModified at header update

akvo/rsr/management/commands/change_project_parent.py, akvo/rsr/management/commands/nuffic_hierarchy_changes.py, akvo/rsr/usecases/change_project_parent.py
=> [#4714] Make reimport step optional when change project parent

akvo/rest/cache.py, akvo/rest/serializers/project.py, scripts/deployment/pip/requirements/2_rsr.txt, scripts/deployment/pip/requirements/3_dev.txt, scripts/deployment/pip/requirements/production.in
=> [#4725] Improve project directory performance

akvo/rest/cache.py, akvo/rest/views/project.py, akvo/rsr/dir/app/modules/index/view.jsx
=> [#4725] Project directory performance improvement part 2

akvo/settings/20-default.conf
To allow uploading large image files.
=> [#4733] Increase max request body limit

akvo/rsr/management/commands/clear_all_sessions.py, akvo/rsr/spa/app/main.js
It helps us in cases where everybody has to be logged out in order to force them to login again.
=> Add command clear_all_sessions

akvo/rest/cache.py, akvo/rest/views/project.py
=> [#4748] Cache project directory response

akvo/rsr/spa/app/modules/updates/updates.jsx
=> [#4745] Fix can't delete main photo at project updates

akvo/rest/views/indicator_period_data.py, akvo/rsr/tests/rest/test_indicator_period_data.py
=> [#4741] Fix Nuffic collaborate draft updates bug

akvo/rsr/spa/app/modules/project-view/project-view.jsx
=> [#4541] Remove results admin featflag except nuffic

scripts/deployment/pip/requirements/2_rsr.txt, scripts/deployment/pip/requirements/3_dev.txt, scripts/deployment/pip/requirements/production.in
Dependabot flagged it in https://github.com/advisories/GHSA-v6rh-hp5x-86rv
=> Upgrade to Django>=3.2.10

akvo/rsr/management/commands/delete_untitled_and_unpublished_projects.py, akvo/rsr/tests/base.py, akvo/rsr/tests/commands/test_delete_untitled_and_unpublished_projects.py
=> [#4767] Create script to delete untitled and unpublished projects

ci/build-semaphoreci.sh
Closes #4769 
- defines a necessary function (`checksum`)
- doesn't attempt to log into DockerHub
=> [#4769] Fix Local CI execution

akvo/rsr/management/commands/report_d2d.py
=> [#4765] Adjust script to generate D2D report

akvo/rsr/management/commands/delete_empty_project_relations.py, akvo/rsr/models/related_project.py
=> [#4783] Make script to delete empty project relations

akvo/rsr/spa/app/modules/results-admin/PendingApproval.jsx, akvo/rsr/spa/app/modules/results-admin/TobeReported.jsx, akvo/rsr/spa/app/modules/results-admin/components/ReportedEdit.jsx, akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx, akvo/rsr/spa/app/modules/results/enumerator.scss, akvo/rsr/spa/app/modules/results/router.jsx
Refactoring Enumerator view to submit updates with new UI
https://xd.adobe.com/view/856e52a9-ecab-489b-8866-2c8c05ec4a7b-d03d/
=> [#4582] Refactoring UI Enumerator view and edit, del reintroduced

akvo/rsr/spa/app/components/AddUpdate.jsx, akvo/rsr/spa/app/modules/results-admin/components/ReportedForm.jsx, akvo/rsr/spa/app/modules/results/enumerator.jsx
1. Login as Enumerator _Juliette Eul**rink_
2. Go to [http://localhost/my-rsr/projects/8136/results](http://localhost/my-rsr/projects/8136/results)
3. Open Indicator ```A.E.2. Increased participation of students from minorities```
4. Put zero at Denominator field
5. Error
=> [#4582] Fix: input zero at denominator field

akvo/rsr/models/project.py, akvo/rsr/spa/app/modules/editor/section5/periods/periods.jsx, akvo/rsr/spa/app/modules/editor/section5/section5.jsx, akvo/rsr/spa/app/utils/required-hint.jsx
=> [#4755] Fix: Invalid periods from targetsAt

akvo/rsr/spa/app/modules/editor/section5/periods/periods.jsx
=> [#4754] Fix can't delete periods copied from defaults

akvo/rsr/dataclasses.py, akvo/rsr/views/py_reports/program_overview_excel_report.py
=> [#4798] Add baseline column in program report

akvo/rsr/models/iati_import_job.py
=> [#4800] Don't send IATI import emails to admins

akvo/rsr/spa/app/components/AuditTrail.jsx, akvo/rsr/spa/app/components/StatusIndicator.jsx, akvo/rsr/spa/app/modules/program/indicator.jsx, akvo/rsr/spa/app/modules/results-admin/PendingApproval.jsx, akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx, akvo/rsr/spa/app/modules/results-admin/TobeReported.jsx, akvo/rsr/spa/app/modules/results-admin/TobeReported.scss, akvo/rsr/spa/app/modules/results-overview/ResultOverview.jsx, akvo/rsr/spa/app/modules/results-overview/components/FilterBar.jsx, akvo/rsr/spa/app/modules/results-overview/components/Indicator.jsx, akvo/rsr/spa/app/modules/results-overview/components/UpdatePeriod.jsx, akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx, akvo/rsr/spa/app/modules/results/enumerator.scss, akvo/rsr/spa/app/modules/results/styles.scss, akvo/rsr/spa/app/modules/results/update.jsx
=> [#4803] Fix results overview page

akvo/rsr/spa/app/components/StatusIndicator.jsx, akvo/rsr/spa/app/modules/results-admin/TobeReported.jsx, akvo/rsr/spa/app/modules/results-admin/TobeReported.scss, akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx, akvo/rsr/spa/app/modules/results/styles.scss
- Adding label at indicator panel.
- Fix Alignment of close button.
- Remove description at indicator panel.
=> [#4802] Fix: Indicator status panel at Results admin view

akvo/rsr/spa/app/modules/results-overview/ResultOverview.jsx, akvo/rsr/spa/app/modules/results/styles.scss
=> [#4803] Add title indicator at results overview

akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx, akvo/rsr/spa/app/modules/results-admin/TobeReported.jsx, akvo/rsr/spa/app/modules/results-admin/components/ReportedEdit.jsx, akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx
=> [#4802] Move description and period at results admin

akvo/rsr/management/commands/populate_local_db.py, akvo/rsr/tests/base.py
This allows clean dev envs to create programs in the frontend
Closes #4788 Clean dev envs can't create programs in the frontend
=> [#4788] create an initial program in dev env

akvo/rsr/spa/app/modules/editor/project-init-handler.js, akvo/rsr/spa/app/modules/editor/section7/section7.jsx
1. Login to RSR
2. Choose any project.
3. Go to Editor.
4. Click Location menu and
5. Go to Hierarchy tab quickly 
6. Choose other project.
7. Go to Editor and click location quickly.
8. Focus on Location name if Location is exist.
9. Repeat from step 5 - 8 until you got Location name is suddenly changing from previous state to new one.
=> [#4806] Fix: delayed location changes by adding loading indicator

akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx, akvo/rsr/spa/app/modules/results-admin/TobeReported.jsx, akvo/rsr/spa/app/modules/results-admin/components/ReportedEdit.jsx, akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx, akvo/rsr/spa/app/modules/results/filters.js
1. Go to https://rsr.test.akvo.org/my-rsr/projects/9559/results
2. Unlock any period. eg : first indicator second period like this
3. Go to Results admin
4. Unlocked period not found
=> 4802 unlock period not showing

akvo/rsr/spa/app/modules/editor/section9/docs/uploader.jsx
=> [#4814] Fix upload document at section 9

akvo/rsr/spa/app/modules/editor/actions.js, akvo/rsr/spa/app/modules/project-view/project-view.jsx
=> [#4823] Fix project editor permissions at project view

akvo/rsr/spa/app/modules/editor/section5/periods/periods.jsx, akvo/rsr/spa/app/utils/auto-save.jsx
=> [#4754] Fix sometimes get an error when deleting periods

akvo/rsr/dataclasses.py, akvo/rsr/views/py_reports/program_overview_excel_report.py
=> [#4846] Nuffic reports bugs

akvo/rsr/spa/app/modules/editor/actions.js, akvo/rsr/spa/app/modules/editor/project-init-handler.js, akvo/rsr/spa/app/modules/editor/reducer.js, akvo/rsr/spa/app/modules/editor/section1/comp/external-projects.jsx, akvo/rsr/spa/app/modules/editor/section1/comp/project-picker.jsx, akvo/rsr/spa/app/modules/editor/section1/section1.jsx
=> [#4837] Fix bug 'contributed to' field not saved

akvo/rsr/spa/app/modules/editor/section5/section5.jsx, akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx, akvo/rsr/spa/app/modules/results-admin/components/ReportedForm.jsx, akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx, akvo/rsr/spa/app/modules/results/update.jsx
http://localhost/my-rsr/projects/9419/results
=> [#4853] Fix percentage indicator update at TobeReport

akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx
=> [#4853] Hide existing percentage update for non-authors

akvo/rsr/spa/app/components/StatusPeriod.jsx, akvo/rsr/spa/app/modules/project-view/project-view.jsx, akvo/rsr/spa/app/modules/results-overview/ResultOverview.jsx, akvo/rsr/spa/app/modules/results-overview/ResultOverview.scss, akvo/rsr/spa/app/modules/results-overview/components/Indicator.jsx, akvo/rsr/spa/app/modules/results-overview/components/UpdateItems.jsx, akvo/rsr/spa/app/modules/results-overview/components/UpdatePeriod.jsx, akvo/rsr/spa/app/modules/results/router.jsx, akvo/rsr/spa/app/modules/results/timeline.jsx
=> [#4582] Add edit feature at results overview

akvo/rsr/spa/app/modules/program/ApprovedUpdates.jsx, akvo/rsr/spa/app/modules/program/Comments.jsx, akvo/rsr/spa/app/modules/program/Disaggregations.jsx, akvo/rsr/spa/app/modules/program/ExpandIcon.jsx, akvo/rsr/spa/app/modules/program/ProgramPeriod.jsx, akvo/rsr/spa/app/modules/program/ProjectSummary.jsx, akvo/rsr/spa/app/modules/program/config.js, akvo/rsr/spa/app/modules/program/indicator.jsx, akvo/rsr/spa/app/modules/program/program.jsx, akvo/rsr/spa/app/modules/program/result.jsx
=> [#4860] Fix invalid disaggregation at program overview

akvo/rsr/spa/app/modules/results-admin/PendingApproval.jsx, akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx, akvo/rsr/spa/app/modules/results-admin/TobeReported.jsx, akvo/rsr/spa/app/modules/results-admin/components/ReportedEdit.jsx, akvo/rsr/spa/app/modules/results-overview/ResultOverview.scss, akvo/rsr/spa/app/modules/results-overview/components/UpdateItems.jsx, akvo/rsr/spa/app/modules/results-overview/components/UpdatePeriod.jsx, akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx, akvo/rsr/spa/app/modules/results/update.jsx
=> [#4853] Hide approved update at tobe reported view

akvo/rsr/spa/app/modules/results-admin/components/ReportedEdit.jsx
=> [#4582] Fix invalid disabled input form

akvo/rsr/spa/app/modules/results-admin/PendingApproval.jsx, akvo/rsr/spa/app/modules/results-admin/TobeReported.jsx, akvo/rsr/spa/app/modules/results-overview/components/UpdatePeriod.jsx, akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx
=> [#4582] Fix typo confirm deletion message

akvo/rsr/management/commands/a4a_optimy_import.py
=> [#4871] A4A include finalised projects

akvo/rest/authentication.py, akvo/rest/views/project.py, akvo/rest/viewsets.py, akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx
- Create a form access link for an enumerator 
e.g `http://localhost/my-rsr/projects/9570/results/?rt=....`
- Create a new draft update   
- Reload the page and ensure that the status changed
=> [#4875]: Fix: Form access link doesn't show submitted results and drafts

akvo/rsr/checks/indicators.py, akvo/rsr/checks/periods.py, akvo/rsr/checks/results.py, akvo/rsr/management/commands/data_integrity.py, akvo/rsr/management/commands/helpers/data_integrity.py
=> [#4822] extend data integrity command to include results with parents belonging to multiple projects

akvo/rsr/spa/app/components/LineChart.jsx, akvo/rsr/spa/app/components/ProgressBar.jsx, akvo/rsr/spa/app/components/ProgressBar.scss, akvo/rsr/spa/app/modules/results-overview/ResultOverview.scss, akvo/rsr/spa/app/modules/results-overview/components/UpdateItems.jsx, akvo/rsr/spa/app/modules/results/styles.scss
**Check with the following projects**
](http://localhost/my-rsr/projects/9290/results)
=> [#4827] Feat req: Update chart visuals for indicator reporting

akvo/rsr/tests/rsr_utils/test_utils.py, akvo/utils.py, akvo/wsgi.py, ci/build-semaphoreci.sh, ci/k8s/config-prod.yml, ci/k8s/config-test.yml, ci/k8s/deployment.yml, ci/training-envs/templates/deployment.yaml, scripts/deployment/pip/requirements/2_rsr.txt, scripts/deployment/pip/requirements/3_dev.txt, scripts/deployment/pip/requirements/production.in
We need to know how our application is performing and why.
It should be possible for us to find out where bottlenecks are or  where we're wasting cycles and being inefficient.
-----------
Closes #4880
=> [#4880] Run Google Cloud Profiler in GCP

akvo/rsr/spa/app/modules/results-overview/components/FilterBar.jsx, akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx
=> [#4889] Fix bug: Enumerators can see unassigned indicators

akvo/rsr/spa/app/components/AddUpdate.jsx, akvo/rsr/spa/app/modules/results-admin/components/ReportedForm.jsx, akvo/rsr/spa/app/modules/results-overview/components/UpdateItems.jsx, akvo/rsr/spa/app/modules/results/enumerator.jsx, akvo/rsr/spa/app/modules/results/period.jsx
Login as Admin/MnE Manager and open the following projects :
=> [#4898] Fix bug: Results Indicator dates on audit trail

akvo/rest/serializers/project.py, akvo/rsr/models/project.py, akvo/rsr/tests/models/test_project.py
=> [#4901] IATI profile URL

akvo/rsr/spa/app/modules/hierarchy/card.jsx, akvo/rsr/spa/app/modules/hierarchy/hierarchy.jsx
=> [#4910] Fix bug multi selected card at hierarchy

.dockerignore, Dockerfile-e2e, README.dev.md, akvo/rsr/e2e/babel.config.js, akvo/rsr/e2e/config.js, akvo/rsr/e2e/jest-puppeteer.config.js, akvo/rsr/e2e/jest.config.js, akvo/rsr/e2e/package-lock.json, akvo/rsr/e2e/package.json, akvo/rsr/e2e/pages/BasePageObject.js, akvo/rsr/e2e/pages/LandingPage.js, akvo/rsr/e2e/pages/LoginPage.js, akvo/rsr/e2e/pages/MyProjectsPage.js, akvo/rsr/e2e/pages/ProjectEditorPage.js, akvo/rsr/e2e/pages/helpers.js, akvo/rsr/e2e/pages/index.js, akvo/rsr/e2e/scripts/wait-for-host.js, akvo/rsr/e2e/tests/create-project.test.js, akvo/rsr/e2e/tests/login.test.js, akvo/rsr/e2e/tests/smoke.test.js, akvo/rsr/management/commands/populate_e2e_data.py, ci/promote-test-to-prod.sh, scripts/devhelpers/run-e2e-linux.sh, scripts/devhelpers/run-e2e-local.sh
=> [#4721] E2E puppeteer

akvo/rsr/spa/app/modules/editor/reducer.js, akvo/rsr/spa/app/modules/project-view/project-view.jsx
Login as Project Editor eg: Janine de Laat (j.del***@aquaforall.org) and go to following projects
=> [#4914] Fix bug description field at project editor

akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx
=> [#4921] Fix blanks enumerator preview/access link

akvo/iati/checks/fields/budgets.py, akvo/iati/checks/fields/countries_and_regions.py, akvo/iati/checks/fields/results.py, akvo/iati/exports/elements/result.py, akvo/rsr/tests/iati_checks/test_iati_checks_fields_budgets.py, akvo/rsr/tests/iati_checks/test_iati_checks_fields_countries_and_regions.py, akvo/rsr/tests/iati_checks/test_iati_checks_fields_results.py, akvo/rsr/tests/iati_export/test_iati_export.py
=> [#4923] Add missing IATI validations

akvo/rsr/spa/app/modules/program/ProgramPeriod.jsx, akvo/rsr/spa/app/modules/program/ProjectSummary.jsx, akvo/rsr/spa/app/modules/program/indicator.jsx
=> [#4928] Fix qualitative indictors blank screen

akvo/rsr/views/py_reports/__init__.py, akvo/rsr/views/py_reports/project_overview_pdf_report.py, akvo/rsr/views/py_reports/utils.py, akvo/templates/reports/project-overview.css, akvo/templates/reports/project-overview.html, akvo/urls.py, scripts/deployment/pip/requirements/2_rsr.txt, scripts/deployment/pip/requirements/3_dev.txt, scripts/deployment/pip/requirements/production.in
- Open `http://localhost/py-reports/project/<project_id>/overview-report/` to download a project report
---
Closes #4937
=> 4937 project public report

akvo/rsr/spa/app/modules/editor/section7/recipient-regions/recipient-regions.jsx, akvo/rsr/spa/app/utils/final-field.jsx
=> [#4377] Fix Recipient Region blank screen

akvo/rest/serializers/__init__.py, akvo/rest/serializers/project.py, akvo/rest/urls.py, akvo/rest/views/__init__.py, akvo/rest/views/project.py, akvo/rsr/tests/rest/test_project.py
=> [#4920] Implement projects_by_id endpoint

akvo/rest/serializers/project.py, akvo/rest/views/project.py, akvo/rsr/tests/rest/test_project.py
Add required attributes on `ProjectDIrectoryDynamicFieldsSerializer`
=> [#4920] projects_by_id fields adjustments

akvo/rsr/admin.py
=> [#4960] Fix moved FieldDoesNotExist exception

akvo/rsr/spa/app/modules/project-view/project-view.jsx, akvo/rsr/spa/app/root.jsx
- Login as MnE 
- Find project id : [9604](http://localhost/my-rsr/projects/9604/results)
- Go to Enumerators tab.
- Choose any Indicator which has unlocked periods and assign to any available enumerator.
- Click eye button at the right side
=> [#4957] Hidden back button at the enumerator preview/jwt page

akvo/rsr/spa/app/modules/editor/section3/access/access.jsx
- Switch (Un)restricted
- Add new user
- Edit role user
- Remove user
=> [#4958] Fix User Access modifications are not recorded

akvo/rsr/models/project.py, akvo/rsr/tests/results_framework/test_results_framework.py
=> [#4966] Fix indicator baseline comment bug

akvo/rsr/dir/app/modules/main/index.jsx, akvo/rsr/dir/app/modules/main/sections/JumboTron.jsx, akvo/rsr/dir/app/modules/main/sections/WorksSection.jsx, akvo/rsr/dir/app/modules/project-page/ProjectPage.jsx, akvo/rsr/dir/app/styles/app.scss, akvo/rsr/dir/app/styles/home-page.scss, akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx, akvo/rsr/spa/app/modules/results-overview/ResultOverview.jsx, akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx
=> [#4764] Remove beta button at results view

akvo/rsr/dir/app/images/home-monitoring.svg, akvo/rsr/dir/app/modules/components/chart/Bar.jsx, akvo/rsr/dir/app/modules/components/chart/Dot.jsx, akvo/rsr/dir/app/modules/components/chart/LabelsXAxis.jsx, akvo/rsr/dir/app/modules/components/chart/LabelsYAxis.jsx, akvo/rsr/dir/app/modules/main/components/MapView.jsx, akvo/rsr/dir/app/modules/main/queries.js, akvo/rsr/dir/app/modules/main/sections/FooterSection.jsx, akvo/rsr/dir/app/modules/main/sections/JumboTron.jsx, akvo/rsr/dir/app/modules/main/sections/ProjectSection.jsx, akvo/rsr/dir/app/modules/main/sections/WorksSection.jsx, akvo/rsr/dir/app/modules/project-page/ProjectPage.jsx, akvo/rsr/dir/app/modules/project-page/components/SemiDoughnut.jsx, akvo/rsr/dir/app/modules/project-page/views/Home.jsx, akvo/rsr/dir/app/modules/project-page/views/ResultOverview.jsx, akvo/rsr/dir/app/modules/wcaro-index/view.scss, akvo/rsr/dir/app/styles/app.scss, akvo/rsr/dir/app/styles/home-page.scss, akvo/rsr/dir/app/styles/project-page.scss, akvo/rsr/dir/app/utils/misc.js
=> [#4764] Fix sorting by activeness and semi-doughnut chart

akvo/rsr/spa/app/modules/announcements/17-05-2022.jsx, akvo/rsr/spa/app/modules/announcements/list.js, akvo/rsr/spa/app/modules/enumerators/enumerators.jsx, akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx, akvo/rsr/spa/app/modules/results-overview/ResultOverview.jsx, akvo/rsr/spa/app/modules/results-overview/components/Indicator.jsx, akvo/rsr/spa/app/modules/results/router.jsx
These changes are based on this document:
https://docs.google.com/document/d/1-Z21499LhRUiVrpfeG6-r_08dWUromDThYXagTmK9aI/edit?usp=sharing
=> [#4242] Added new announcement: 07-05-2022

akvo/rest/views/project.py, akvo/rsr/dir/app/modules/index/filter-bar.jsx, akvo/rsr/dir/app/modules/main/sections/BlogSection.jsx, akvo/rsr/dir/app/styles/main.scss
=> [#4996] Fix bug old ui sector filter not showing

akvo/rsr/dir/app/modules/index/filter-bar.jsx
=> [#4996] Fix selected className at old ui filtering not working

akvo/rest/urls.py, akvo/rest/views/__init__.py, akvo/rest/views/program_results.py, akvo/rest/views/project_overview.py, akvo/rsr/dataclasses.py
`/rest/v1/program/<program_id>/results/`
Returns the result frameworks of the program and its contribution hierarchy
=> [#4642] Create program results endpoint

akvo/rsr/dir/app/json/features.json, akvo/rsr/dir/app/json/how-it-works.json, akvo/rsr/dir/app/modules/index/map.jsx, akvo/rsr/dir/app/modules/main/components/MapView.jsx, akvo/rsr/dir/app/modules/main/index.jsx, akvo/rsr/dir/app/modules/main/sections/ContactForm.jsx, akvo/rsr/dir/app/modules/main/sections/FooterSection.jsx, akvo/rsr/dir/app/modules/main/sections/JumboTron.jsx, akvo/rsr/dir/app/modules/main/sections/WorksSection.jsx, akvo/rsr/dir/app/modules/project-page/components/Author.jsx, akvo/rsr/dir/app/modules/project-page/views/Home.jsx, akvo/rsr/dir/app/modules/project-page/views/UpdateFeatured.jsx, akvo/rsr/dir/app/modules/project-page/views/UpdateItem.jsx, akvo/rsr/dir/app/styles/app.scss, akvo/rsr/dir/app/styles/home-page.scss, akvo/rsr/dir/app/styles/project-page.scss, akvo/rsr/dir/app/utils/config.js, akvo/rsr/dir/app/utils/string.js
=> 4987 fix project updates and org name

akvo/rsr/spa/app/modules/projects/projects.jsx, akvo/rsr/spa/app/modules/projects/styles.scss, akvo/rsr/spa/app/modules/results-admin/TobeReported.jsx, akvo/rsr/spa/app/modules/results-admin/TobeReported.scss, akvo/rsr/spa/app/modules/results-admin/components/ReportedEdit.jsx, akvo/rsr/spa/app/modules/results-overview/components/FilterBar.jsx, akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx, akvo/rsr/spa/app/modules/results/enumerator.scss, akvo/rsr/spa/app/modules/results/styles.scss, akvo/rsr/spa/app/modules/updates/styles.scss, akvo/rsr/spa/app/styles/container.scss
=> [#5003] Fix mobile view of enumerator forms

akvo/rsr/spa/app/modules/results-admin/PendingApproval.jsx, akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx, akvo/rsr/spa/app/modules/results-admin/TobeReported.jsx, akvo/rsr/spa/app/modules/results-admin/components/ReportedEdit.jsx, akvo/rsr/spa/app/modules/results-admin/components/ReportedForm.jsx, akvo/rsr/spa/app/modules/results-overview/ResultOverview.jsx, akvo/rsr/spa/app/modules/results-overview/components/Indicator.jsx, akvo/rsr/spa/app/modules/results-overview/components/UpdatePeriod.jsx, akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx, akvo/rsr/spa/app/modules/results/router.jsx, akvo/rsr/spa/app/utils/feat-flags.js
Enable entering values other than the sum of disaggregation values for NSO projects
- Edit an update with disaggregation on the _Result overview_ page
- Add/Edit an update with disaggregation on the _Result Admin > To be Reported_ page
- Edit an update with disaggregation on the Result _Admin > Pending Approval_ page
- Add/Edit an update with disaggregation on the _Enumerator_ page
- Login as NSO Admin
- Open NSO projects (e.g http://localhost/my-rsr/projects/8406)
- Total value should not be auto-calculated
- Login as Akvo Admin
- Open non-NSO projects
- Total value should be auto-calculated
---
Closes #5012
=> [#5012] Disable disaggregation auto calculation for NSO projects

akvo/rsr/spa/app/modules/announcements/HelpLinks.jsx, akvo/rsr/spa/app/modules/announcements/announcement.jsx, akvo/rsr/spa/app/modules/announcements/help-links.json, akvo/rsr/spa/app/modules/project-view/project-view.jsx, akvo/rsr/spa/app/styles/main.scss
=> [#4991] Create support links floating button

akvo/rsr/views/py_reports/utils.py, akvo/templates/reports/project-results-indicators-map-overview.html
=> [#5027] Fix project results overview report bugs

akvo/rsr/spa/app/modules/announcements/HelpLinks.jsx, akvo/rsr/spa/app/modules/announcements/announcement.jsx, akvo/rsr/spa/app/modules/enumerators/assignment-view.jsx, akvo/rsr/spa/app/styles/main.scss
=> [#5025] Fix wrong org by replacing it with the number of indicators

akvo/rest/views/project_enumerators.py, akvo/rsr/tests/rest/test_project_enumerators.py
- Login as Admin
- Open a project that is part of a program (i.e: ID=10219)
- Assign an indicator to an enumerator
- Open another project that is part of the same program as the previous project (id: ID=10203)
- Assign an indicator to the same enumerator
- Assert that the enumerator is assigned to indicators from both projects.
---
Closes #5030
=> [#5030] Fix assignment of enumerators to multiple projects

akvo/rest/views/program_results.py, akvo/rsr/dataclasses.py
Add attributes:
- indicator.target_values
- indicator.score_options
- period.target_values attributes
=> [#4642] Adjust program results endpoint

akvo/rsr/spa/app/modules/results-admin/PendingApproval.jsx, akvo/rsr/spa/app/modules/results-admin/PendingApproval.scss
=> [#5033] Improve the UI for qualitative indictor update

akvo/rsr/spa/app/modules/results-admin/PendingApproval.scss, akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx, akvo/rsr/spa/app/modules/results/enumerator.scss
=> [#5033] Add more space in update section & show description

akvo/rsr/dir/app/modules/components/RsrButton.jsx, akvo/rsr/dir/app/modules/main/index.jsx, akvo/rsr/dir/app/modules/main/sections/WorksSection.jsx, akvo/rsr/dir/app/modules/schedule-demo/ScheduleDemo.jsx, akvo/rsr/dir/app/modules/schedule-demo/index.js, akvo/rsr/dir/app/root.jsx, akvo/rsr/dir/app/styles/app.scss, akvo/rsr/dir/app/styles/buttons.scss, akvo/rsr/dir/app/styles/schedule-demo.scss, akvo/rsr/dir/app/utils/config.js, akvo/rsr/dir/package-lock.json, akvo/rsr/dir/package.json
=> [#5008] Create schedule demo form

akvo/rsr/spa/app/modules/hierarchy/column.jsx, akvo/rsr/spa/app/modules/hierarchy/hierarchy.jsx, akvo/rsr/spa/app/modules/hierarchy/styles.scss
[#4999] Add 'No results found' message at card hierarchy
=> [#4999] Fix bug program country filter gremlin

akvo/rsr/spa/app/modules/project-view/project-view.jsx
Use project http://localhost/my-rsr/projects/10180/partners as a test case
- Login as the M&E manager role, the Enumerator tab should be accessible
- Login as the Enumerator role, the Enumerator tab should not be accessible
- Login as the User role, the Enumerator tab should not be visible
- Login as the Admin role, the Enumerator tab should be visible
---
Closes #5052
=> [#5052] Modify condition to show Enumerator tab

akvo/rsr/spa/app/components/AuditTrail.jsx
1. Login as MnE manager
2. Go to project http://localhost/my-rsr/projects/9604/results
3. Find indicator title : Number of networks meetings on sustainable WASH elements
4. Open first update which is value 222,222
5. Open Audit trail panel and find any declined status, the comment should be there.
=> [#5051] Show review note if status is R in Audit trail

akvo/rsr/spa/app/modules/announcements/HelpLinks.jsx, akvo/rsr/spa/app/modules/announcements/help-links.json
You can re-validate with the existing list in this spreadsheet
https://docs.google.com/spreadsheets/d/15ix4oAmHnpDjS1UBPBlFP26ovRQtGjpVswD038iQ-bY/edit?usp=sharing
=> [#4991] Fix patname and update invalid framework guide

akvo/rsr/spa/app/modules/editor/editor.jsx, akvo/rsr/spa/app/store/root-reducer.js
- Go to project id: [2](http://localhost/my-rsr/projects/2/info)
- Edit project title
- Wait until it's saved.
- Refresh the page
=> [#5057] Fix persistence editor caused date invalid

akvo/rsr/spa/app/modules/results/router.jsx
1. Sign in with your account
2. Search project by ID : 10193
3. Click on the project and
4. should be redirected to the Results overview page
=> [#5087] Add optional chaining at results reducer state

akvo/rsr/spa/app/modules/editor/section6/section6.jsx
- Login with the MnE manager
- Open a new tab with the same browser and open this URL.
https://rsr.akvo.org/my-rsr/projects/10128/finance#/transaction/19372
- The panel will be opened according to the ID transaction from the URL
- Login with the MnE manager
- Go to project ID [6703](https://rsr.akvo.org/my-rsr/projects/6703/results)
- Move to project editor and click the [Finance section](https://rsr.akvo.org/my-rsr/projects/6703/finance)
- Play with pagination
=> [#5095] Fix transaction redirect does not load values

akvo/rsr/dir/app/index.html, akvo/rsr/dir/app/modules/project-page/components/Video.jsx, akvo/rsr/dir/app/modules/project-page/views/UpdatePage.jsx, akvo/rsr/dir/app/styles/project-page.scss, akvo/rsr/dir/app/utils/string.js
=> [#5100] Fix Project update video link issue

akvo/rsr/dir/app/modules/components/YoutubeThumb.jsx, akvo/rsr/dir/app/modules/project-page/components/Author.jsx, akvo/rsr/dir/app/modules/project-page/components/Thumbnail.jsx, akvo/rsr/dir/app/modules/project-page/components/Video.jsx, akvo/rsr/dir/app/modules/project-page/views/UpdateFeatured.jsx, akvo/rsr/dir/app/modules/project-page/views/UpdateItem.jsx, akvo/rsr/dir/app/modules/project-page/views/UpdatePage.jsx, akvo/rsr/dir/app/styles/project-page.scss, akvo/rsr/dir/app/utils/config.js, akvo/rsr/dir/app/utils/string.js, akvo/rsr/spa/app/components/Thumbnail.jsx, akvo/rsr/spa/app/modules/updates/updates.jsx
=> [#5100] Create thumbnail component

akvo/rsr/dir/app/modules/index/view.jsx, akvo/rsr/dir/app/modules/project-page/views/Home.jsx, akvo/rsr/dir/app/styles/main.scss, akvo/rsr/dir/app/styles/project-page.scss
=> 5100 youtube thumb in highlight

ci/training-envs/README.md
=> chore: Fix the training-env README

akvo/rsr/dir/app/modules/project-page/views/Results.jsx, akvo/rsr/spa/app/modules/hierarchy/column.jsx, akvo/rsr/spa/app/modules/hierarchy/hierarchy.jsx, akvo/rsr/spa/app/modules/hierarchy/styles.scss, akvo/rsr/spa/app/modules/program/indicator.jsx
=> [#4910] Fix invalid selected card and add a new contributing project func. in the project view

akvo/rsr/spa/app/modules/hierarchy/card.jsx, akvo/rsr/spa/app/modules/hierarchy/hierarchy.jsx
=> [#4910] Fix project card not clickable in the hierarchy tab

akvo/rest/urls.py, akvo/rest/views/__init__.py, akvo/rest/views/indicator_period_data.py, akvo/rsr/tests/rest/test_indicator_period_data.py, akvo/rsr/tests/usecases/test_previous_cumulative_update_by_user.py, akvo/rsr/usecases/previous_cumulative_update_by_user.py
Make an endpoint to get the previous cumulative update by the logged-in user
=> [#5076] previous cumulative update endpoint

akvo/rsr/models/project.py, akvo/rsr/models/result/disaggregation_aggregation.py, akvo/rsr/models/result/indicator.py, akvo/rsr/models/result/indicator_period.py, akvo/rsr/models/result/utils.py, akvo/rsr/tests/results_framework/test_cumulative_updates.py
=> [#5105] Ongoing cumulative indicator period value

akvo/rsr/spa/app/modules/editor/project-init-handler.js
-  [ ] Go directly by URL.
-  [ ] Passing in through My projects.
=> [#5073] Fix Project editor - description section not loading

akvo/rsr/dir/app/global-style.js, akvo/rsr/dir/app/modules/home/Home.jsx
=> [#5048] Fix project filtering not showing on partner sites

README.md, ci/deploy-semaphoreci.sh, ci/promote-test-to-prod.sh, doc/deploying.md
=> Use production branch

akvo/rsr/dir/app/modules/project-page/components/Thumbnail.jsx, akvo/rsr/dir/app/modules/project-page/views/UpdateFeatured.jsx, akvo/rsr/dir/app/modules/project-page/views/UpdateItem.jsx, akvo/rsr/dir/app/modules/project-page/views/UpdatePage.jsx, akvo/rsr/dir/app/styles/project-page.scss, akvo/rsr/dir/app/utils/misc.js
=> [#5048] Fix project page invalid multiple images

akvo/rsr/spa/app/modules/editor/project-init-handler.js
=> [#5133] Fix Project found incorrect programme

akvo/rsr/spa/app/modules/editor/project-init-handler.js
=> [#5148] Fix bug saving description of a project

akvo/rsr/spa/app/modules/editor/section5/indicators.jsx
=> [#5142] Add a cumulative option in the project editor

akvo/rsr/spa/app/components/AddUpdate.jsx, akvo/rsr/spa/app/components/LineChart.jsx, akvo/rsr/spa/app/components/PrevUpdate.jsx, akvo/rsr/spa/app/modules/results-admin/ResultAdmin.jsx, akvo/rsr/spa/app/modules/results-admin/components/QuantitativeIndicator.jsx, akvo/rsr/spa/app/modules/results-admin/components/ReportedEdit.jsx, akvo/rsr/spa/app/modules/results-admin/components/ReportedForm.jsx, akvo/rsr/spa/app/modules/results-overview/ResultOverview.scss, akvo/rsr/spa/app/modules/results-overview/components/UpdateItems.jsx, akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx, akvo/rsr/spa/app/modules/results/edit-update.jsx, akvo/rsr/spa/app/modules/results/period.jsx, akvo/rsr/spa/app/modules/results/update.jsx, akvo/rsr/spa/app/utils/constants.js, akvo/rsr/spa/app/utils/final-field.jsx, akvo/rsr/spa/app/utils/misc.js
=> [#5161] feature reporting on negative percentages

akvo/rsr/spa/app/modules/results-admin/components/ReportedForm.jsx, akvo/rsr/spa/app/utils/final-field.jsx
Go to [Total Impact / Jibu project](http://localhost/my-rsr/projects/9786/results-admin)
=> [#5161] Fix whitescreen when attempting a negative value for dsg

akvo/rsr/dataclasses.py, akvo/rsr/tests/views/py_reports/test_cumulative_updates.py, akvo/rsr/views/py_reports/eutf_org_results_table_excel_report.py, akvo/rsr/views/py_reports/program_overview_excel_report.py, akvo/rsr/views/py_reports/program_period_labels_overview_pdf_report.py, akvo/rsr/views/py_reports/project_results_indicators_excel_report.py, akvo/rsr/views/py_reports/utils.py
=> [#5129] Adjust reports to support cumulative updates feature

akvo/rsr/management/commands/switch_indicators_to_cumulative_reporting.py, akvo/rsr/tests/commands/test_switch_indicators_to_cumulative_reporting.py
=> [#5170] Implement command to switch indicator to cumulative reporting

akvo/rsr/views/py_reports/email_report.py
=> [#5187] Use correct handler for program PDF report

akvo/rest/serializers/indicator.py, akvo/rsr/spa/app/modules/results-overview/ResultOverview.jsx, akvo/rsr/views/py_reports/eutf_narrative_word_report.py, akvo/rsr/views/py_reports/kickstart_word_report.py, akvo/rsr/views/py_reports/utils.py
=> [#5194] indicator periods cumulative summary value

akvo/rsr/management/commands/report_d2d.py
This allows for the entire report to be output as file for use by non-techies
=> feat: Enhance D2D report with multisheet document output

akvo/rsr/management/commands/a4a_optimy_import.py
Django calls `timezone.make_aware(datetime, is_dst=None)` so for times that are just around daylight savings time, they will fail and we have to manually decide the time.
Fixes #5192
---
- https://app.asana.com/0/0/1203752498395495
=> A4a import script failing

akvo/rsr/spa/app/modules/project-view/project-view.jsx
=> [#5132] Add tooltip saying 'Please publish first'

akvo/rsr/spa/app/modules/enumerators/enumerators.jsx, akvo/rsr/spa/app/modules/program/program.jsx
* Create project
* Set title in Editor
* Reload in editor tab e.g [editor tab][]
* Verify that the title is the same
* Switch to [enumerator tab][]
* Switch back to [editor][editor tab]
* Change project title
* Switch [enumerator tab][]
=> Resolve : bug project title changes are reset in frontend when switching view

akvo/rest/serializers/indicator_period_data.py, akvo/rsr/spa/app/modules/results-admin/PendingApproval.jsx
=> [#5191] Show qualitative score on Pending Approval page

akvo/rsr/dataclasses.py, akvo/rsr/project_overview.py, akvo/rsr/views/py_reports/program_overview_excel_report.py, akvo/rsr/views/py_reports/program_overview_pdf_report.py, akvo/rsr/views/py_reports/utils.py, akvo/templates/reports/program-overview.html, docker-compose.override.yaml, scripts/docker/dev/50-docker-local-dev.conf
=> [#5212] Hide carried-over values for future periods on the reports

akvo/rest/views/project_overview.py, akvo/rsr/spa/app/modules/program/ActualValue.jsx, akvo/rsr/spa/app/modules/program/indicator.jsx, akvo/rsr/spa/app/modules/program/result.jsx, akvo/rsr/spa/app/modules/program/styles.scss
=> [#5211] Fix incorrect aggregated value pg overview

akvo/rsr/spa/app/modules/editor/section1/section1.jsx, akvo/rsr/spa/app/utils/misc.js
=> [#5228] Get the actual parent UUID for "contributes to" field

ci/k8s/deployment.yml
=> [#4680] fix: timings for worker container readiness and liveliness probe

akvo/rsr/models/result/utils.py, akvo/rsr/tests/results_framework/test_cumulative_updates.py, akvo/rsr/usecases/period_update_aggregation.py
=> [#5241] Fix incorrect cumulative periods aggregation values

Dockerfile-dev, Dockerfile-prod-no-code-with-nodejs, akvo/rsr/front-end/npm-shrinkwrap.json, akvo/rsr/spa/package-lock.json
=> #5255 Upgrade node to 10.24.1

akvo/urls.py
=> [#5269] Adjust IATI file URLs to accept the .xml suffix

akvo/rsr/views/py_reports/project_results_indicators_excel_report.py
=> [#5251] Adjust Results and indicators table report

akvo/rest/viewsets.py, akvo/rsr/dataclasses.py, akvo/rsr/models/result/utils.py, akvo/rsr/tests/views/py_reports/test_cumulative_updates.py, akvo/rsr/views/py_reports/program_overview_excel_report.py, akvo/rsr/views/py_reports/program_overview_pdf_report.py, akvo/rsr/views/py_reports/program_utils.py, akvo/templates/reports/program-overview.css, akvo/templates/reports/program-overview.html, akvo/urls.py
=> [#5277] Include qualitative updates in program PDF report

akvo/iati/checks/fields/budgets.py, akvo/iati/exports/elements/sector.py, akvo/rsr/tests/iati_checks/test_iati_checks_fields_budgets.py
=> [#5280] Fix IATI budget checker and sector export

akvo/rsr/spa/app/modules/hierarchy/hierarchy.jsx
- Login as MnE Manager
- Go to project ID : [7350](http://localhost/my-rsr/programs/7350)
- Move to the Hierarchy tab
- Click the cards in the following order:
1.   Orange Knowledge Programme
2.  OKP-Tailor-made-trainings
3. TMT 2019 call 2
4. TMT 2020 call 1
=> [#5208] Fix bug deep program hierarchies

akvo/rest/serializers/project.py, akvo/rsr/tests/rest/test_project.py
-----
Closes #5231 
---
- https://app.asana.com/0/0/1204682486384210
=> [#5231] Fix contributes to field updates parent project

akvo/rsr/dataclasses.py, akvo/rsr/views/py_reports/program_overview_excel_report.py, akvo/rsr/views/py_reports/program_utils.py
=> [#4861] Add narrative column on program overview excel report

akvo/rsr/spa/app/components/StatusIndicator.jsx, akvo/rsr/spa/app/modules/results-admin/TobeReported.jsx, akvo/rsr/spa/app/modules/results-admin/TobeReported.scss, akvo/rsr/spa/app/modules/results-admin/components/PeriodTitle.jsx, akvo/rsr/spa/app/modules/results-admin/components/SubmissionsModal.jsx, akvo/rsr/spa/app/utils/constants.js
---
Related to #5080 
---
- https://app.asana.com/0/0/1204682486804306
=> [#5080] Implement indicator approval workflow

akvo/rsr/dataclasses.py, akvo/rsr/views/py_reports/program_overview_excel_report.py, akvo/rsr/views/py_reports/program_utils.py
---
Closes #5293 
---
- https://app.asana.com/0/0/1204952910383467
=> [#5293] Add actual comment on program_overview_excel_report

akvo/rsr/spa/app/modules/program/result.jsx, akvo/rsr/spa/app/modules/program/styles.scss
---
- https://app.asana.com/0/0/1205121015665348
=> Add cumulative flag on program overview

akvo/settings/80-sentry.conf
=> Enable Sentry's performance monitoring

akvo/settings/80-sentry.conf
=> Enable Sentry's profiling

doc/components/index.md, doc/components/projects.md, doc/components/report_generation.md, doc/report_generation.md
---
- https://app.asana.com/0/0/1205121015665352
=> Document report generation

akvo/settings/80-sentry.conf, scripts/deployment/pip/requirements/2_rsr.txt, scripts/deployment/pip/requirements/3_dev.txt, scripts/deployment/pip/requirements/production.in
=> Enable sentry profiling

.gitignore, .semaphore/semaphore.yml, Dockerfile-dbdocs, Makefile, akvo/settings/10-base.conf, ci/build-semaphoreci.sh, doc/index.md, doc/references.md, docker-compose.ci.prod.images.yaml, scripts/deployment/pip/requirements/2_rsr.txt, scripts/deployment/pip/requirements/3_dev.txt, scripts/deployment/pip/requirements/production.in, scripts/docker/ci/build.sh
---
- https://app.asana.com/0/0/1205628188792526
- https://app.asana.com/0/0/1205628188792528
=> Generate dbml file and push it to dbdocs.io

doc/conf.py, scripts/deployment/pip/requirements/3_dev.txt, scripts/deployment/pip/requirements/dev.in
---
- https://app.asana.com/0/0/1205628188792529
=> Use rtd_theme for the sphinx doc

akvo/rsr/tests/views/py_reports/test_send_report_via_email.py, akvo/rsr/views/py_reports/__init__.py, akvo/rsr/views/py_reports/organisation_data_quality_overview_report.py, akvo/rsr/views/py_reports/organisation_projects_overview_report.py, akvo/rsr/views/py_reports/results_indicators_excel_report.py
---
- https://app.asana.com/0/0/1205859329328343
=> Use background jobs to generate Org level reports

akvo/rest/views/user.py, akvo/rsr/spa/app/components/StatusIndicator.jsx, akvo/rsr/spa/app/modules/results-overview/components/FilterBar.jsx, akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx, akvo/rsr/spa/app/root.jsx
- Last submission date attribute
- Hide approved submissions filter
---
- https://app.asana.com/0/0/1205657783099581
=> Implement new feature on Enumerator form

akvo/rsr/spa/app/modules/results/EnumeratorPage.jsx
---
- https://app.asana.com/0/0/1205881735162193
=> Implement enumerator submission modal list

akvo/rsr/views/account.py, akvo/templates/two_factor/core/setup.html, akvo/templates/two_factor/profile/disable.html, akvo/urls.py
---
- https://app.asana.com/0/0/1206691331458605
- https://app.asana.com/0/0/1206691331458602
=> 2FA Enforcement Adjustment

akvo/rest/serializers/project.py, akvo/utils/__init__.py
---
- https://app.asana.com/0/0/1207052333728467
=> Work around for invalid project.created_at timezone

akvo/rest/serializers/project.py, akvo/rsr/models/project.py, akvo/rsr/models/project_update.py, akvo/rsr/tests/commands/test_cleanup_untitled_and_unpublished_projects.py
---
- https://app.asana.com/0/0/1207412234826583
=> Fix AmbiguousTimeError caused by invalid project.created_at date

akvo/rsr/spa/app/modules/editor/project-init-handler.js, akvo/rsr/spa/app/modules/editor/section5/indicators.jsx, akvo/rsr/spa/app/modules/editor/section5/section5.jsx
---
- https://app.asana.com/0/0/1208219705766289
=> Fix bug in project editor section 5
