akvo/rsr/admin.py, akvo/rsr/migrations/0076_auto__add_projectdocument__del_field_link_category__del_field_link_lan.py, akvo/rsr/models/__init__.py, akvo/rsr/models/link.py, akvo/rsr/models/project_document.py, akvo/rsr/static/rsr/v3/css/src/main.css, akvo/rsr/static/rsr/v3/css/src/main.scss, akvo/templates/navigation/footer.html, akvo/templates/partials/project_footer.html, akvo/templates/project_main.html
- Added a footer section to the project main page, containing:
- Documents (new model)
- Links
- Grab a widget (to be implemented)
- RSS feed (to be implemented)
=> [#942] Added footer to project main page

akvo/rsr/migrations/0064_auto__add_field_project_last_update.py, akvo/rsr/migrations/0065_denormalize_project_last_update.py, akvo/rsr/models/project.py, akvo/rsr/models/project_update.py, akvo/rsr/views.py, akvo/templates/rsr/project/project_directory.html
The main project list is now using this.
=> [#1015] Adds denormalised last_update field on project

akvo/rsr/views.py, akvo/rsr/views_partner_sites/base.py, akvo/rsr/views_partner_sites/widgets.py, akvo/templates/partner_sites/home.html, akvo/templates/partner_sites/widgets/project_list.html, akvo/templates/widgets/project_list.html
=> [#1015] Extended usage of project.last_update

akvo/rsr/models/project.py, akvo/templates/project_finance.html
@loicsans This probably needs some additional styling, but it has live data now
=> [#1031] Financial page

akvo/rsr/context_processors.py, akvo/rsr/models/partner_site.py, akvo/templates/base.html, akvo/templates/partials/project_header.html
Note: Facebook share texts won't work locally since sharer.php scrapes the content online from the meta tags. But it should work on the redesign environment.
=> [#947] Added social media buttons to project header

akvo/rest/views/country.py, akvo/rest/views/employment.py, akvo/rsr/backends.py, akvo/rsr/models/__init__.py, akvo/rsr/models/employment.py, akvo/rsr/models/project.py, akvo/rsr/permissions.py, akvo/rsr/signals.py, akvo/rsr/static/rsr/v3/js/src/my-details.js, akvo/rsr/static/rsr/v3/js/src/react-my-details.js, akvo/rsr/static/rsr/v3/js/src/react-my-details.jsx, akvo/rsr/static/rsr/v3/js/src/react-user-management.js, akvo/rsr/static/rsr/v3/js/src/react-user-management.jsx, akvo/rsr/views/account.py, akvo/rsr/views/my_rsr.py, akvo/templates/myrsr/my_details.html, akvo/templates/myrsr/my_projects.html, akvo/templates/myrsr/user_management.html, akvo/templates/registration/activation_email_subject.txt, akvo/templates/registration/approved_email_message.txt, akvo/templates/registration/approved_email_subject.txt, akvo/templates/registration/password_reset_subject.txt, akvo/templates/registration/user_organisation_request_subject.txt
=> [#1078] User process

akvo/templates/base.html, akvo/templates/widgets/base.html, akvo/templates/widgets/projects_map.html
* Move Piwik code to the bottom of the page
* Use protocol relative URL when including 3rd party libs
=> [#1101] Small HTML code improvements

akvo/rsr/static/rsr/v3/js/src/my-details.js, akvo/rsr/static/rsr/v3/js/src/scripts.js, akvo/templates/base.html
* `-` is not allowed in JS identifiers, we need to use array notation to
access that member
=> [#1105] Fix regression introduced in code cleanup

akvo/rsr/static/rsr/v3/css/src/main.css, akvo/rsr/static/rsr/v3/css/src/main.scss, akvo/templates/base.html, akvo/templates/partials/project_budget.html
Added version banner at the bottom though
Fixes for Project directory UI
=> [#986][#1050] Remove financial details

akvo/settings/40-pipeline.conf
Realised that the duplicate paths were unused so killed some more unused stuff.
=> 1109 duplicate paths

akvo/templates/navigation/footer.html
Waiting monday confirmation of email for feddback
=> [#1049][#1111] Provide feedback + API link

akvo/rsr/static/rsr/v3/css/src/library.scss, akvo/rsr/static/rsr/v3/css/src/main.css, akvo/rsr/static/rsr/v3/css/src/main.scss, akvo/templates/myrsr/my_projects.html, akvo/templates/myrsr/my_updates.html, akvo/templates/navigation/pagination.html, akvo/templates/organisation_directory.html, akvo/templates/update_add.html, akvo/templates/update_directory.html
Fix Map on mobile
Fix update component, on add update page
Fix paging padding in myrsr
=> [#1150] UI issues

vagrant/provisioning/load_test_db.sh
Since the one without the codelist app broke.
=> [#1187] New data set!

RELEASE_NOTES.md
Release notes are in and I think are ready to be merged.
=> #1183 release notes

akvo/rsr/filters.py, akvo/templates/organisation_directory.html, akvo/templates/update_directory.html
- Changed partner filter on updates
- Updated html syntax to make the form element close over form elements
in the advanced filter.
=> [#1226] Filters on update and orgs updated

akvo/api/resources/__init__.py, akvo/api/resources/project_update.py
- Added missing resource
- Updated call for org
=> [#1252] Fixed broken API endpoint

akvo/rsr/static/rsr/v3/css/src/main.css, akvo/rsr/static/rsr/v3/css/src/main.scss, akvo/templates/partials/project_budget.html, akvo/templates/project_directory.html, akvo/templates/project_finance.html
@gabemart (or @loicsans) Could you update the alignments on the finance page? The amounts are now all aligned to the left, but should be aligned to the right so that they're easier to compare.
=> [#1292] Update finance page

akvo/rsr/admin.py, akvo/rsr/migrations/0088_auto__add_field_user_is_support.py, akvo/rsr/models/user.py, akvo/rsr/signals.py, akvo/rsr/views/my_rsr.py, akvo/templates/myrsr/user_management.html
- Added support role for Users
- Updated user management page:
- Pagination
- Support (RSR) users can view and edit all users
- Updated to whom we send emails when a user requests to join an organisation
=> [#1042] New user process

scripts/deployment/pip/requirements/2_rsr.txt
- #1010 Upgrade PIL to 2.7.0
- #1011 Upgrade Django to 1.6.10
=> [#1010 #1011] Upgrade Django and PIL

DEVELOPMENT.md
- Added links to the Node.js and Gulp.js sits.
- Removed duplicate slash
[#1227]
=> [#1227] Updated get started with dev docs

RELEASE_NOTES.md
=> #1353 release notes

akvo/rsr/static/rsr/v3/css/src/main.css, akvo/rsr/static/rsr/v3/css/src/main.scss, akvo/templates/project_main.html
[#1358]
Add partner logos to project page tooltip. Each partner logo links to organisation page.
=> 1358 partner tooltip

akvo/rsr/static/rsr/v3/css/src/main.css, akvo/rsr/static/rsr/v3/css/src/main.scss, akvo/rsr/views/project.py, akvo/templates/project_main.html, akvo/templates/project_partners.html, akvo/urls.py
=> [#1358] Add partner subpage to project page

akvo/templates/organisation_main.html
=> [#1286] Project currency

akvo/rest/fields.py, akvo/rest/serializers/__init__.py, akvo/rest/serializers/project.py, akvo/rest/urls.py, akvo/rest/views/__init__.py, akvo/rest/views/project.py
Note that the main new functionality, being able to include a specification for a thumbnail in an API GET, is generic, i.e. it works for all models where we have an image: Project, ProjectUpdate and Organisation.
=> 1384 project rest endpoint for up

.gitignore, akvo/templates/myrsr/my_projects.html
=> [#1410] fixed Firefox responsive bug

akvo/rsr/models/organisation.py, akvo/rsr/models/user.py, akvo/rsr/views/my_rsr.py, akvo/templates/myrsr/my_projects.html, akvo/templates/myrsr/my_updates.html, akvo/templates/myrsr/user_management.html
- Remove users without employment from user management
- Add search field to user management page
=> [#1398] Improve user management

akvo/templates/myrsr/my_projects.html, akvo/templates/myrsr/my_updates.html
This branch is based on the #1398 branch (user management improvement), so that one should be merged in first.
=> [#1413] Make links of my projects and updates titles

akvo/templates/inclusion_tags/map.html, akvo/utils.py
- Encode utf-8 for query strings
- Update maps with correct encoding
=> [#1284] Fix encoding issues

akvo/templates/project_directory.html
@gabemart I've added the latest update date on the project list, could you take a look if it makes sense to you to place it like this:
=> [#1281] Last update in project list

akvo/rsr/static/scripts-src/password-reset.js, akvo/rsr/static/scripts-src/password-reset.jsx, akvo/rsr/views/account.py
The /sign_in/ resource for password reset cause a 500 error.
=> 1453 password reset

akvo/api/resources/project.py, akvo/rsr/iso3166.py, akvo/scripts/cordaid/organisation_upload.py, akvo/scripts/cordaid/post_import.py, akvo/scripts/rain/organisation_upload.py, akvo/scripts/rain/post_import.py, akvo/scripts/rvo/__init__.py, akvo/scripts/rvo/post_import.py, akvo/scripts/rvo/rvo_project_upload.py
No need to check thoroughly. The RVO script will only be used on Test, so that they can see what an eventual Akvo Page for RVO would look like if we would import their IATI data.
=> [#1378 #1452] Add RVO import scripts and fix existing import scripts

akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/templates/organisation_main.html
=> [#1375] organisation page responsive design improvements

.gitignore, akvo/rsr/admin.py, data/simple-load.sh
=> #1519 admin search

akvo/templates/project_directory.html
=> [#1474] add partner page link to project directory

akvo/rsr/models/user.py, akvo/rsr/permissions.py, akvo/rsr/static/scripts-src/my-user-management.js, akvo/rsr/static/scripts-src/my-user-management.jsx, akvo/rsr/views/my_rsr.py, akvo/templates/myrsr/user_management.html
=> [#1499] User management performance

akvo/rsr/models/project.py
=> [#1533] Remove pending donations from calculated funds of project

akvo/templates/partials/project_budget.html
=> [#1507] Added 'funds needed' to project list

akvo/rsr/views/widgets.py
Since there is multiple problems in #1559 this is a first PR.
=> #1559 list widget

akvo/rsr/static/scripts-src/project-main.js, akvo/rsr/static/scripts-src/project-main.jsx, akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss
=> [#1572] Open first accordion item and add visual indicator

akvo/rsr/views/widgets.py, akvo/templates/widgets/project_list.html
Temporary fix until we do pagination.
=> #1559 list widget limit

akvo/rsr/admin.py
The odd use case is still slow :-(
=> #1559 admin project directory

akvo/templates/registration/approved_email_message.txt, akvo/templates/registration/approved_email_subject.txt, akvo/templates/registration/register_complete.html, akvo/templates/registration/user_organisation_request_message.txt, akvo/templates/registration/user_organisation_request_subject.txt
=> [#1564] Registration mails

akvo/iati/checks/v201.py, akvo/rest/urls.py, akvo/rest/views/__init__.py, akvo/rest/views/project_iati_checks.py, akvo/rsr/forms.py, akvo/rsr/static/scripts-src/my-details-employments.js, akvo/rsr/static/scripts-src/my-details-employments.jsx, akvo/rsr/static/scripts-src/my-iati.js, akvo/rsr/static/scripts-src/my-iati.jsx, akvo/rsr/static/scripts-src/my-user-management.js, akvo/rsr/static/scripts-src/my-user-management.jsx, akvo/rsr/static/scripts-src/password-reset.js, akvo/rsr/static/scripts-src/password-reset.jsx, akvo/rsr/static/scripts-src/project-main.js, akvo/rsr/static/scripts-src/project-main.jsx, akvo/settings/40-pipeline.conf, akvo/templates/myrsr/my_iati.html
=> [#1447] IATI export performance

akvo/rsr/admin.py, akvo/rsr/migrations/0008_organisation_can_become_reporting.py, akvo/rsr/migrations/0009_auto_20150528_1413.py, akvo/rsr/models/organisation.py, akvo/rsr/models/project.py, akvo/rsr/views/organisation.py
=> #1341 partner types

akvo/rest/views/organisation.py
=> [#1593] Add content_owner filter for organisation API

akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss
fixes the language-dropdown portion of #1596
=> [#1596] fix language dropdown on narrow viewports

akvo/rsr/models/transaction.py
=> [#1602] Changed the unicode of a Transaction to Unicode

akvo/rsr/views/organisation.py, akvo/rsr/views/project.py, akvo/rsr/views/project_update.py
=> [#1600] Hotfix for displaying the correct orgs and updates on Akvo Pages

akvo/rsr/models/__init__.py
=> [#1604] Set correct permissions for indicator (period)

akvo/rsr/admin.py, akvo/rsr/migrations/0010_auto_20150615_1149.py, akvo/rsr/models/keyword.py, akvo/rsr/models/project.py, akvo/rsr/templatetags/rsr_utils.py, akvo/templates/partials/project_header.html
=> [#1616] Consortium projects

akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/rsr/views/project.py, akvo/templates/myrsr/my_iati.html, akvo/templates/organisation_directory.html, akvo/templates/project_directory.html, akvo/templates/project_finance.html, akvo/templates/project_main.html, akvo/templates/project_report.html, akvo/templates/update_directory.html, akvo/templates/update_main.html
Resolves most of the issues in #1615. 
Exceptions are budget item start and end dates, and showing previous budgets
=> [#1615] Small user interface enhancements

akvo/rsr/admin.py, akvo/rsr/middleware.py, akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/settings/10-base.conf, akvo/templates/base.html, akvo/templates/navigation/header.html
Test plan:
With the minimal test dataset & the following entry to /etc/hosts (local host computer)
192.168.50.101 gooddeeds.localakvoapp.org
The Good deeds RSR page should be visible at [gooddeeds.localakvoapp.org](http://gooddeeds.localakvoapp.org)
If one enable the Google translate bar in the admin and then RSR should display a Google dropdown top right.
=> #1617 google translate

akvo/iati/checks/v201.py, akvo/iati/elements/document_link.py, akvo/iati/elements/reporting_org.py, akvo/iati/elements/sector.py, akvo/rsr/forms.py, akvo/rsr/static/scripts-src/my-iati.js, akvo/rsr/static/scripts-src/my-iati.jsx, akvo/templates/myrsr/my_iati.html
=> [#1618] Improve IATI export

akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/templates/navigation/header.html
=> [#1617] google translate CSS tweaks

akvo/rsr/migrations/0015_auto_20150722_1519.py, akvo/rsr/models/partnership.py, akvo/templates/inclusion_tags/more_partners.html, akvo/templates/myrsr/project_admin.html, akvo/templates/myrsr/project_admin_partials/partner_input.html, akvo/templates/myrsr/project_admin_partials/related_project_input.html, akvo/templates/project_partners.html
[fixes #1633] IATI partner types
=> [fixes #1633] IATI partner types

akvo/rest/views/project_admin.py, akvo/rsr/migrations/0016_auto_20150723_0930.py, akvo/rsr/models/budget_item.py, akvo/rsr/models/project.py, akvo/rsr/static/scripts-src/myrsr-admin.js, akvo/rsr/static/scripts-src/myrsr-admin.jsx, akvo/templates/myrsr/project_admin.html, akvo/templates/myrsr/project_admin_partials/budget_item_input.html, akvo/templates/project_finance.html
[fixes #1640] Improved budget section
=> [fixes #1640] Improved budget section

akvo/templates/inclusion_tags/more_partners.html
=> [Fixes #1667] Fixed '+more' organisation logo styling

akvo/rsr/forms.py, akvo/rsr/migrations/0013_auto_20150803_0905.py, akvo/rsr/models/project_update.py
=> [Fixes #1682] Increase photo and video credit to 75 chars

akvo/rsr/models/__init__.py
[Fixes #1699] Allow organisation Admin and User Managers to delete employments
=> [Fixes #1699] Allow to delete employments

akvo/rsr/models/__init__.py, akvo/rsr/permissions.py
[Fixes #1700] Set correct permissions for adding and deleting organisations
=> [Fixes #1700] Set correct permissions for organisations

akvo/rsr/forms.py, akvo/rsr/migrations/0013_auto_20150803_0905.py, akvo/rsr/migrations/0014_auto_20150803_1017.py, akvo/rsr/models/organisation.py, akvo/rsr/models/project_update.py
[Fixes #1406] Make organisation names unique
Note: has a dependancy on the migration of #1682.
=> [Fixes #1406] Make organisation names unique

akvo/rsr/views/project.py, akvo/templates/project_partners.html
=> [Fixes #1674] Fix organisation logos on the project partner page

akvo/rsr/migrations/0001_initial.py
Fixes #1733; Remove constraint from initial migration
=> [Fixes #1733] Remove constraint from initial migration

akvo/rsr/admin.py, akvo/rsr/migrations/0022_auto_20150819_0801.py, akvo/rsr/migrations/0022_auto_20150819_0908.py, akvo/rsr/models/custom_field.py, akvo/rsr/static/scripts-src/myrsr-admin.js, akvo/rsr/static/scripts-src/myrsr-admin.jsx, akvo/rsr/views/my_rsr.py, akvo/templates/myrsr/my_projects.html, akvo/templates/myrsr/project_editor.html
- Add sorting for custom fields (customfield.order)
- Add type for custom fields (customfield.type)
- 'Text' will display a textbox in the project editor
- 'Checkbox' will display a checkbox in the project editor
=> [Fixes #1738] Custom fields extra

akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/templates/myrsr/my_projects.html, akvo/templates/navigation/header.html
Fixes #1571
@zzgvh Looks good to me, can you check? I've also removed the 'View' and 'Publish' buttons from My Projects. View is done by clicking on the image or project title anyway, and publish can be done through the project editor, which should be used for publishing projects now.
=> [Fixes #1571] Don't update unpublished

akvo/rest/views/project_editor.py, akvo/rsr/migrations/0023_auto_20150821_1020.py, akvo/rsr/migrations/0023_auto_20150821_1145.py, akvo/rsr/models/budget_item.py, akvo/rsr/models/related_project.py, akvo/rsr/static/scripts-src/myrsr-admin.js, akvo/rsr/static/scripts-src/myrsr-admin.jsx, akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/templates/myrsr/project_editor.html, akvo/templates/myrsr/project_editor_partials/document_input.html, akvo/templates/myrsr/project_editor_partials/related_project_input.html
=> [Fixes #1759] Final editor feedback

akvo/rsr/models/sector.py
=> [Fixes #1762] Remove sector vocabulary signal

akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/templates/project_main.html
=> [Fixes #1514] Project dates on project main page

akvo/rsr/views/my_rsr.py, akvo/templates/myrsr/user_management.html
=> [Fixes #1560] Fix pagination on user management page

akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/templates/project_finance.html
=> [Fixes #1659] Added IATI activity ID of budgets to finance page

akvo/iati/checks/v201.py, akvo/iati/elements/participating_org.py
Fixes #1749 
- Change disbursement.amount to disbursement.value
=> [Fixes #1749] IATI check bug

akvo/rsr/static/scripts-src/myrsr-admin.js, akvo/rsr/static/scripts-src/myrsr-admin.jsx
=> [#1764] stop info icon event propagation

akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/templates/myrsr/project_editor.html
=> [#1776] fix publish project button alignment

akvo/rest/views/project_editor.py, akvo/rsr/static/scripts-src/myrsr-admin.js, akvo/rsr/static/scripts-src/myrsr-admin.jsx, akvo/templates/myrsr/project_editor.html
=> [#1788] Small project editor bugs

akvo/rsr/static/scripts-src/myrsr-admin.js, akvo/rsr/static/scripts-src/myrsr-admin.jsx, akvo/templates/myrsr/project_editor.html
=> [#1765] remove zepto dependency from project editor

akvo/rsr/static/scripts-src/rsr.js, akvo/rsr/templatetags/rsr_tags.py, akvo/templates/inclusion_tags/more_partners.html, akvo/templates/project_directory.html, akvo/templates/project_main.html
We exclude Project.reporting_org() org from the partners list to
get counting & display correct. The problem was that a project could
have a reporting org and then a partner that was another org.
=> [#1793] Fix +1 links corner case

akvo/rsr/static/scripts-src/myrsr-admin.js, akvo/rsr/static/scripts-src/myrsr-admin.jsx
=> [#1791] use setTimeout so save clicks propagate

akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss
=> [#1722] display update bullet points correctly

akvo/templates/base.html, akvo/templates/navigation/header.html
=> [#1796] Hide navbar padding until widget clicked

akvo/rsr/static/scripts-src/rsr.js, akvo/templates/inclusion_tags/maps.html
=> [#1251] Close existing infoWindows before opening new one

akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/templates/project_finance.html
=> [#1771] Add budget period to project finance page

akvo/rest/serializers/typeahead.py, akvo/rest/views/typeahead.py, akvo/rsr/static/scripts-src/myrsr-admin.js, akvo/rsr/static/scripts-src/myrsr-admin.jsx
=> [#1751] add filtering on ID for project typeaheads

akvo/rsr/migrations/0032_auto_20151001_0956.py
Fixes #1770 
Small addition to the migrations.
=> [#1770] Fix migration

akvo/templates/myrsr/project_editor.html
=> [#1832] Allow anyone to link keywords in project editor

akvo/rsr/views/my_rsr.py
=> [#1799] Show all projects in MyRSR for superusers or RSR admins

akvo/rsr/static/scripts-src/my-projects.js, akvo/rsr/views/my_rsr.py, akvo/templates/myrsr/my_projects.html
=> [#1817] Fix multiple employments in My projects issue

akvo/rsr/views/my_rsr.py
=> [#1777] Add organisation name to user management search

akvo/rest/views/project.py
=> [#1827] Added publishing status as filter and updated docs

akvo/rsr/admin.py, akvo/rsr/models/organisation.py, akvo/rsr/permissions.py, akvo/rsr/views/my_rsr.py
=> [#795] Organisation content_owner permissions

akvo/rsr/management/__init__.py, akvo/rsr/management/commands/__init__.py, akvo/rsr/management/commands/merge_keywords.py
Fixes #1825
This management command merges and removes a number of keywords, most
associated with the Walking for Water projects.
=> [#1825] Management command removing duplicate keywords

akvo/rsr/filters.py, akvo/rsr/static/scripts-src/organisation-directory.js, akvo/rsr/static/scripts-src/update-directory.js, akvo/rsr/views/organisation.py, akvo/rsr/views/project.py, akvo/rsr/views/project_update.py, akvo/templates/organisation_directory.html, akvo/templates/project_directory.html, akvo/templates/update_directory.html
Fixes #1515
Could be extended to use MultipleChoice filters on locations, but UI get's a bit tight.
=> [#1515] Filters on listing pages

akvo/rest/urls.py, akvo/rest/views/__init__.py, akvo/rest/views/project_editor.py, akvo/rsr/models/organisation.py, akvo/rsr/static/scripts-src/myrsr-admin.js, akvo/rsr/static/scripts-src/myrsr-admin.jsx, akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/templates/myrsr/project_editor.html
=> [#1746] Improvement of the 'Add organisation' functionality

akvo/rest/views/project_update.py, akvo/rsr/migrations/0035_auto_20151008_0939.py, akvo/rsr/models/project_update.py, akvo/templates/project_main.html
After merging, run ```sh manage.sh migrate rsr``` in the devhelpers folder.
=> [#1772] Add indicator fields to ProjectUpdate model

akvo/settings/10-base.conf
=> [#1860] Remove SEND_BROKEN_LINK_EMAILS setting

akvo/rsr/models/partner_site.py
=> [#1500] Always make hostnames of an Akvo Page lowercase

akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/templates/organisation_directory.html, akvo/templates/project_directory.html, akvo/templates/update_directory.html
=> [#1288] Add map explanation

akvo/rsr/models/organisation.py
=> [#1859] Exclude self from organisation validation checks

akvo/rsr/static/scripts-src/myrsr-admin.js, akvo/rsr/static/scripts-src/project-main.js, akvo/rsr/static/scripts-src/project-main.jsx, akvo/rsr/views/project.py
=> [#1868] Fix AnonymousUser bug and JS crash when no descriptions

akvo/rest/views/project_editor.py, akvo/templates/myrsr/project_editor.html
=> [#1866] Fix empty IATI ID in project editor

akvo/iati/checks/versions/v201.py
=> [#1851] Additional IATI checks

akvo/rsr/models/project.py, akvo/rsr/templatetags/maps.py
=> [#1849] Fix project main map unicoding

akvo/rsr/models/employment.py
=> [#1069] Fix Auth groups

akvo/rsr/models/partnership.py
=> [#1874] Fix reporting org validation

akvo/rest/views/project_editor.py
=> [#1881] Fix aggregation status and ascending in project editor

akvo/templates/project_main_tabs/report.html
=> [#1880] Several full data report changes

akvo/rsr/models/project_update.py, akvo/rsr/static/scripts-src/project-main.js, akvo/rsr/static/scripts-src/project-main.jsx, akvo/templates/project_main_tabs/results.html
=> [#1877] Calculate sliders from start of period

akvo/rsr/static/scripts-src/project-main.js, akvo/rsr/static/scripts-src/project-main.jsx, akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/templates/project_main.html
=> [#1887] Add confirmation dialog for deleting updates in results framework

akvo/rsr/views/project.py
=> [#1892] Only show first 5 updates on summary page

akvo/rsr/models/indicator.py
=> [#1889] Editing or adding updates to previous periods

akvo/templates/project_main_tabs/results.html
=> [#1831] Add PDF report

akvo/rsr/models/organisation.py
Fixes #1903
Fix an AttributeError when adding or changing Organisation.iati_org_id.
=> [#1903] Fix validation of iati_org_id

akvo/templates/project_main_tabs/partners.html
=> [#1911] Fixed parter logos

akvo/templates/project_main.html
=> [#1908] Added project footer

akvo/rest/views/project.py
=> [#1909] Make project querysets in REST API distinct

akvo/rsr/models/project.py
=> [#1914] Fixed empty IATI activity IDs

akvo/rsr/models/partnership.py, akvo/templates/project_main_tabs/report.html
=> [#1901] Fix full data report when partnership has no role

akvo/rsr/models/project_condition.py
=> [#1919] Fix for rsr_projectcondition.__unicode__() for empty text

akvo/rsr/admin.py, akvo/rsr/models/organisation.py
=> [#1922] Refactor UserAdmin.get_queryset()

akvo/rsr/static/scripts-src/project-main.js, akvo/rsr/static/scripts-src/project-main.jsx
=> [#1924] Update results and indicators descriptions on summary tab

akvo/templates/myrsr/project_editor.html, akvo/templates/navigation/footer.html
=> [#1891] Change support email address in footer and project editor

akvo/rsr/views/widgets.py, akvo/templates/project_widgets.html, akvo/templates/project_widgets2.html
=> [#1923] Widgets fix for projects without reporting org

akvo/rsr/migrations/0042_auto_20153011_1450.py, akvo/rsr/models/project.py
=> [#1936] Change order for primary organisations; reporting org first

akvo/rest/views/project.py
=> [#1939] Fix project Up REST resource

akvo/rsr/views/organisation.py, akvo/templates/organisation_directory.html
=> [#1940] Fix organisations list performance

akvo/rest/viewsets.py
=> [#1944] Remove filtering for public projects in API

akvo/iati/exports/elements/participating_org.py
=> [#1947] Do not include reporting org or sponsor partners in the export

akvo/rest/views/user.py, akvo/rsr/models/__init__.py, akvo/rsr/permissions.py, akvo/rsr/static/lib/scripts/react-typeahead-1.1.5.js, akvo/rsr/static/scripts-src/my-details-employments.js, akvo/rsr/static/scripts-src/my-details-employments.jsx, akvo/settings/40-pipeline.conf, akvo/templates/myrsr/my_details.html
=> [#1510 #1778] Refactor 'Connect to employer'

akvo/rsr/models/project.py, akvo/rsr/static/scripts-src/my-projects.js, akvo/settings/20-default.conf
=> [#1959] Delete projects bug

akvo/rsr/reports.py, akvo/rsr/static/lib/scripts/react-typeahead-1.1.5.js, akvo/rsr/static/scripts-src/my-reports.js, akvo/rsr/static/scripts-src/my-reports.jsx, akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/rsr/views/my_rsr.py, akvo/settings/40-pipeline.conf, akvo/templates/myrsr/my_reports.html, akvo/templates/myrsr/myrsr_base.html, akvo/urls.py
Fixes #1960. Since the whole 'My reports' page is React.js, assigned @gabemart to this PR. @zzgvh feel free to have a look though :).
=> [#1960] My reports section in MyRSR

akvo/rsr/views/my_rsr.py
=> [#1828] Make project and organisation names unicode

akvo/rsr/static/scripts-src/project-main.js, akvo/rsr/static/scripts-src/project-main.jsx
=> [#1953] Always show indicator period values

akvo/rsr/models/project.py
=> [#1971] Catch multiple reporting organisations scenario

akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/templates/partials/project_header.html
=> [#1855] Style project page logos for Akvo Pages

akvo/rsr/migrations/0048_auto_20160119_1347.py, akvo/rsr/models/budget_item.py, akvo/rsr/models/indicator.py, akvo/rsr/models/organisation.py, akvo/rsr/models/partnership.py, akvo/rsr/models/policy_marker.py, akvo/rsr/models/project.py, akvo/rsr/models/region.py, akvo/rsr/models/result.py, akvo/rsr/models/sector.py, akvo/rsr/models/transaction.py, akvo/rsr/static/scripts-src/project-main.js, akvo/rsr/static/scripts-src/project-main.jsx, akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/templates/partials/project_header.html, akvo/templates/project_main_tabs/summary.html
=> [#1948] Increase character limits

akvo/rest/views/project_update.py
=> [#2014] Remove old results framework fields in REST API

akvo/templates/navigation/footer.html
=> [#2016] Change support link in RSR's footer

akvo/rsr/static/scripts-src/my-change-password.js, akvo/rsr/static/scripts-src/my-details-employments.js, akvo/rsr/static/scripts-src/my-details-employments.jsx, akvo/settings/20-default.conf, akvo/templates/base.html, akvo/templates/myrsr/my_details.html
=> [Fixes #2013] Change Piwik URL, and remove ReactBootstrap partly

akvo/settings/20-default.conf
=> [#2013] Set Piwik URL to https by default

akvo/rsr/static/scripts-src/my-user-management.js, akvo/rsr/static/scripts-src/my-user-management.jsx, akvo/rsr/static/scripts-src/password-reset.js, akvo/rsr/static/scripts-src/password-reset.jsx, akvo/rsr/static/scripts-src/project-main.js, akvo/rsr/static/scripts-src/project-main.jsx, akvo/templates/project_main.html, akvo/templates/project_main_tabs/finance.html, akvo/templates/project_main_tabs/partners.html, akvo/templates/project_main_tabs/report.html, akvo/templates/project_main_tabs/updates.html
=> [#2020] React bootstrap fixes

akvo/rsr/admin.py
=> [#2026] Remove old results framework fields from admin

akvo/rsr/static/scripts-src/project-main.js, akvo/rsr/static/scripts-src/project-main.jsx, akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss
=> [#2041] Fix accordion on project page

akvo/templates/inclusion_tags/more_partners.html
=> [#2051] Handle partnerships with no organisation

akvo/rsr/views/project.py
=> [#2057] Fix tests in case of non-existent or multiple IATI versions

akvo/rsr/models/partnership.py
=> [#2059] Make sure iati_role_to_partner_type() doesn't crash

akvo/rsr/migrations/0064_auto_20160317_1238.py, akvo/rsr/models/crs_add.py, akvo/rsr/models/fss.py, akvo/rsr/models/indicator.py, akvo/rsr/models/legacy_data.py, akvo/templates/myrsr/project_editor/related_objects/crs_add_input.html, akvo/templates/myrsr/project_editor/related_objects/indicator_input.html, akvo/templates/myrsr/project_editor/related_objects/indicator_period_input.html, akvo/templates/myrsr/project_editor/section_1.html, akvo/templates/myrsr/project_editor/section_8.html
=> [#1920] IATI v2.02 feedback

akvo/rsr/views/organisation.py, akvo/urls.py
=> [#2004] Create link for latest IATI file

akvo/rest/views/user.py
=> [#2074] Remove Django auth for requesting to join an organisation

akvo/rsr/models/indicator.py
=> [#2078] Fix 'calculated' actual values

akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/templates/myrsr/my_iati.html
=> [#2082] Realignment of user management tab

akvo/rsr/forms.py, akvo/rsr/views/organisation.py
=> [#2080] Fix bug in latest IATI file of organisation

akvo/rsr/admin.py, akvo/rsr/models/organisation_document.py, scripts/deployment/pip/requirements/2_rsr.txt
=> [#2077] Fix old organisation admin

akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss
=> [#2105] Fixed

akvo/rsr/static/scripts-src/project-main/project-main.js, akvo/rsr/static/scripts-src/project-main/project-main.jsx, akvo/templates/project_main_tabs/summary.html
=> [#2107] Fix 'See all updates' link on summary tab

akvo/iati/exports/elements/budget.py
=> [#2108] Fix budget items without value in IATI export

akvo/rest/views/indicator_period_data.py
=> [#2109] Fix indicator period data comment endpoint

akvo/rest/views/typeahead.py, akvo/templates/myrsr/my_projects.html
=> [#2113] Show results framework for private projects as well

akvo/rest/views/user.py
Fixes #2074.
Would be great to test this.
=> #2074 user employment application auth

akvo/templates/partials/project_header.html
=> [#1986] Fixed url encoding for Twitter share button

akvo/rest/views/project_update.py
=> [Fixes #1774] Validate date strings using regex

akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/templates/organisation_directory.html
Fixes #2128'
Also added icon for IATI ID and fixed colors in CSS.
=> [Fixes #2128] Changed social media icons to match other icons

akvo/locale/all/LC_MESSAGES/django.po, akvo/locale/es/LC_MESSAGES/django.po, akvo/locale/fr/LC_MESSAGES/django.po, akvo/templates/project_hierarchy.html
=> [Fixes #2023] Fixed typo 'to' -> 'too'

akvo/rsr/models/sector.py
=> [Fixes #2150] Added missing space

akvo/rest/viewsets.py
=> [Fixes #2143] Parameters starting with 'image_thumb_' are now supported

akvo/rsr/static/scripts-src/my-iati.js, akvo/rsr/static/scripts-src/my-iati.jsx
=> [#2102] Fix correct redirect link for new export

akvo/rsr/feeds.py
=> [Fixes #2155] Update limit lowered from 50 to 25 for RSS feeds

akvo/rest/serializers/__init__.py, akvo/rest/serializers/budget_item.py, akvo/rest/serializers/partnership.py, akvo/rest/serializers/planned_disbursement.py, akvo/rest/serializers/policy_marker.py, akvo/rest/serializers/project.py, akvo/rest/serializers/project_condition.py, akvo/rest/serializers/project_contact.py, akvo/rest/serializers/project_document.py, akvo/rest/serializers/project_location.py, akvo/rest/serializers/recipient_country.py, akvo/rest/serializers/region.py, akvo/rest/serializers/related_project.py, akvo/rest/serializers/result.py, akvo/rest/serializers/sector.py, akvo/rest/serializers/transaction.py, akvo/rest/views/project.py, akvo/rest/viewsets.py
=> [#2154] Performance improvements on project_extra resource

akvo/rsr/feeds.py, akvo/rsr/static/scripts-src/my-iati.js, akvo/rsr/static/scripts-src/my-iati.jsx, akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss
=> [#2102] Removed some of the filters in my IATI

akvo/rsr/models/project_document.py
=> [Fixes #2160] Added default title to 'project_document' model

akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/templates/project_main_tabs/finance.html
=> [Fixes #2162] Added placeholder for missing funders

akvo/rsr/admin.py
=> #2053 akvo page fields

akvo/rest/filters.py, akvo/rest/viewsets.py, akvo/rsr/admin.py
=> #2171 api extra parameters

akvo/rsr/management/commands/user_cleanup.py
=> [Fixes #1753] Added django management script for account cleanup

akvo/templates/myrsr/my_projects.html
=> [Fixes #2176] Project title now links to editor if user has permission

akvo/templates/myrsr/my_projects.html
=> #2006 disable complete projects

akvo/rsr/views/project.py, akvo/templates/partials/project_footer.html
=> [Fixes #2197] Five related documents now shown on project pages

akvo/rsr/views/account.py
=> [#2168] Add JSON response for /auth/token/

akvo/rest/views/project_update.py
=> [#1774] API Up bug

akvo/rsr/management/commands/project_cleanup.py, akvo/rsr/models/project.py
=> [#2003] Management command to clean up empty projects

akvo/rsr/models/organisation.py, akvo/rsr/models/project.py, akvo/rsr/signals.py, akvo/rsr/static/scripts-src/my-iati.js, akvo/rsr/views/my_rsr.py
=> [#2196] Invite content owned organisations

akvo/rsr/migrations/0071_auto_20160525_1036.py, akvo/rsr/migrations/0073_auto_20160525_1541.py
=> [#1804] Fix exception in IATI country migrations

akvo/rsr/reports.py, akvo/rsr/static/scripts-src/my-reports.js, akvo/rsr/static/scripts-src/my-reports.jsx, akvo/templates/myrsr/my_reports.html
=> [#2194] Plan Finland report

akvo/rsr/static/scripts-src/my-user-management.js, akvo/rsr/static/scripts-src/my-user-management.jsx, akvo/rsr/views/my_rsr.py
Fixes #1804 
User management page should now load correctly.
=> #1804 Exceptions in user management page fixed

akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss
=> #2189 'My Projects' action buttons no longer partially stack

akvo/rsr/views/organisation.py
=> [#2227] IATI link should always work

akvo/templates/partials/project_footer.html
=> [#2222] Changed project footer lay-out

akvo/rsr/views/my_rsr.py
=> [#2221] Do not show unpublished projects for Users and User Managers

akvo/rsr/models/budget_item.py, akvo/rsr/models/project.py
=> #2217 Budget items fix

akvo/rsr/static/scripts-src/my-user-management.js, akvo/rsr/static/scripts-src/my-user-management.jsx, akvo/rsr/views/my_rsr.py, akvo/templates/myrsr/user_management.html
=> [#2196] Updated permissions on user management page

akvo/rest/serializers/partnership.py, akvo/rsr/models/partnership.py, akvo/rsr/static/scripts-src/project-main/project-main-report.js, akvo/rsr/static/scripts-src/project-main/project-main-report.jsx
=> [#1801] Added currency to funding partners on report tab

akvo/rsr/views/project_update.py
=> [#2245] Remove location filter for updates on Akvo Pages

akvo/templates/project_main_tabs/summary.html
=> [#2242] Remove organisation location from project summary

akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss
=> [#2224] Publish errors aligned with progress bar

akvo/rest/views/user_management.py, akvo/rsr/views/account.py, akvo/templates/registration/activate.html, akvo/templates/registration/activation_email.txt, akvo/templates/registration/invite_activate.html, akvo/templates/registration/invited_user_message.html, akvo/templates/registration/invited_user_message.txt
=> [#2250] Removed date check from invitations

akvo/rsr/views/error.py, akvo/templates/500.html
=> [#2218] Refreshed 500 error template and fixed 500 error view

akvo/rsr/static/scripts-src/project-editor.js, akvo/rsr/static/scripts-src/project-editor.jsx
=> [#2229] Show mandatory fields for mandatory models

akvo/rsr/tests/iati_export/test_iati_export.py, akvo/rsr/tests/up/test_up.py, akvo/settings/80-travis.conf
=> [#2205] Initial tests for RSR Up

akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss
=> [#2257] CSS fixes for indicator period comments and updates

akvo/rsr/models/__init__.py
=> [Fixes #2261] Add additional permissions for org admins

akvo/rsr/models/project.py
=> [#2263] Restore editing/updating for cancelled and completed projects

akvo/rsr/admin.py
=> [#2276] Removed country field since it is no longer in database

akvo/codelists/models/country.py, akvo/rsr/models/country.py, akvo/rsr/models/employment.py, akvo/rsr/models/location.py, akvo/rsr/models/organisation_budget.py, akvo/rsr/models/organisation_document.py, akvo/rsr/models/transaction.py
=> [#2278] Country choice formatting

akvo/rest/views/project_editor.py
=> [#2275] Non-unicode values in project editor no longer cause uncaught exceptions

akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss
=> [#2266] Remove mid-word wrapping from full report description

akvo/rsr/static/scripts-src/project-main/project-main-report.js, akvo/rsr/static/scripts-src/project-main/project-main-report.jsx, akvo/rsr/static/scripts-src/project-main/project-main.js, akvo/rsr/static/scripts-src/project-main/project-main.jsx
=> [#2268] Added markdown support to project summary field

akvo/rsr/models/publishing_status.py
=> [#2269] Zero value allowed for funding and budget item amounts

akvo/rest/filters.py
=> [#2291] Catch invalid API filters and pass error on to user

akvo/rsr/models/project.py, akvo/rsr/views/project.py
=> [#2270] Remove unpublished and private projects from hierarchy

akvo/rest/fields.py
=> [#2273] Handle corrupt images in API calls

akvo/rsr/static/scripts-src/my-results.js, akvo/rsr/static/scripts-src/my-results.jsx
=> [#2267] Deselect period on result selection

akvo/rsr/static/scripts-src/my-results.js, akvo/rsr/static/scripts-src/my-results.jsx
=> [#2272] Edit approved update

akvo/rsr/static/scripts-src/cookie.js, akvo/rsr/static/scripts-src/cookie.jsx, akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/templates/base.html, akvo/templates/myrsr/my_details.html, akvo/templates/myrsr/my_iati.html, akvo/templates/myrsr/my_reports.html, akvo/templates/myrsr/my_results.html, akvo/templates/myrsr/my_results_select.html, akvo/templates/myrsr/project_editor/project_editor.html, akvo/templates/myrsr/user_management.html, akvo/templates/project_directory.html, akvo/templates/project_main.html, akvo/templates/sign_in.html
=> [#2225] Login layer for Test and UAT

akvo/rsr/migrations/0080_auto_20160707_1204.py, akvo/rsr/models/indicator.py, akvo/rsr/models/project.py, akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/templates/myrsr/project_editor/section_5.html
=> [#2182] Aggregation options for indicators

akvo/rsr/models/__init__.py, akvo/rsr/views/project.py, akvo/templates/myrsr/my_projects.html, akvo/templates/project_main_tabs/summary.html
=> [#2299] Allow organisation members to view and add updates to private projects

akvo/templates/base.html, akvo/templates/myrsr/project_editor/project_editor.html
=> [#2303] Move moment.js to base.html

akvo/rest/serializers/indicator.py, akvo/rsr/models/indicator.py, akvo/rsr/models/project.py, akvo/rsr/static/scripts-src/my-results.js, akvo/rsr/static/scripts-src/my-results.jsx, akvo/rsr/tests/results_framework/test_results_framework.py, akvo/settings/80-travis.conf, akvo/settings/__init__.py, akvo/templates/myrsr/my_results.html, akvo/templates/project_main.html
=> [#2181] Average aggregation of percentages

akvo/rsr/models/indicator.py, akvo/rsr/models/project.py, akvo/rsr/static/scripts-src/project-editor.js, akvo/rsr/static/scripts-src/project-editor.jsx, akvo/rsr/tests/results_framework/test_results_framework.py, akvo/templates/myrsr/project_editor/partials/related_object_header.html, akvo/templates/myrsr/project_editor/project_editor.html, akvo/templates/myrsr/project_editor/section_5.html
=> [#2316] Suva test feedback

akvo/rest/views/user_management.py, akvo/rsr/views/my_rsr.py
=> [#2321] Edit own account in User management when admin

akvo/iati/checks/fields/__init__.py, akvo/iati/checks/fields/language.py, akvo/rsr/migrations/0082_auto_20160811_1633.py
=> [#2320] Add IATI language check

akvo/rsr/static/scripts-src/my-results.js, akvo/rsr/static/scripts-src/my-results.jsx, akvo/rsr/views/my_rsr.py
=> [#2326] Admins have same permissions as M&E Managers

akvo/rsr/models/user.py
=> [#2328] Rewrite get_admin_employment_orgs()

akvo/rest/pagination.py, akvo/rest/renderers.py, akvo/rest/viewsets.py, akvo/settings/30-rsr.conf
=> [#2329] Offset for 'old' API

akvo/rsr/static/scripts-src/my-results-select.js, akvo/rsr/static/scripts-src/my-results-select.jsx
=> [#2347] Change <form> to <div> to prevent useless submit

akvo/rsr/static/scripts-src/project-editor.js, akvo/rsr/static/scripts-src/project-editor.jsx
Fixes #2359.
1. Check that filling in an empty, mandatory date field in the Project editor, updates the corresponding section completion progress bar. 
2. Make sure that the mandatory * doesn't go away after the field has been filled in. 
3. Check that mandatory OR datefields work correctly.  For instance 01. General Information > Start date (actual)/(planned) with IATI validation.
=> Fix problems with using react-datepicker for date fields

akvo/rest/viewsets.py
Adds a trivial missing import.   
Not sure what the workflow needs to be for such issues.
=> Add missing import for _ in rest/viewsets.py

akvo/rest/serializers/user.py, akvo/rest/views/user.py
Test with old versions of Up. I don't know the details but I think @stellanl does! 😛
=> #2364 up user fixes

akvo/rsr/admin.py
=> [#2389] Display group in Employment admin page

akvo/rsr/models/transaction.py, akvo/rsr/tests/iati_import/test_iati_import.py, akvo/rsr/tests/iati_import/xml_files.py, akvo/utils.py
Alternative fix of the iati transaction import problem. I think this fixes the root cause of the issue, and also addresses the lookup of the currency name correctly.
=> #2382 fix currency name lookup

akvo/rsr/forms.py, akvo/rsr/views/project.py, akvo/templates/update_add.html
This PR also adds a couple of new strings to be translated, but it doesn't do anything with them, because it would be easier to deal with all the translation issues in a separate issue.  
Closes #2040
=> [#2040] Add a js check for image upload size

akvo/rsr/static/scripts-src/donate-popup.js, akvo/rsr/static/scripts-src/donate-popup.jsx
This fixes the broken Donate popup after minification of the js code.  
Clicking on the donate button, should show a popup about being taken to an external site, and then clicking okay should work.
=> #1885 remove donation button

README.md, RELEASE_NOTES.md
Every PR is expected to come with a RELEASE_NOTES entry, unless it's not
worth mentioning there.  The pull-request template will also remind us.
=> [#2419] Move the RELEASE_NOTES from wiki to repo

RELEASE_NOTES.md, akvo/rsr/models/indicator.py, akvo/rsr/tests/models/test_indicator.py
=> [#2426] Fix UnicodeEncodeError on adding an IndicatorPeriodData

akvo/rsr/tests/models/test_indicator.py
Should fix test error on rsr.test.
=> [#2426] Add tearDown to IndicatorPeriodModelTestCase

.travis.yml
=> [#2430] Cache pip directory to cut down build time on Travis

RELEASE_NOTES.md, akvo/templates/reportserver/BIRT/data_quality.rptdesign
=> #2434 data quality report counts

akvo/iati/imports/mappers/Result_only/__init__.py, akvo/iati/imports/mappers/dates.py, akvo/rsr/models/iati_import.py, akvo/rsr/tests/iati_import/test_iati_import.py, akvo/rsr/tests/iati_import/xml_files.py
=> #2442 only mapper

akvo/rsr/tests/iati_import/test_iati_import.py, akvo/rsr/tests/iati_import/xml_files.py
Get the builds on Travis passing by bringing back coverage to 100%
=> [#2442] Minor test change to bring coverage to 100%

RELEASE_NOTES.md, akvo/iati/imports/__init__.py, akvo/iati/imports/mappers/classifications.py, akvo/iati/imports/mappers/contacts.py, akvo/iati/imports/mappers/financials.py, akvo/iati/imports/mappers/humanitarian.py, akvo/iati/imports/mappers/locations.py, akvo/iati/imports/mappers/partnerships.py, akvo/iati/imports/mappers/related_projects.py, akvo/iati/imports/mappers/results.py, akvo/iati/imports/mappers/special_reporting.py, akvo/rsr/admin.py, akvo/rsr/tests/iati_import/test_iati_import.py, akvo/rsr/tests/iati_import/xml_files.py
=> #2452 selective iati import

RELEASE_NOTES.md, akvo/iati/imports/__init__.py, akvo/iati/imports/mappers/classifications.py, akvo/iati/imports/mappers/contacts.py, akvo/iati/imports/mappers/financials.py, akvo/iati/imports/mappers/humanitarian.py, akvo/iati/imports/mappers/locations.py, akvo/iati/imports/mappers/partnerships.py, akvo/iati/imports/mappers/related_projects.py, akvo/iati/imports/mappers/results.py, akvo/iati/imports/mappers/special_reporting.py, akvo/rsr/admin.py, akvo/rsr/tests/iati_import/test_iati_import.py, akvo/rsr/tests/iati_import/xml_files.py
The changes for v3.18.2 are on develop interleaved with other changes. Hence, this is a separate branch with just the changes that need to go in to this hot-fix.
=> Hot fix 3.18.2 changes from develop

akvo/rsr/migrations/0087_auto_20161110_0920.py
=> Changes from master after v3.18.2 release

RELEASE_NOTES.md, akvo/rsr/models/user.py
=> [#2381] Use only approved organisation as legacy_org

akvo/rsr/migrations/0088_auto_20161116_1214.py
The code works without it, but it's needed to make the migrations machinery happy in the long run.
=> [#2442] Add migration for the mapper

akvo/templates/registration/activation_email.txt
=> [#2415] Mention RSR mobile application on employment confirmation

akvo/templates/reportserver/BIRT/Project-results-single.rptdesign
=> [#2456]Sort results and indicators on order, id

RELEASE_NOTES.md, akvo/templates/reportserver/BIRT/Project-results-simple-table.rptdesign
=> [#2457]Map result type numbers to strings

akvo/rsr/middleware.py, akvo/rsr/tests/test_middleware.py
Move request.get_host into the try block where it was originally meant to be.
=> [#2487] Fix problem with disallowed hosts in requests

akvo/rsr/models/__init__.py, akvo/rsr/tests/rest/test_administrative_location.py, akvo/rsr/tests/rest/test_permissions.py
AdministrativeLocation should be deletable from the project editor, by everyone
who has the permissions to edit a project.
Closes #2482
=> [#2482] Add permissions for AdministrativeLocation

akvo/rsr/models/project.py, akvo/rsr/tests/results_framework/test_results_framework.py
=> [#2484] Importing Results does not import IndicatorReferences

akvo/iati/checks/fields/partners.py, akvo/iati/checks/fields/related_activities.py, akvo/iati/checks/fields/transactions.py, akvo/rest/views/typeahead.py, akvo/rsr/static/scripts-src/project-editor.js, akvo/rsr/static/scripts-src/project-editor.jsx
=> Client side hot-fixes for big projects for hot fix release

RELEASE_NOTES.md, akvo/rsr/models/country.py, akvo/rsr/tests/rest/test_recipient_country.py
=> [#2514] Return unicode in RecipientCountry.iati_country_unicode

RELEASE_NOTES.md, akvo/rsr/models/custom_field.py, akvo/rsr/tests/models/test_custom_field.py
=> [#2516] Fix problems with unicode values in ProjectCustomFields

RELEASE_NOTES.md, akvo/rest/views/typeahead.py
=> Release 3.20.1 Bogotá (hot-fix)

RELEASE_NOTES.md, akvo/rsr/management/commands/fix_orphaned_periods.py, akvo/rsr/migrations/0089_auto_20170207_0707.py, akvo/rsr/migrations/0089_auto_20170207_2235.py, akvo/rsr/migrations/0090_auto_20170207_2235.py, akvo/rsr/migrations/0091_auto_20170208_1035.py, akvo/rsr/models/indicator.py, akvo/rsr/models/project.py, akvo/rsr/tests/results_framework/test_results_framework.py, akvo/templates/myrsr/project_editor/related_objects/indicator_input.html
Also, needs the management command `fix_orphaned_periods` to be run to fix the data in the DB. 
The output of the migration script needs to be carefully looked at, to find any more periods and indicators that need fixing, other than the ones already fixed by default by the script.
=> Release 3.20.2 Bogotá (hot-fix)

RELEASE_NOTES.md, akvo/rest/views/indicator_period_data.py, akvo/rest/views/partnership.py
=> Fix 504s on the results framework page

akvo/rsr/migrations/0092_auto_20170216_1209.py
=> [#2486] Add piwik ids for PartnerSites without an id

akvo/rsr/static/scripts-src/my-details-employments.js, akvo/rsr/static/scripts-src/my-details-employments.jsx, akvo/rsr/static/scripts-src/my-iati.js, akvo/rsr/static/scripts-src/my-iati.jsx, akvo/rsr/static/scripts-src/my-results.js, akvo/rsr/static/scripts-src/my-results.jsx, akvo/rsr/static/scripts-src/my-user-management.js, akvo/rsr/static/scripts-src/my-user-management.jsx, akvo/rsr/static/scripts-src/project-editor.js, akvo/rsr/static/scripts-src/project-editor.jsx
=> Handle parsing non-JSON responses in a bunch of places

akvo/rsr/admin.py
Over-ride the username field in the UserChangeForm and UserCreationForm used in
the Django Admin.  The forms have max_length different from what the model has.
Closes #2543
=> [#2543] Fix incorrect username max_length validation in admin

akvo/rsr/migrations/0094_auto_20170222_1059.py, akvo/rsr/models/keyword.py
=> [#2554] Increase Keyword label max_length to 100

akvo/rsr/migrations/0094_auto_20170220_1510.py, akvo/rsr/models/partner_site.py, akvo/rsr/tests/rest/test_permissions.py, akvo/rsr/tests/test_middleware.py
=> [#2486] Make PartnerSite.piwik_id a non-nullable field

akvo/rsr/migrations/0095_auto_20170309_0901.py
=> [#2554] Fix conflicting migrations

RELEASE_NOTES.md, akvo/rest/views/typeahead.py, akvo/rsr/static/scripts-src/project-editor.js, akvo/rsr/static/scripts-src/project-editor.jsx, akvo/rsr/tests/rest/test_typeahead.py
=> [#1853] Show only organisation projects on Akvo sites search

akvo/settings/40-pipeline.conf
=> [#2569] Fix Pipeline settings

RELEASE_NOTES.md
=> Release 3.22 Chisinau hotfix

RELEASE_NOTES.md, akvo/utils.py
=> Release 3.22 Chisinau hotfix II

akvo/rsr/views/account.py, akvo/rsr/views/my_rsr.py, akvo/templates/navigation/header.html
=> [#2581] Change landing page for My RSR

akvo/rsr/models/indicator.py, akvo/rsr/tests/models/test_indicator.py
=> [#2563] Deleting indicator update should change actual value comment

akvo/rsr/management/commands/delete_spam_users.py
=> [#2454] Add management command to delete spam users

akvo/rest/views/project_editor.py, akvo/rsr/tests/rest/test_project_editor.py
=> [#2605] Fix bug handling unicode error messages in project editor

akvo/rsr/tests/views/test_project.py, akvo/rsr/views/project.py
=> [#2603] Fix bug in listing non partner projects on partner site

RELEASE_NOTES.md, akvo/rest/views/project_editor.py, akvo/rsr/tests/rest/test_project_editor.py, akvo/rsr/tests/views/test_project.py, akvo/rsr/views/project.py
=> Release 3.23.1 New Delhi (hot-fix)

akvo/templates/partials/project_header.html
=> [#2609] Add edit project link to project page

akvo/templates/project_directory.html
=> [#2616] Move keywords filter to the top of list of filters

akvo/rsr/models/location.py, akvo/rsr/tests/rest/test_project_location.py
=> [#2634] Fix broken project_location response when country is unicode

akvo/rsr/tests/views/test_my_rsr.py, akvo/rsr/views/my_rsr.py
Searches with long query terms would time out on the my projects page's
search.  This commit refactors the search code to use Q objects instead of
nested filters to make the search much faster.
Closes #2636
=> [#2636] Use Q object to make search on my projects more efficient

akvo/templates/base.html
Closes #2677
```markdown
Fixed problem with date fields becoming unusable - [#2677](https://github.com/akvo/akvo-rsr/issues/2677)
```
=> [#2677] Load moment before react-datepicker since it's a dependency

RELEASE_NOTES.md
=> Changes for hot-fix for broken date fields

akvo/rsr/models/link.py
```markdown
Open related links in new tab - [#2656](https://github.com/akvo/akvo-rsr/issues/2656)
```
=> [#2656] Open related links and documents in new tab

RELEASE_NOTES.md, akvo/templates/base.html
=> Release 3.25.1 (hot-fix)

akvo/rsr/admin.py, akvo/rsr/admin_actions.py
```markdown
Admin action to mark projects as complete [#2671](https://github.com/akvo/akvo-rsr/issues/2671)
```
=> Admin action to set projects complete

akvo/settings/30-rsr.conf
=> Update setting for new results beta testers

akvo/templates/base.html
Closes #2708
```markdown
Fix problem with react elements not being closed when clicking outside them [#2708](https://github.com/akvo/akvo-rsr/issues/2708)
```
=> [#2708] Load react-clickoutside.js before other react stuff

akvo/settings/30-rsr.conf
=> Add Spider as a results framework beta tester

akvo/rsr/static/styles-src/results.css, akvo/rsr/static/styles-src/results.scss
Closes #2759
```markdown
Fix long indicator titles in Results view [#2759](https://github.com/akvo/akvo-rsr/issues/2759)
```
=> [#2759] Wrap indicator title to not overlap progress indicator

akvo/rsr/static/scripts-src/my-results/components/updates/UpdateForm.jsx
=> [#2810] Fix css issue in update form for percentage updates

akvo/rsr/static/scripts-src/my-results.js, akvo/rsr/static/scripts-src/my-results.jsx
The changes seem to have been made in e56f029f2fc94cab17e6da60f7aa9e9351dafede
=> [#2781] Revert change accidentally made to old results UI

akvo/rsr/static/styles-src/results.css, akvo/rsr/static/styles-src/results.scss
Go to an indicator that has several periods. Check that the periods are separated by a stroke.
=> [#2807] Added a separator when several periods are present

akvo/rsr/static/scripts-src/my-results.js, akvo/rsr/static/scripts-src/my-results.jsx
1. Test if adding an update to a percentage indicator measure works correctly
2. Test that the add new indicator button is not visible on periods (of %age indicator measures) that already have an update
=> [#2815] Correctly handle %age indicator updates from the old UI

akvo/rsr/management/commands/update_custom_fields.py
Fixes #2826
```markdown
Add management command for updating project custom fields
```
=> [#2826] Add management command for updating project custom fields

akvo/rsr/static/scripts-src/my-results/components/updates/Updates.jsx, akvo/rsr/static/styles-src/results.css, akvo/rsr/static/styles-src/results.scss
Check if text overflow when qualitative update is a huge paragrapher
=> [#2840] Fixed small issues

akvo/rsr/migrations/0107_auto_20170913_0904.py
=> [#2772] Add missing migration adding on_delete to IndicatorLabel

akvo/rsr/migrations/0108_auto_20170915_0902.py, akvo/rsr/models/link.py
```markdown
Make URL mandatory for link field. [#2864]https://github.com/akvo/akvo-rsr/issues/2864
```
=> [#2864] Show a fragment of the URL, if no caption present

akvo/rsr/migrations/0109_auto_20170911_1039.py, akvo/rsr/static/scripts-src/my-results/components/updates/Updates.jsx
```markdown
Migrate actual values and comments in periods entered in the project editor to indicator updates [#2849](https://github.com/akvo/akvo-rsr/issues/2849)
```
=> [#2849] Create updates for periods which have been directly updated

akvo/rsr/models/result/indicator_label.py, akvo/rsr/static/scripts-src/project-editor.js, akvo/rsr/static/scripts-src/project-editor.jsx, akvo/templates/myrsr/project_editor/related_objects/indicator_input.html
=> [#2883] hide indicator labels

akvo/rsr/static/scripts-src/my-results/components/Periods.jsx
=> [#2675] Hide updates in the public view of the results framework

akvo/rsr/context_processors.py, akvo/rsr/static/scripts-src/rsr.js, akvo/templates/base.html, scripts/deployment/pip/requirements/2_rsr.txt
This is currently deployed on the dev instance using the new hosted version of sentry (sentry.io).  This PR will need us to migrate to using the hosted version of Sentry for things to work on Live/Test/UAT
```
Improve error reporting on the javascript side [#2871](https://github.com/akvo/akvo-rsr/issues/2871)
```
=> [#2871] Add Sentry notifications for javascript errors

akvo/templates/reportserver/BIRT/Programme-results-simple-table.rptdesign, akvo/templates/reportserver/BIRT/Project-results-simple-table.rptdesign, akvo/templates/reportserver/BIRT/Project-results-single.rptdesign
=> Remove unused datasources

akvo/rsr/views/my_rsr.py
=> [#2856] Order the roles in the user management dialog

akvo/rsr/filters.py, akvo/rsr/models/organisation.py, akvo/rsr/models/project.py, akvo/rsr/views/project.py, akvo/rsr/views/project_update.py, akvo/rsr/views/utils.py, akvo/templates/organisation_main.html
=> Use a consistent definition for organisation updates

akvo/rsr/management/commands/fix_orphaned_periods.py
Closes #2946 
This commit changes the old script to fix orphaned periods to make it detect orphaned periods and indicators if we can, and fix them. 
```markdown
More orphaned periods found in the DB [#2946](https://github.com/akvo/akvo-rsr/issues/2946)
```
=> [#2946] Automatically find orphaned indicators and periods

akvo/rsr/models/project.py
=> [#2950] Import dimensions when the result framework is imported

akvo/rsr/models/budget_item.py
=> [#2298] Remove leftover debug statements

akvo/rest/views/project_editor.py, akvo/rsr/migrations/0117_auto_20171201_0913.py
Closes #2984
```markdown
Trim disaggregation names and values [#2984](https://github.com/akvo/akvo-rsr/issues/2984)
```
=> [#2984] Trim all text data entered in the project editor

akvo/rest/serializers/__init__.py, akvo/rest/serializers/narrative_report.py, akvo/rest/urls.py, akvo/rest/views/__init__.py, akvo/rest/views/narrative_report.py, akvo/rsr/migrations/0117_auto_20171205_0849.py, akvo/rsr/migrations/0117_auto_20171206_1518.py, akvo/rsr/models/__init__.py, akvo/rsr/models/result/__init__.py, akvo/rsr/models/result/narrative_report.py, akvo/rsr/tests/rest/test_permissions.py
=> Add Narrative report model and API end-points

akvo/templates/reportserver/README.md
=> [#3028]Improve docs.

akvo/rsr/models/result/indicator_period_aggregation.py
The view, rsr_indicator_period_disaggregation, adds value, numerator and denominator for all disaggregations of a period.
=> [#3026] Add view for aggregates of disaggregations

akvo/rsr/static/scripts-src/my-results/components/App.jsx
=> Fix organisation_indicator_label fetch URL typo

akvo/rsr/migrations/0119_auto_20180104_1310.py
=> [#3012] Add a missing migration for fixed typo in NarrativeReport

akvo/settings/20-default.conf
=> [#3041] Change RSR's Piwik ID

akvo/rsr/static/scripts-src/my-reports.js, akvo/rsr/static/scripts-src/my-reports.jsx
=> Fix broken disabling of my reports download button

akvo/rest/views/typeahead.py, akvo/rsr/models/user.py, akvo/rsr/views/my_rsr.py
Easy fixes to make it easier to work with couple of MyRSR pages.  This makes it
easier to play around with these pages, while trying to restructure MyRSR
=> [#3045] Add missing select_related calls to couple of MyRSR pages

akvo/rest/views/user_management.py, akvo/rsr/tests/rest/test_user_management.py, scripts/deployment/pip/requirements/3_testing.txt
It's still not perfect, but cleaned up the code and added a bunch of tests.
Unable to find the problem with users not receiving activation emails.
=> [#2920] Add a bunch of tests and refactor invite_user code

scripts/devhelpers/release_notes.py
=> [#3090] Script to create RELEASE NOTES draft for a milestone

akvo/templates/update_add.html
=> [#3082] Fix broken add update from the french site

akvo/rsr/forms.py, akvo/rsr/views/project.py
Closes #3094 
Ask me how to test, I won't post it here 😉
=> [#3094] Secure posting of updates

akvo/rest/serializers/indicator_period_data.py, akvo/rest/views/indicator_period_data.py, akvo/rest/viewsets.py
=> Couple of latency fixes when changing indicator update state

.travis.yml, akvo/rsr/migrations/0123_periodactualvalue_perioddisaggregation.py, akvo/rsr/tests/rest/migration_data.py
=> [#3064] Add a check for missing migrations on Travis

akvo/rsr/management/commands/reinstate_implementors.py
=> Release 3.36.1 - hotfix

akvo/rsr/management/commands/add_periods.py, akvo/rsr/management/commands/replace_periods.py
=> [#3110] sript adding indicator periods

akvo/rsr/static/scripts-src/my-iati.js, akvo/rsr/static/scripts-src/my-iati.jsx, akvo/rsr/static/scripts-src/project-editor.js, akvo/rsr/static/scripts-src/project-editor.jsx, akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss
=> Link from IATI error messages to the project editor

akvo/rsr/views/__init__.py
=> [#3068] When logged in, landing page is My RSR

akvo/rsr/static/scripts-src/my-reports.js, akvo/rsr/static/scripts-src/my-reports.jsx, akvo/rsr/static/scripts-src/my-results-select.js, akvo/rsr/static/scripts-src/my-results-select.jsx
The 'container' element was renamed to 'container-fluid' confusing the code in my-reports.jsx.
=> [#3127] Fix renamed element ID

akvo/rsr/static/scripts-src/my-results/components/RSRUpdates.jsx, akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss, akvo/templates/myrsr/my_projects.html, akvo/templates/update_directory.html
=> [#3127] Various improvements

akvo/templates/navigation/header.html
=> [#3147] Change the logo link to always go to project directory

akvo/rsr/models/project.py
=> [#3155] Order funding organisations alphabetically

akvo/rsr/models/result/indicator_period_aggregation.py, akvo/rsr/tests/models/test_results_aggregation.py
Also add tests showing that only approved updates are included in the aggregation
Closes #3172
=> [#3172] Fix aggregation view

akvo/rest/urls.py, akvo/templates/myrsr/my_details.html, akvo/templates/myrsr/my_reports.html, akvo/templates/partials/project_footer.html
Fix a few url template tags that target the API.
They now need to include the version as a first parameter.
=> [#3122] Fix url template tags

akvo/rsr/migrations/0125_auto_20180320_1252.py, akvo/rsr/models/partner_site.py, akvo/rsr/tests/test_validators.py, akvo/rsr/validators.py
=> [#3124] Fix hostname validation for partner sites

akvo/rest/viewsets.py, akvo/rsr/tests/rest/test_permissions.py, akvo/rsr/tests/rest/test_project.py, akvo/rsr/tests/rest/test_project_location.py, akvo/rsr/tests/rest/test_project_update.py, akvo/rsr/tests/rest/test_recipient_country.py
Also, filter out all the other models that are related to such projects.
Closes #3131
=> [#3131] Exclude unpublished projects from anonymous user APIs

akvo/templates/project_main_tabs/summary.html
Since it is going to be removed from the project directory.
Closes #3137
=> [#3137] Add budget to summary

akvo/iati/checks/fields/results.py, akvo/iati/exports/elements/result.py, akvo/rsr/tests/iati_checks/test_iati_checks_fields_results.py, akvo/rsr/tests/iati_export/test_iati_export.py
=> [#3191] Baseline year needs to be a positiveInteger

akvo/templates/myrsr/my_projects.html
=> [#3144] Add link to view all projects, after searching

akvo/rest/fields.py, akvo/rest/serializers/project.py, akvo/rsr/templatetags/maps.py, akvo/rsr/tests/rsr_utils/test_utils.py, akvo/rsr/views/project.py, akvo/utils.py
=> [#3165] Use a placeholder image when developing locally

akvo/templates/myrsr/my_projects.html
=> [#3196] Add project location, relationships and end date

akvo/rsr/models/__init__.py
=> [#2315] Project Editors and M&E Managers should be able to IATI export

akvo/rsr/static/package-lock.json, akvo/rsr/static/package.json, akvo/rsr/static/tests/scripts-src/my-results/utils.test.js
=> [#3190] Added tests for some store dependency functions in utils

akvo/rsr/models/__init__.py, akvo/rsr/views/my_rsr.py, scripts/deployment/pip/requirements/2_rsr.txt
=> [#3238] results ui: Allow org admin to perform ME Manager actions

.gitignore, akvo/rsr/admin.py, akvo/rsr/migrations/0127_auto_20180529_0955.py, scripts/deployment/pip/requirements/2_rsr.txt
=> [#3244] Upgrade psycopg

akvo/rest/renderers.py
=> [#3200] Add a sensible filename content hint

akvo/rest/views/organisation.py
=> [#3249] Fix count of organisations in a directory search

akvo/rsr/models/project.py, akvo/rsr/models/result/indicator.py, akvo/rsr/models/result/indicator_period.py, akvo/rsr/tests/results_framework/test_results_framework.py
=> [#3258] Fix creation of deleted indicators when parent updated

akvo/rsr/models/project.py, akvo/rsr/models/result/indicator.py, akvo/rsr/models/result/indicator_period.py, akvo/rsr/tests/results_framework/test_results_framework.py
=> [#3258] Hot-fix 3.37.2 changes to develop

akvo/rsr/static/scripts-src/project-editor.js, akvo/rsr/static/scripts-src/project-editor.jsx
=>  [#3267] Fix project editor save incorrectly detecting page changes

akvo/rsr/views/project.py
=> [#3265] Masquerade period dates in the public results view

akvo/rsr/static/scripts-src/project-editor.js, akvo/rsr/static/scripts-src/project-editor.jsx
=> RSR release 3.37.4 Nassau hot-fix

akvo/rsr/static/scripts-src/directory-utils.js, akvo/rsr/static/scripts-src/directory-utils.jsx
=> [#3264] Jump to page 1 when filters in a directory change

akvo/rsr/management/commands/anonymize_user.py
=> [#3283] Initial cut of script to anonymize user information

akvo/rest/urls.py
=> [#3296] rest: Add a version api root view as docs

akvo/rest/views/project_update.py, akvo/rsr/models/organisation.py, akvo/rsr/static/scripts-src/directory-utils.js, akvo/rsr/static/scripts-src/directory-utils.jsx, akvo/templates/organisation_main.html
=> Make update count on organisation summary page and update directory consistent

akvo/rest/views/project_editor.py, akvo/rsr/models/project.py, akvo/templates/myrsr/project_editor/project_editor.html
Filter for the LogEntry objects using id and content type.
Include the action_time value and use that in lieu of Project.last_modified_at since this field is only updated when the Project model changes.
=> [#3318] Fix problems with modified by

akvo/iati/exports/elements/result.py, akvo/rsr/tests/iati_export/test_iati_export.py
=> [#3222] iati_export: Fix measure value for qualitative indicator

akvo/settings/30-rsr.conf
=> [#3217] Disable the project access feature

akvo/iati/exports/elements/result.py, akvo/rsr/static/scripts-src/my-user-management.js, akvo/rsr/static/scripts-src/my-user-management.jsx, akvo/rsr/tests/iati_export/test_iati_export.py, akvo/rsr/views/my_rsr.py, akvo/settings/30-rsr.conf, akvo/templates/myrsr/user_projects.html
=> Post 3.39 release merge back into develop

akvo/templates/myrsr/my_project.html
=> [#3294] my_project: Add private "tag" for private projects

scripts/deployment/pip/requirements/2_rsr.txt
=> Update gunicorn based on vulnerability report from GitHub

akvo/rsr/backends.py, akvo/settings/10-base.conf, scripts/deployment/pip/requirements/2_rsr.txt
=> [#3357] Use the bcrypt hasher for hashing passwords

akvo/rsr/context_processors.py, akvo/rsr/static/scripts-src/my-results/components/updates/UpdateForm.jsx, akvo/settings/85-gmaps.conf, akvo/templates/inclusion_tags/maps.html, akvo/templates/organisation_directory.html, akvo/templates/organisation_main.html, akvo/templates/project_directory.html, akvo/templates/update_directory.html
=> Release v3.39.2 Belmopan

akvo/rsr/static/scripts-src/my-results/components/RSRUpdates.jsx, akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss
=> [#3367] Use react-datepicker Update event_date

akvo/rsr/static/scripts-src/my-results/components/RSRUpdates.jsx, akvo/rsr/static/styles-src/main.css, akvo/rsr/static/styles-src/main.scss
=> RSR release 3.39.3 Belmopan hot-fix

akvo/rsr/forms.py, akvo/rsr/tests/views/test_account.py
=> [#3357] Set minimum password length to 12

akvo/rsr/views/account.py
=> [#3395] Handle failed login validation errors when fetching api_key

akvo/iati/checks/fields/results.py, akvo/rsr/tests/iati_checks/test_iati_checks_fields_results.py
=> [#3392] Fix iati checks for results with only qualitative indicators

akvo/iati/checks/fields/results.py, akvo/rsr/permissions.py
=> Check content owned orgs only once per request

akvo/rest/views/project_editor.py, akvo/rsr/static/scripts-src/project-editor.js, akvo/rsr/static/scripts-src/project-editor.jsx
Modify the endpoint to return HTTP status codes 201 and 400 for success and failure respectively, and refactor the client side code to determine action depending on the response status.
Also check that the user can change the project results are being imported to and modify the returned data some.
=> [#3422] Modify API endpoint triggering results import

akvo/rest/pagination.py, akvo/rest/views/indicator_dimension.py, akvo/rsr/static/scripts-src/my-results/actions/model-actions.js, akvo/rsr/static/scripts-src/my-results/const.js, akvo/rsr/static/scripts-src/my-results/utils.js, akvo/settings/30-rsr.conf
=> Use a bigger page size when requesting for indicator dimensions

akvo/rsr/static/scripts-src/my-results/utils.js
=> [#3420] Apply proper filtering for indicator dimensions

akvo/rest/pagination.py, akvo/rest/views/indicator_dimension.py, akvo/rsr/static/scripts-src/my-results/actions/model-actions.js, akvo/rsr/static/scripts-src/my-results/const.js, akvo/rsr/static/scripts-src/my-results/utils.js, akvo/settings/30-rsr.conf
=> RSR release 3.40.3 Managua hot-fix

akvo/rsr/views/my_rsr.py
=> [#3293] Revert user count on mgmnt page

akvo/rsr/static/scripts-src/my-results/utils.js
=> [#3382] New updates don't come with a _meta attribute

nginx/default.conf
=> updating url to k8s reportserver
